### ISSUE TITLE
0.3.8 crashing on startup - Exception in server tick loop

### ISSUE THREAD

**Issue by Shindur** [NillerMedDild/Enigmatica5#100]
**Modpack version**
0.3.8

**Issue**
Load up the game and it crashes on startup. Log seems to point to ultra amplified dimension mod.

**Logs**
https://pastebin.com/3g0bsc7H

**Comment by NielsPilgaard** [comment]
It crashed when it loaded the world, not non startup, right? :)
I'll look into this asap.

**Comment by Shindur** [comment]
It crashed when loading the pack, didn't get a chance to load the world.

**Comment by Shindur** [comment]
It might've been on world load.. I don't remember honestly. But I was able to load into my world the second time around.. Random crashing?

**Comment by NielsPilgaard** [comment]
Errr.. that's odd. Thanks for trying again :P

**Comment by TelepathicGrunt** [comment]
@Shindur Did you make any changes to the ultra amplified config and if so, may I see the config file? it might help me see why it crashed during world loading

**Comment by Shindur** [comment]
I did not touch the Ultra Amplified config. Only changes I made to the pack was adding light level overlay and update mining gadgets/industrial foregoing. IF was after the crash occurred and I haven't had the crash again since.

**Comment by TelepathicGrunt** [comment]
Weird. Well, let me know if it happens again but hopefully it was just a one time oddity!
