### ISSUE TITLE
Ore Excavation doesn't work

### ISSUE THREAD

**Issue by loaimohamed** [NillerMedDild/Enigmatica5#101]
**Modpack version**
0.3.8

**Issue**
Ore Excavation doesn't work

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NielsPilgaard** [comment]
It's only enabled for ores, could that be the issue?

**Comment by lovetalker** [comment]
Can confirm, only enabled for ores. Shape mining is disabled.

Hammers are supposed to be the solution to this. Is there any way to chop wood faster?

**Comment by Darkere** [comment]
There should be a larger axe with a similar recipe to the hammers that works on trees.

**Comment by lovetalker** [comment]
If there is one, I haven't found it in NEI.

**Comment by NielsPilgaard** [comment]
No large axes yet I'm afraid
