### ISSUE TITLE
0.3.8 Server Ticking block entity after updating

### ISSUE THREAD

**Issue by BloodyKujo** [NillerMedDild/Enigmatica5#104]
**Modpack version**
0.3.8 Server

**Issue**
After upgrading from 0.3.5 to 0.3.8 the server would crash when a user logged on. Fixed by removing offending Mekanism tiles with NBTExplorer. 

**Logs**
https://pastebin.com/embed_js/DtFNLRtq
https://pastebin.com/QWpGErcz
https://pastebin.com/gTkM10DU

**Comment by NielsPilgaard** [comment]
My apologies, I've heard that Mekanism made a breaking change to machine inventories, and all machines should be emptied prior to updating :/
