### ISSUE TITLE
More Dragon Eggs

### ISSUE THREAD

**Issue by NielsPilgaard** [NillerMedDild/Enigmatica5#108]
https://www.curseforge.com/minecraft/mc-mods/more-dragon-eggs

**Comment by NielsPilgaard** [comment]
~~Doesn't seem to do anything.~~ It works perfectly, I should go to sleep.

**Comment by Darkere** [comment]
uh wat
its my mod :P

**Comment by NielsPilgaard** [comment]
I know, was about to write you :P I used the kill command to kill the dragon the first time, then killed it the old fashioned way, which resulted in a new dragon egg - but the vanilla variety. Now that I think about it, that's not default dragon behaviour, is the vanilla egg one of the possibilities?

**Comment by Darkere** [comment]
:D you are misunderstanding what the mod does lol.

Vanilla doesn't spawn a dragon egg after the first kill. This mod makes it so that it drops a dragon egg every time.

**Comment by NielsPilgaard** [comment]
Lol, I wonder how I got that wrong, it's so obvious now :P

**Comment by NielsPilgaard** [comment]
... It works great, thanks!

**Comment by TheUntamed** [comment]
Was that changed with mc 1.15.2? Because in 1.12.2 the dragon gave an egg every single time it was killed.

**Comment by Darkere** [comment]
Nope. It didn't do that in 1.12 either. That was a mod adding it. Draconic evolution for example.
