### ISSUE TITLE
Simple Farming Cherry Tree Crash

### ISSUE THREAD

**Issue by Jerome15** [NillerMedDild/Enigmatica5#11]
**Modpack version**
0.2.0

**Issue**
Simple Farming Cherry Tree crash the server when leafs are mine down. 

**Logs**
https://pastebin.com/tXvsxtr5

**Comment by NielsPilgaard** [comment]
Thanks for the report. I don't see any crash in that log, could you link to the crash report please?

**Comment by Jerome15** [comment]
Hi sorry about that, sent the wrong thing. Here is the crash report. https://pastebin.com/Cy7W90jg

**Comment by NielsPilgaard** [comment]
Thanks! I'll report it to the mod author tonight :)

**Comment by NielsPilgaard** [comment]
I reported the issue here: https://github.com/enemeez/simplefarming/issues/54
