### ISSUE TITLE
Terraforged Generates Mow Roofs 

### ISSUE THREAD

**Issue by lovetalker** [NillerMedDild/Enigmatica5#112]
**Modpack version**
0.3.8

**Issue**
Terraforged generates worlds with a layer of Mow roofs under sand, (still beneath the dirt like it should be, I suppose,) which is definitely not intended. Are they considered a natural stone type by accident or something? Also, it seems like regular stone is a bit rarer than it may have been intended to be. Might be important to have some extra recipes for using diorite, granite, basalt, etc.

They eat a boatload of ram when there are thousands of them, because they aren't regular blocks.
**Logs**
Nullpo, no logs.

**Comment by NielsPilgaard** [comment]
Thanks for the report, I believe this has been fixed in a recent update of TerraForged, I'll update it asap :)

Will also look into lack of stone.
