### ISSUE TITLE
Configure and Update Nether Portal Spread

### ISSUE THREAD

**Issue by ricksouth** [NillerMedDild/Enigmatica5#117]
I've updated the mod to 3.0 and added configurable spread blocks. I'm looking forward to what configuration you'll come up with. Sorry for the extra work ;)

[https://www.curseforge.com/minecraft/mc-mods/nether-portal-spread](https://www.curseforge.com/minecraft/mc-mods/nether-portal-spread)

**Comment by NielsPilgaard** [comment]
Looking forward to it, thanks :D

**Comment by NielsPilgaard** [comment]
The new .txt based config doesn't reload, right?

**Comment by ricksouth** [comment]
What do you mean with reload? You'll have to reboot the game/server for it to process the settings.

**Comment by NielsPilgaard** [comment]
I thought so - I meant whether it gets reloaded by the /reload command, like most configs, as you guessed.

**Comment by ricksouth** [comment]
I'm not exactly sure what /reload does, but I don't think it does. The mod reads the text file on the "load complete"-event in Forge. Do you think there's a necessity for it to re-read the spread settings on reload?

**Comment by NielsPilgaard** [comment]
Nah I don't think it's important, I was just curious cause it would've saved me a little time, but no big deal :)

**Comment by NielsPilgaard** [comment]
I take it I can't add my own blocks to the spreadsettings.txt, right?

**Comment by ricksouth** [comment]
You should be able to I think! Haven't tested it though. The mod by default adds "minecraft:" in front of the name values when there's no : in there. So if you add modwithablock:new_stone or whatever its value is it *should* work.
