### ISSUE TITLE
Storage Drawers UI not working

### ISSUE THREAD

**Issue by RoNoN-85** [NillerMedDild/Enigmatica5#120]
**Modpack version**
0.3.8

**Issue**
Can no longer open the Storage Drawers UI
At the beginning it still worked

**Comment by NielsPilgaard** [comment]
Thanks for the report, I'll investigate the issue :)

**Comment by NielsPilgaard** [comment]
I can open them just fine with shift right click, with an empty hand - Could you explain how to reproduce it? :)

**Comment by RoNoN-85** [comment]
Good Morning.
Now i have found the bug / issue .

If you hold a shield in the offhand, you cannot open the ui
i think this is together with the right click because then the shield is used.
The description should apply to both hands.

> both hands must be empty

i hope you understand me. my english is not awesome :D 

Thanks for your work :)

**Comment by NielsPilgaard** [comment]
Ah I see.

My pleasure, thanks for the report :D
