### ISSUE TITLE
Server (pack version 0.4.0) won't load BoP biomes

### ISSUE THREAD

**Issue by Shindur** [NillerMedDild/Enigmatica5#143]
**Modpack version**
0.4.0 and 31.1.30 version of forge on both client and server.
**Issue**
Can't generate BoP biomes when creating a new world on a server. I see BoP trees and various blocks from the mod in vanilla biomes, but no BoP biomes.

Have a rented server where I put the contents of the server pack for 0.4.0 and loaded it up. According to BoP's page "The mod works automatically on servers for 1.14 and above, as long as the use-world-type option stays set to true in /config/biomesoplenty/server.toml." Which I checked the config file and it's set to true. 
When the server world gets generated the level-type field gets put into the server.properties file and is set to default, even putting that to BIOMESOP (like how we had to do for 1.12 and below) and generating a new world, doesn't seem to fix the issue at hand. 

Me and some others talked in the #enigmatica5 channel in the discord, could be a forge related issue? Seems the following change was made for the server.properties file before the latest version of forge:
Build: 1.15.2-31.1.29 - Fri Mar 27 23:19:42 GMT 2020
	dags-:
		Defer writing the server.properties file until after mods have loaded to prevent config loss (#6545)

**Logs**
Unsure which log would be needed, let me know which you need and I can get it.

**Comment by NielsPilgaard** [comment]
I also think this could be a Forge issue, I'll investigate tomorrow evening, hopefully.
and thanks for the report :)

**Comment by NielsPilgaard** [comment]
The bug isn't on the Forge GitHub, that much I can see.

**Comment by NielsPilgaard** [comment]
Could you try setting the Forge version to 31.1.27 and see if it persists?

**Comment by Shindur** [comment]
Yea, lemme try that

**Comment by Shindur** [comment]
This worked! :D

**Comment by NielsPilgaard** [comment]
Awesome!

**Comment by NielsPilgaard** [comment]
Do you have the time to report this breaking change to BoP? :) Not sure whether they need to adapt, or Forge needs to revert.

**Comment by Shindur** [comment]
I can do that for ya

**Comment by Shindur** [comment]
Seems setting level-type=biomesoplenty does the trick for forge 31.1.30! 
Refer to this: https://github.com/Glitchfiend/BiomesOPlenty/issues/1572

**Comment by NielsPilgaard** [comment]
Oh, that could mean we can use TerraForged worldgen on servers :O

**Comment by NielsPilgaard** [comment]
I've set default server worldtype to `level-type=biomesoplenty`
Thanks for the help Shindur!

**Comment by Shindur** [comment]
No problem, glad I could be of help :)
