### ISSUE TITLE
Change TerraForged Worldgen Default

### ISSUE THREAD

**Issue by NielsPilgaard** [NillerMedDild/Enigmatica5#148]
More steep mountains, smaller biomes?

Comments / thoughts are very welcome

**Comment by Shindur** [comment]
Smaller biomes for sure, seems default terraforged generation has LARGE biomes from my experience. Could make it hard to find say a swamp or jungle.

**Comment by Shindur** [comment]
Maybe smaller oceans as well. Unless I'm just unlucky with seeds lol

**Comment by Shindur** [comment]
Ok, the TerraTest world type definitely needs smaller biomes... I just tried that, nothing but Plains biome.. evene going into the ocean.

**Comment by NielsPilgaard** [comment]
TerraTest is a dev world afaik :P not meant for survival

**Comment by Shindur** [comment]
Fair enough. And I was browsing TerraForged's github, any biomes that TerraForged makes is labeled as a Plains biome.. so disregard what I said about that.

If TerraTest was a dev world, then so far I think the general spread of biomes are doing well. And the smaller oceans thing is with the TerraTest as well, so disregard that.

**Comment by TheUntamed** [comment]
My fear is that smaller biomes look less beautiful. If that turns out true it would be better to give some travel stuff early on. Like boots with speed or something like that.

**Comment by Shindur** [comment]
If we can also make granite/andesite/diorite spawn less in the terraforged world gen.. It seems the world is filled with nothing but that.

Another thing, as mentioned in the discord - better bedrock generator isn't working in terraforged world gen. Dunno how that'll get fixed but yea :P

**Comment by NielsPilgaard** [comment]
Are you not on version 0.4.0 @Shindur? :o

Yeah I saw, thanks for the reminder, will let them know.

**Comment by NielsPilgaard** [comment]
https://github.com/TerraForged/TerraForged/issues/112

**Comment by Shindur** [comment]
I am on version 0.4.0 - generated a new world without changing anything in the TerraForged world type in single player.

**Comment by NielsPilgaard** [comment]
Huh that's odd, I changed the amount of Diorite / Andesite Granite to almost 0 in 0.4.0
The option `strataDecorator=false` removes the massive amount of those stones, so that should be set to false if you don't want them.

**Comment by Shindur** [comment]
It's set to false for me as well.. not sure. I just seem to find more of those rock types than stone for some reason. Could be a modded biome thing perhaps?

**Comment by NielsPilgaard** [comment]
Hmm, I'll look into that :)

**Comment by TheUntamed** [comment]
I already created a issue on terraforge github for flat bedrock.
My world on 0.4.0 is also filled with granite and diorite.
One question: How did you got the TerraForge generation json?

**Comment by NielsPilgaard** [comment]
I know, that's what I linked :D 
There's a button for it in the customization gui.

**Comment by TheUntamed** [comment]
Hey I found out why the strataDecorator=fals didnt work forShindur.
If you create a singleplayer world, you have to select "customize" --> "done" for the _terraforged-generator.json_ to work (you don't have to change anything, just press "done"). Otherwise the world will be generated with the absolut default settings not the modified ones.

**Comment by NielsPilgaard** [comment]
Nice catch! Linking the issue for future reference: https://github.com/TerraForged/TerraForged/issues/108

**Comment by NielsPilgaard** [comment]
I personally liked this one, with TerraForged 0.0.11
https://gist.github.com/NillerMedDild/842346e16d9af9c96c8b872f4b5ac403
In case you guys wanna try

<blockquote><img src="https://github.githubassets.com/images/modules/gists/gist-og-image.png" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> Gist</div><div><strong><a href="https://gist.github.com/NillerMedDild/842346e16d9af9c96c8b872f4b5ac403">terraforged-generator.json</a></strong></div><div>GitHub Gist: instantly share code, notes, and snippets.</div></blockquote>

**Comment by TheUntamed** [comment]
Smaller Oceans and smaller continents are a good idea. The values you choosed seem a bit too small maybe.
I also tried to reduce the biome size. From the default 200 to 150. But I think at 150 they are too small. Right now I'm at 180 and it's not that much of a difference to 200.

You also reduced mountain scale. That means mountains are not that steep? Or as steep as before and just not that high?

You also changed the horizontal Scale for mountains? Whats the effect of that value?

**Comment by NielsPilgaard** [comment]
I tried to make mountains steeper and less gradual, not sure if I succeeded :P I imagine horizontal scale of mountains is their height.

I think biome size 200 is fine to be honest, at least when flying

**Comment by TheUntamed** [comment]
There are a lot of hills that are not very steep, that's true, but there are also some very steep mountains. Especially in the cold biomes.

Btw. I just watched the mc world generation of the future. Very interesting: https://www.youtube.com/watch?v=8_bW3ab8YAk

<blockquote><img src="https://i.ytimg.com/vi/8_bW3ab8YAk/maxresdefault.jpg" width="48" align="right"><div><img src="/yts/img/favicon_144-vfliLAfaB.png" height="14"> YouTube</div><div><strong><a href="https://www.youtube.com/watch?v=8_bW3ab8YAk">The Earth in Minecraft, 1:1 scale ...for the first time.</a></strong></div><div>Join me in the BUILD THE EARTH discord to formulate a strategy to build the entire earth in minecraft. https://discord.gg/69ashjz https://www.reddit.com/r/Bu...</div></blockquote>

**Comment by NielsPilgaard** [comment]
Myeah I've tried it out, very very cool. But not fit for survival imo :(

**Comment by NielsPilgaard** [comment]
I'm okay with the generation for now, feel free to suggest other configs in the future :)
