### ISSUE TITLE
Unable to mine activated redstone with mining gadget

### ISSUE THREAD

**Issue by Qwekkeboom** [NillerMedDild/Enigmatica5#155]
**Modpack version**
0.4.0

**Issue**
When mining with the mining gadget you are unable to mine activated redstone.
This only applies when standing close enough to activate the redstone. If you have enough range the mining gadget will mine it but when you are standing to close you will activate the redstone instead of mining it.
Also submitted this issue directly to the mining gadget mod github.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NielsPilgaard** [comment]
Appreciate the repost, thanks :)
https://github.com/Direwolf20-MC/MiningGadgets/issues/79

**Comment by MichaelHillcox** [comment]
Looks like mining gadgets in the pack is outdated. We're on [1.3.5](https://github.com/Direwolf20-MC/MiningGadgets/blob/master/CHANGELOG.md#1152-135---2020-03-29) now :D
