### ISSUE TITLE
multiple death handling mods

### ISSUE THREAD

**Issue by theboo** [NillerMedDild/Enigmatica5#170]
**Modpack version**
0.4.1

**Issue**
Currently we have both Quark and Corpse handling "graves" and you never know which one you are going to get. If we decide to go with Quark's "totem of holding"(under oddities in quark config) and not the Corpse mod, we should probably disable dark souls mode as that makes you lose all your stuff if u die again before retrieving your grave.

**Comment by NielsPilgaard** [comment]
Err woops, I didn't know Oddities had graves o_O

**Comment by theboo** [comment]
Yeah, I was gonna do a PR to disable the quark one but was unsure of which you would want to go with

**Comment by NielsPilgaard** [comment]
I would like to disable the Quark one - if you do make a PR please aim at the developer branch :D

**Comment by theboo** [comment]
done

**Comment by NielsPilgaard** [comment]
Perfect, thank you :D
