### ISSUE TITLE
Sugar cane keeps growing

### ISSUE THREAD

**Issue by arjache** [NillerMedDild/Enigmatica5#173]
**Modpack version**
0.4.0

**Issue**
Sugar cane keeps growing without limit. This seems to apply to both naturally generated sugar cane and player planted sugar cane.

![2020-04-11_00 51 28](https://user-images.githubusercontent.com/63493138/79039856-05752f00-7b99-11ea-8b84-ccebe1350285.png)

**Comment by NielsPilgaard** [comment]
That is intentional, thanks for the report anyway :)
