### ISSUE TITLE
Native cave world support

### ISSUE THREAD

**Issue by SoniEx2** [NillerMedDild/Enigmatica5#184]
**Modpack version**
Input modpack version here
0.4.0? I'm not sure which version multimc's new thing pulls but I'm gonna guess I'm on 0.4.0.

**Issue**
Input short description of the issue here
as of minecraft 1.13, minecraft has this new "buffet" world type. you can do all sorts of weird things with it like generate cave worlds. you can also set it to generate all overworld biomes in such cave worlds, by editing the level.dat and changing `"generatorOptions"` -> `"biome_source"` -> `"type"` to `"minecraft:vanilla_layered"`. it is significantly harder than a "surface" overworld, and much more satisfying. could you support this kind of world generation officially in the modpack? thanks.

( https://youtu.be/3m7-eVeXQkk?t=215 )

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NielsPilgaard** [comment]
I'm not sure what you're actually asking for? Sounds like you can already do this.

**Comment by SoniEx2** [comment]
I'm asking if this is an acceptable way of playing the pack, or if it's more akin to installing additional mods.

**Comment by NielsPilgaard** [comment]
It's more like installing additional mods, but I'll try to help if you run into issues :)

**Comment by SoniEx2** [comment]
but it's vanilla

**Comment by NielsPilgaard** [comment]
So is creative mode, that doesn't mean it's one of the intended ways to play the pack. But again, if you run into issues I'll try to help.
