### ISSUE TITLE
botany pots don't survive restarts?

### ISSUE THREAD

**Issue by SoniEx2** [NillerMedDild/Enigmatica5#185]
**Modpack version**
Input modpack version here

0.4.0

**Issue**
Input short description of the issue here

after quitting the game and reloading, my botany pots deleted their crops with errors in the logs about dirt not being a valid soil.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

https://paste.ee/p/zHm09 (from multimc)

**Comment by NielsPilgaard** [comment]
This issue should be fixed in version 0.4.1+ :)
https://github.com/Darkhax-Minecraft/BotanyPots/issues/11
