### ISSUE TITLE
quark "tetris" style enchanting was enabled

### ISSUE THREAD

**Issue by theboo** [NillerMedDild/Enigmatica5#191]
**Modpack version**
0.4.2
**Issue**
somehow quark enchanting was enabled which doesnt work so well with so many enchants in the pack, should probably disable it. (ill look through the config and see if i can do a PR)

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NielsPilgaard** [comment]
And thanks again :D fixed by #194
