### ISSUE TITLE
DisenchantingForge

### ISSUE THREAD

**Issue by theboo** [NillerMedDild/Enigmatica5#192]
https://www.curseforge.com/minecraft/mc-mods/disenchantingforge

currently there is not a good way to disenchant items in this pack, this might be a good option?

**Comment by NielsPilgaard** [comment]
Vanilla has disenchanting, check out the grinding stone/wheel :)

**Comment by theboo** [comment]
aaah... this is more of an enchantment stripping mod than a disenchanting mod(allows you to strip enchants on to books using experience) xD i should have explained that better

**Comment by bessiq** [comment]
Apotheosis can do this with Tomes of Scrapping, but getting each enchant from the item is not guaranteed (based on your available experience), and the item is consumed in the process.

**Comment by theboo** [comment]
yeah i know about the scrapping tomes, they never seem to pull the one enchant i want off an item lol, also the forge would allow us to separate enchantments as well instead of trying to do that weird anvil drop crap lol
