### ISSUE TITLE
omega craft mod

### ISSUE THREAD

**Issue by theboo** [NillerMedDild/Enigmatica5#193]
https://www.curseforge.com/minecraft/mc-mods/omega-craft-mod

adds things like short range wireless energy, item and fluid transfer as well as some nice machines and concepts... seems pretty well put together, worth looking at for sure... added it to a single player e5 0.4.1 world and everything seems to work as advertised...

only sad thing is instead of using CT, it has its own scripts, but does allow for adding and removing recipes pretty easily

idk, worth a look at, wont hurt my feelings if it doesnt get added xD

**Comment by Darkere** [comment]
See #128
