### ISSUE TITLE
Server Crash on 0.4.1

### ISSUE THREAD

**Issue by TheKLC** [NillerMedDild/Enigmatica5#198]
**Modpack version**
0.4.1

**Issue**
Server crash - reporting to help with possible bugs

**Logs**
https://pastebin.com/xJXFNS09

**Comment by TheKLC** [comment]
Reproduced crash when hitting obsidian with an obsidian hammer. Server crashed on the first hit.

**Comment by NielsPilgaard** [comment]
Please update to the latest modpack version.

**Comment by TheKLC** [comment]
👍 Noticed there was a newer release after I posted. Will do.
