### ISSUE TITLE
Duplicating using death history menu.

### ISSUE THREAD

**Issue by Hell0there** [NillerMedDild/Enigmatica5#205]
You can **infinitely duplicate** items using the corpse mod's, death history menu that is opened by pressing "u"; I suggest making it so that you can only get your items from your last death once because even if you die again you can just get the items back.

**Comment by NielsPilgaard** [comment]
Thank you for the report, I will investigate the issue.

**Comment by theboo** [comment]
it's whatever mod lets you extract/insert all into an inventory from the gui... (the up and down arrow on the right middle when u are in a chest for example) you cannot pull stuff out by shift clicking or regular dragging, but you can pull it all out using the buttons from that mod... if that makes sense?

**Comment by NielsPilgaard** [comment]
Totally fixed, removing the mod :P
