### ISSUE TITLE
Unable to Create new server from Enigmatica5Server-0.4.4 Server Files

### ISSUE THREAD

**Issue by matt3948** [NillerMedDild/Enigmatica5#206]
**Modpack version**
Enigmatica5Server-0.4.4

**Issue**
Server crash prior to world creation

**Logs**
https://pastebin.com/A4jQ0fTX

**Comment by Darkere** [comment]
Remove StepUp from the mods folder. Download will be fixed soon.

**Comment by matt3948** [comment]
> 
> 
> Remove StepUp from the mods folder. Download will be fixed soon.

Thank you

**Comment by NielsPilgaard** [comment]
Download won't be fixed, but I will make a 0.4.5 this evening :)
