### ISSUE TITLE
64k disk drive duplicating

### ISSUE THREAD

**Issue by Hell0there** [NillerMedDild/Enigmatica5#207]
Refined storage 64k disks are all the same (every disk the same items in them in or out even if I add to the storage system when there out) so if I put them in the disk drive it duplicates for every drive (but it still has the original amount, as in I can only take out the amount I put in ) I could suspect the same thing is happening with other storage disks though I have not tried. ( This seems to happen exclusively on servers because I tried to replicate this in a single player world and it did not work)

**Comment by Darkere** [comment]
This only happens when you dupe disks or copy them with creative mode. New disks always get a new ID when they are created. 
You can see the ID if you enabled advanced tooltips with F3 + h.

**Comment by Hell0there** [comment]
Then how did this happen in my survival server

**Comment by Hell0there** [comment]
Do you think I could solve this problem by running the disks through a machine??

**Comment by Darkere** [comment]
Well where did you get the disks from?

You can throw away all but one of the identical disks. They all just link to the same storage.

**Comment by Hell0there** [comment]
ok
