### ISSUE TITLE
DimStorage

### ISSUE THREAD

**Issue by theboo** [NillerMedDild/Enigmatica5#210]
https://www.curseforge.com/minecraft/mc-mods/dimstorage

basically an ender storage clone, but slightly more techy and slightly less good looking... seems to work pretty well in testing with e5 0.4.6 in creative. Didn't see an issue for it here or on e4 so figured i would throw it in the hat.

**Comment by NielsPilgaard** [comment]
I recently checked it out after the developer messaged me about it, but due to how he asked I rejected it. I have a bad feeling about the mod :)
