### ISSUE TITLE
Uraninite Smelting Recipe Missing

### ISSUE THREAD

**Issue by theboo** [NillerMedDild/Enigmatica5#211]
**Modpack version**
0.4.6

**Issue**
it seems we no longer have a recipe to smelt the various forms(poor, regular and dense) of raw uraninite from the powah mod

**Comment by creepystalker2** [comment]
Dang I made an account just to report this and you took it from me.

**Comment by NielsPilgaard** [comment]
Thank you for the report, I will investigate the issue.
