### ISSUE TITLE
quickstacks crash with Refined Storage

### ISSUE THREAD

**Issue by theboo** [NillerMedDild/Enigmatica5#216]
**Modpack version**
0.4.7

**Issue**
Crash when pressing a "priority" button in a refined storage GUI. Disabling the quickstacks mod removes the issue

**Logs**
https://pastebin.com/awdx14AH

**Comment by Darkere** [comment]
https://github.com/Tfarcenim/DropOff/issues/12

Also reported to moddev via discord.
