### ISSUE TITLE
Tetra cause issue with servers.

### ISSUE THREAD

**Issue by SilverGhostie** [NillerMedDild/Enigmatica5#217]
My server group is using the latest releace of Enigmatica 5.  I beleave its 0.4.7.  However the issue has followed since atleast 4 updates ago, the issue is that if you put a emerald on your pick you are able to break bedrock, as well as dungons walls in their dim, which as far as we know should not be able to do.  some time after some one does this, it starts breaking the server.  is there a fix for this?

**Comment by NielsPilgaard** [comment]
Well that doesn't sound good at all, I'll investigate.
When you say starts breaking the server, what do you mean?

**Comment by NielsPilgaard** [comment]
Confirmed the issue, alerted the mod author through discord.

**Comment by SilverGhostie** [comment]
bogged down with lag, and or just crashing the server.  the biggest thing
we noticed on the last blow up.  our server has a auto restart every four
hours.  after a restart, it shows that its up and running, but no one can
log in.  our tech guy said that the last time was due to a corupt intatie,
-my spelling is horrid i am sorry for that-.,

**Comment by NielsPilgaard** [comment]
No worries, I can understand you just fine :)
May I please have one of those crash reports?

**Comment by SilverGhostie** [comment]
let me see if there is any, ill have to get with the tech guy for that.  im
just the messenger here lmao.
