### ISSUE TITLE
Tetra Thermal Cell Charge Recipe

### ISSUE THREAD

**Issue by theboo** [NillerMedDild/Enigmatica5#218]
add recipe to charge tetra thermal cells in energizer from powah

**Comment by theboo** [comment]
i was planning on doing this but my script fails due to the empty cell not being in JEI... it is in the creative tab tho.. JEI is supposed to pull everything from the creative tabs so idk why it is missing.

Another option would be to make recipes for the extractor pipe and transfer unit and these are the tetra ways to recharge them. Unfortunately the pipes need to be sitting on "seeping bedrock" to provide power to the core extractor which gives power to the transfer unit which charges the thermal cell

**Comment by NielsPilgaard** [comment]
I'll have a look too soon :)

**Comment by NielsPilgaard** [comment]
Did you use `<item:tetra:magmatic_cell>.withTag({Damage: 128})` as the empty cell?

**Comment by theboo** [comment]
yes, but i got an error from CT saying that isnt in jei

**Comment by NielsPilgaard** [comment]
![billede](https://user-images.githubusercontent.com/21295394/80143676-7a8b3000-85ad-11ea-8e05-180f4a8a7f7a.png)
