### ISSUE TITLE
mystical flowers

### ISSUE THREAD

**Issue by Hell0there** [NillerMedDild/Enigmatica5#221]
When me and my brother mine mystical tall flowers from botanica they do not give the item (mystical tall flower or just mystical flower)

**Comment by Hell0there** [comment]
Sorry to bug you if this is intentional

**Comment by Discomanco** [comment]
Did you harvest them with shears?

**Comment by theboo** [comment]
in testing in 0.4.7, only vanilla shears can harvest. Cyclic obsidian and flint shears do not harvest. And ironically, botania manasteel and elementium shears do not harvest either.

**Comment by theboo** [comment]
reported the botania shears issues on botania github. They dont work on leaves either. 

Cyclic shears seem to work with everything but botania tall flowers

**Comment by theboo** [comment]
seems the botania shears at least will be fixed in next release
https://github.com/Vazkii/Botania/issues/3262#issue-605020569

**Comment by NielsPilgaard** [comment]
Forge needs to implement this fix, so it might be a while.
