### ISSUE TITLE
Drag/Pan/Scroll slow in fullscreen Journeymap

### ISSUE THREAD

**Issue by Dracos99** [NillerMedDild/Enigmatica5#222]
**Modpack version**
0.4.7

**Issue**
Drag/Pan/Scroll slow in fullscreen Journeymap.
When clicking and dragging the full map around, it is very slow.
It looks like a conflict with extremeSoundMuffler-1.2.1_forge-1.15.2.jar when i run without this mod, the map performs as expected. Tested even with Journeymap and extremeSoundMuffler only and issue present.

**Comment by NielsPilgaard** [comment]
Thank you for the report, I will investigate the issue.

**Comment by theboo** [comment]
can confirm, tested this on my test instance removing and re-adding extreme sound mufflers. I have no idea how these two mods are interacting this way but they are.

**Comment by NielsPilgaard** [comment]
Would you mind relaying the issue to the Journeymap and Extreme Sound Muffler trackers @theboo ? :x

**Comment by theboo** [comment]
Yup, I'll do it on my lunch break

**Comment by theboo** [comment]
https://github.com/TeamJM/journeymap/issues/211#issue-606804338

https://github.com/LeoBeliik/ExtremeSoundMuffler/issues/8#issue-606803332

**Comment by theboo** [comment]
Should be fixed in next extreme sound muffler update
