### ISSUE TITLE
RefinedStorage crash

### ISSUE THREAD

**Issue by imol-ai** [NillerMedDild/Enigmatica5#224]
**Modpack version**
0.4.7

**Issue**
RefinedStorage crashing the game, when opening any menus within its interfaces (ex: autocrafting menu, fluid interface output amount configurator). Started happening when i updated from 0.4.4 to 0.4.7.

**Logs**
https://pastebin.com/57dmShcb

**Comment by Darkere** [comment]
duplicate of #216

**Comment by imol-ai** [comment]
Ooh sorry searched for refinedstorage, and didnt see it.
