### ISSUE TITLE
Vanilla Excavators

### ISSUE THREAD

**Issue by NielsPilgaard** [NillerMedDild/Enigmatica5#225]
https://www.curseforge.com/minecraft/mc-mods/vanilla-excavators/files/2939449

**Comment by Darkere** [comment]
fabric

**Comment by Darkere** [comment]
But someone ported to forge :) 
https://www.curseforge.com/minecraft/mc-mods/vanilla-excavators-forge

<blockquote><div><strong><a href="https://www.curseforge.com/minecraft/mc-mods/vanilla-excavators-forge">Attention Required! | Cloudflare</a></strong></div></blockquote>

**Comment by NielsPilgaard** [comment]
Heh, it's already in the pack. What is sleep

**Comment by NielsPilgaard** [comment]
But thanks Darkere for being vigilant as always :D
