### ISSUE TITLE
Bug between RefinedStorage and Quickstack

### ISSUE THREAD

**Issue by Dracos99** [NillerMedDild/Enigmatica5#226]
**Modpack version**
0.4.7

**Issue**
If I want to change the priority (External Storage / Disk Drive), the client crashes
Removing Quickstack resolves the crash

Looks like Refined Storage has an open issue on this
https://github.com/raoulvdberge/refinedstorage/issues/2486

**Comment by Darkere** [comment]
Duplicate of #224

**Comment by Dracos99** [comment]
Sorry, search didn't find the closed issue.
