### ISSUE TITLE
The game crashed whilst ticking entity Error: java.lang.StackOverflowError: Ticking entity

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica5#242]
**Modpack version**
Using Forge-1.15.2-31.1.46

**Issue**
Random crash occurred while standing around afk.

**Logs**
Attached.
[crash-2020-04-26_22.15.40-server.txt](https://github.com/NillerMedDild/Enigmatica5/files/4536407/crash-2020-04-26_22.15.40-server.txt)

**Comment by NielsPilgaard** [comment]
Thanks for the report, I'll relay it to Minecolonies asap :)

**Comment by NielsPilgaard** [comment]
Could you supply your latest.log please? The MineColonies issue tracker requests one for bug reports. Preferably one from close to the crash, if at all possible.

**Comment by NielsPilgaard** [comment]
Nevermind, they fixed it already \o/

**Comment by Ridanisaurus** [comment]
Perfect. Will check it once 0.4.8 is out, and let you know. Sadly I'm unable to start my game anymore due to this error. Let's hope CurseForge finalizes this version soon, and publish it.

**Comment by NielsPilgaard** [comment]
Manually updating MineColonies and Structurize should also fix it :)

**Comment by Ridanisaurus** [comment]
I can confirm that the latest update (E5 0.4.8) seems to have fixed this issue.
