### ISSUE TITLE
Rftools manual

### ISSUE THREAD

**Issue by Valirius** [NillerMedDild/Enigmatica5#244]
**Modpack version**
0.4.8

**Issue**
Problem with tftools manual recipe
And tftools manual is empty (((

**Comment by NielsPilgaard** [comment]
What is the problem with the recipe?

**Comment by NielsPilgaard** [comment]
Ah @theboo just informed me - It seems it's still a work in progress, not a bug or anything.

**Comment by Valirius** [comment]
Of course this is not a bug, this is what needs to be completed. 

**Add to the waiting list and planning.**

It’s just that rftools are not available at all because of this. On the Internet, in addition to long video information, they do not have Wikipedia either. And in the game, the manuals were not added.

You have to spend time on other people's long videos ...

and the recipe is simply not visible in JEI. Available only from akashi tom

**Comment by NielsPilgaard** [comment]
I don't make all the mods in Enigmatica 5, this isn't a task for me.
There is tons of information about RFTools available online. https://ftb.gamepedia.com/RFTools

<blockquote><img src="https://gamepedia.cursecdn.com/ftb_gamepedia/2/2f/Modicon_RFTools.png" width="48" align="right"><div>Feed The Beast Wiki</div><div><strong><a href="https://ftb.gamepedia.com/RFTools">RFTools</a></strong></div></blockquote>
