### ISSUE TITLE
RFTools Builder with MineColony

### ISSUE THREAD

**Issue by Valirius** [NillerMedDild/Enigmatica5#245]
**Modpack version**
0.4.8

**Issue**
I've heard you can somehow whitelist the block and give it permissions with your colony, but I have no idea how, or if that is a thing.

As I understand it, this cannot be done by the local client?
Is it somehow necessary to do this in the colony settings on the server?

With RFTools Elevator (although it seems our server don’t have it) problem is the same.
https://github.com/McJtyMods/RFTools/issues/1796

**Comment by Darkere** [comment]
It appears that it is not possible to whitelist fake players inside a colony right now.  I would be careful when doing so, as you are giving permission for all builder to mine within your colony. 

@NillerMedDild With FTBChunks in the pack I'm not certain if minecolonies protection is still needed. Although I guess it does protect colonists from unfortunate creeper encounters.

**Comment by NielsPilgaard** [comment]
I think that's a good idea, I disabled MineColony protection, but kept it's explosion protection. This should fix your issue OP :)

**Comment by NielsPilgaard** [comment]
![billede](https://user-images.githubusercontent.com/21295394/80860802-78d70180-8c6a-11ea-998a-3dbaf0beca91.png) 
works now :P
