### ISSUE TITLE
 unable to smelt dust created by the Silent's Crusher in the Mekanism's Smelter

### ISSUE THREAD

**Issue by NielsPilgaard** [NillerMedDild/Enigmatica5#247]
Mentioned in the enigmatica5 channel on the Discord.

**Comment by theboo** [comment]
false alarm.. working fine now for the original reporter as well, must have been some sort of lag. https://gyazo.com/6a7cd1f85f40a18ea9777c9fd5659e93

<blockquote><img src="https://i.gyazo.com/thumb/1200/6a7cd1f85f40a18ea9777c9fd5659e93-png.jpg" width="48" align="right"><div><img src="https://assets.gyazo.com/favicon.ico" height="14"> Gyazo</div><div><strong><a href="https://gyazo.com/6a7cd1f85f40a18ea9777c9fd5659e93">Gyazo</a></strong></div><div>&nbsp;</div></blockquote>

**Comment by NielsPilgaard** [comment]
Cool!
