### ISSUE TITLE
Mod suggestion: MiningTweaks

### ISSUE THREAD

**Issue by TheUntamed** [NillerMedDild/Enigmatica5#248]
I just found this mod to change the harvestlevel of blocks:
https://www.curseforge.com/minecraft/mc-mods/miningtweaks
Twitch App didn't suggest it to me so I didn't noticed it for some time. I don't know if you already found another mod to do this.

**Comment by NielsPilgaard** [comment]
Cool, thanks. I don't think I'll go with custom harvest levels this time around though.
