### ISSUE TITLE
Add Silent Ore Chunks to Mekanism Crushers?

### ISSUE THREAD

**Issue by bigyihsuan** [NillerMedDild/Enigmatica5#253]
**Modpack version**
0.4.8

**Issue**
You can't do some Silent's Mechanisms Crusher recipes in Mekanism Crushers. For example, in Silent, you can do Ore --> Crusher --> Ore Chunk --> Crusher --> Dust. Maybe have Mek Crushers output JAPOCA chunks when inputting ore?

**Comment by NielsPilgaard** [comment]
Good idea, I may just do that - But Silent's Mechanisms won't stay in the pack much longer, so I'm not sure I want to.

**Comment by bigyihsuan** [comment]
It could be a possible tier 1 tech mod should E5E ever happen hehe

**Comment by NielsPilgaard** [comment]
I've decided not to do this, as the Mekanism ore processing style is the one we're keeping :)
