### ISSUE TITLE
XNet breaks when applying facade to a cable running parallel to another cable (Refined Storage, Mekanism ..etc.)

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica5#255]
**Modpack version**
Enigmatica 5 v0.4.8

**Issue**
Encountered the issue while trying to apply a facade to an XNet cable running parallel to a Mekanism cable. Applying the facade disables the XNet cable completely, and creates an air block/invisible block instead. I asked on Discord for someone else to confirm if this issue occurs on their side as well, and they confirmed that it also happens if it is running parallel to a Refined Storage cable.

**Logs**
N/A

**Screenshot**
![01](https://user-images.githubusercontent.com/64355028/80675946-fefe1700-8ab5-11ea-9441-937b9ace335e.png)

**Comment by NielsPilgaard** [comment]
Thanks for the report - It seems to be the same as this one: https://github.com/McJtyMods/XNet/issues/383

**Comment by DSAutomations** [comment]
I'm experiencing this issue on **all** xnet cables, regardless of adjacent blocks/parallel cables
