### ISSUE TITLE
Nature's Aura - Recipe for Token of Joy expects small flowers, MC lists this as 'emptytag' - Cosmetic issue only

### ISSUE THREAD

**Issue by Trostmm** [NillerMedDild/Enigmatica5#256]
**Modpack version**
0.4.8

**Issue**
Nature's Aura - Recipe for Token of Joy expects small flowers, MC lists this as 'emptytag'.

Note, ritual still works, cosmetic issue only.

No log
See attached screenshot(s)
![2020-04-30_11 08 32](https://user-images.githubusercontent.com/10382598/80727037-35965a80-8ad3-11ea-83be-24b925a46a58.png)

**Comment by NielsPilgaard** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NielsPilgaard** [comment]
It must've been fixed by a mod update, it's no longer an issue :)

**Comment by Trostmm** [comment]
Bonus, thanks!
