### ISSUE TITLE
Passable Foliage

### ISSUE THREAD

**Issue by NielsPilgaard** [NillerMedDild/Enigmatica5#260]
https://www.curseforge.com/minecraft/mc-mods/passable-foliage

**Comment by NielsPilgaard** [comment]
Removed from 0.4.9 server files
https://github.com/Snownee/PassableFoliage/issues/1

**Comment by hvdklauw** [comment]
Yeah, this mod really breaks minecolonies colonist pathing when using the dark oak version for the town hall, they keep dropping in the "moat" of leaves and can't get out

**Comment by NielsPilgaard** [comment]
Hmm, maybe I should look into only making leaves passable for players.

**Comment by NielsPilgaard** [comment]
https://github.com/Snownee/PassableFoliage/issues/3

**Comment by NielsPilgaard** [comment]
The developer of the mod added a config to allow it to only be enabled for players, so your villagers are safe :)
