### ISSUE TITLE
Putting any item from Industrial foregoing into the crafting grid crashes on servers

### ISSUE THREAD

**Issue by Darkere** [NillerMedDild/Enigmatica5#262]
**Modpack version**
0.4.8

**Issue**
Putting any item from Industrial foregoing into the crafting grid crashes on servers

**Logs**
https://gist.github.com/Darkere/6d92988b82b4276a93bebe6dc57da23a

https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues/740

Could temporarily remove Akashic tome.

**Comment by NielsPilgaard** [comment]
Do you know anything regarding the ETA of next IF update? :)

**Comment by Darkere** [comment]
![image](https://user-images.githubusercontent.com/4283717/80835136-6f11b780-8bf2-11ea-9e0f-e1c33214124d.png)

**Comment by NielsPilgaard** [comment]
You're the best :D
