### ISSUE TITLE
Dupe Glitch With Cyclic Pipes and Storage Drawers.

### ISSUE THREAD

**Issue by Shadowcrit** [NillerMedDild/Enigmatica5#264]
**Modpack version**
0.4.8

**Issue**
Any item can be duplicated with Storage Drawers and Cyclic Item Cables.

**Logs**
N/A

Steps to recreate:
1. Create a Storage Drawer, put an item into it, and Lock it the Storage Drawer Key.
2. Put a Minecraft Chest a block away.
3. Put Cyclic item pipe next to the chest, and on top of the chest, and connect the pipes all together.
4. Set the pipe to extract from the Storage Drawer. Items duplicate.

Attached a picture of the setup.

![image](https://user-images.githubusercontent.com/31373528/80852033-1df5c980-8bda-11ea-9723-d9d8019fbaff.png)

Update: Don't even need the cable on top, if the storage drawer is locked, and One item is in it, the pipe keeps pulling unlimited. So, One item pipe will do.

**Comment by theboo** [comment]
seems to be a cyclic issue, i tried this with every other item transfer we have and the pack and only the cyclic cable behaves this way. Drawer doesn't even have to be locked. Issues were already present on both mod's trackers

https://github.com/Lothrazar/Cyclic/issues/1405

https://github.com/jaquadro/StorageDrawers/issues/822

**Comment by Trostmm** [comment]
I tested this in 0.4.9 and it doesn't *seem* to work anymore. Anyone else want to check?

**Comment by NielsPilgaard** [comment]
Well the dupe is fixed, but now they void items. I'm just gonna disable them.
Edit: They don't void items, the item is stored in the pipe if it can't go to an inventory different from the origin. So leaving them on for now.
