### ISSUE TITLE
Smelting Clay into Terracotta

### ISSUE THREAD

**Issue by tloskpd** [NillerMedDild/Enigmatica5#267]
**Modpack version**
0.4.8

**Issue**
can't smelt clay into terracotta in mek's smelter

**Comment by NielsPilgaard** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NielsPilgaard** [comment]
Works just fine for me, could you send a screenshot of your setup please? Is it server or single player?

**Comment by tloskpd** [comment]
Unfortunately I can’t right now. I was in the process of changing Linux distro and it formatted my efi boot partition need to fix. But standard energized smelter. Couldn’t shift click or manually click clay block into it to smelt. Could have possibly been gdlauncher not updating all files correctly between versions

**Comment by NielsPilgaard** [comment]
Ah damn :/ Well if it happens again feel free to comment here and I'll reopen.
