### ISSUE TITLE
Storage Drawers: 16 stack items do not stack correctly within all drawers. 

### ISSUE THREAD

**Issue by bgoodfinger** [NillerMedDild/Enigmatica5#269]
Build: 0.4.8

Description: If the user stores items that stack in 16 in all drawers from the mod storage drawers the drawer does not store the full amount. 
Effected items that stack in 16 and were tested: Egg, Signs, Snow Balls and Ender Pearls. Buckets were not tested (Did not have 1536 iron ingots to test). 
1x, 2x and 4x oak drawers were used. Wood logs were used as a control and stored the appropriate amount.

Repro:

1. Create 1x, 2x and 4x drawers from the mod Storage Drawers.
2. Obtain over 512 of the items listed above.
3. Store in the 1x, 2x and 4x drawers.
4. Observe drawers not storing appropriate amount.  

Expected Result: User is able to store the appropriate amount of items in Storage Drawers drawers when storing items that stack in 16. 
Expected number per drawer. 1x - 2048, 2x - 1024 and 4x - 512

Actual result: All items tested stored the following amounts. 1x - 512, 2x - 256 and 4x - 128

**Comment by NielsPilgaard** [comment]
That's not a bug, the Storage Drawers contain stacks, if the stack is smaller than normal, the amount of storage is also lower.
