### ISSUE TITLE
Steel messed up

### ISSUE THREAD

**Issue by JFMillerUSA** [NillerMedDild/Enigmatica5#270]
v0.4.8

Silent's Mechanisms Steel makes Mekanism: tools armor which can't be repaired on anvil

**Comment by NielsPilgaard** [comment]
So..the bug report is really that you can't repair Mekanism Steel Armor? :P

**Comment by JFMillerUSA** [comment]
https://imgur.com/NVghyEY

https://imgur.com/LadrION

https://imgur.com/BGcMpNi

**Comment by NielsPilgaard** [comment]
I'll take that as a yes.

**Comment by NielsPilgaard** [comment]
I've made a request here: https://github.com/mekanism/Mekanism/issues/6127

**Comment by JFMillerUSA** [comment]
Is there a way to be able to have Storage drawers Conversion Upgrade to change the Ingots tags

**Comment by NielsPilgaard** [comment]
Nope, you'll have to wait for it to be fixed :)
