### ISSUE TITLE
Odd light render bug when using Botney Pots

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica5#272]
**Modpack version**
E5 0.4.8

**Issue**
Light renders in an odd way for the blocks near the Botney Pots. This was confirmed by another person on the server, making sure it is not client side.
The render is resolved only when the player is in close proximity to the pots.

Current Settings:
Graphics - Fancy
Smooth Lighting - Max
Brightness - Bright

+ Nightvision

**Logs**
N/A

**Screenshots**
![image](https://user-images.githubusercontent.com/64355028/80924139-9483fa00-8d87-11ea-9402-1e4d4b7933ad.png)
![image](https://user-images.githubusercontent.com/64355028/80924144-a1085280-8d87-11ea-9f36-420c79a3ca4a.png)
![image](https://user-images.githubusercontent.com/64355028/80924150-ac5b7e00-8d87-11ea-8771-f4dc8d5b23ae.png)

**Comment by NielsPilgaard** [comment]
What is lighting them on image 2?

**Comment by NielsPilgaard** [comment]
![billede](https://user-images.githubusercontent.com/21295394/80925044-027ef000-8d8d-11ea-9607-ca5ec5d28a10.png)
Seems to work fine for me.

**Comment by Ridanisaurus** [comment]
> What is lighting them on image 2?

I think it was a light placed by the mining tool. However, I did remove all the lights around, and I can confirm it still occurred after its removal. If you want, I can go on the server, and you can teleport over to see it.

**Comment by Ridanisaurus** [comment]
Just an update, I can confirm that the issue remains after updating to 0.4.9. 
![image](https://user-images.githubusercontent.com/64355028/80947869-5a4f4280-8df1-11ea-83c8-74a2d804341a.png)

**Comment by merlerm** [comment]
The problem when I was looking at it on the server seemed to be that the blocks directly underneath the pots were affected. In those screenshots, the pots were sitting exactly above the corner where the glitch happened and it went away the moment the pots were broken.

**Comment by merlerm** [comment]
![2020-05-04_13 29 39](https://user-images.githubusercontent.com/62080872/80961536-6d6f0c00-8e0b-11ea-9d29-b66056e0a554.png)
![2020-05-04_13 29 49](https://user-images.githubusercontent.com/62080872/80961540-6f38cf80-8e0b-11ea-8a3e-d3239898a418.png)
Update, I've also noticed this in my base with white concrete. Seems unrelated from botany pots, as in one instance I have no pots nowhere near. My guess would be Feral Flare Lanterns, as it seems to be the only obvious thing the two situations have in common

**Comment by Ridanisaurus** [comment]
I have removed my Feral Flares, and the issue is still there.

**Comment by merlerm** [comment]
Have you tried getting rid of the light sources they make with the pearl?
