### ISSUE TITLE
Minecolonies protection crashes when opening old colonies

### ISSUE THREAD

**Issue by merlerm** [NillerMedDild/Enigmatica5#273]
**Modpack version**
0.4.9

**Issue**
Client crash when opening Builder's hut block in old colony, seems to have to do with the removed protection

**Logs**
https://pastebin.com/KsmaK5DG

**Comment by NielsPilgaard** [comment]
Does it still happen?

**Comment by merlerm** [comment]
Was just updating, I tested once yesterday and closed it off as it was very late. Just tried to recreate it on the server and it is not happening anymore. Might've been a one-off

**Comment by NielsPilgaard** [comment]
Good, it should be :)

**Comment by merlerm** [comment]
https://pastebin.com/ytwrf1vc

another seemingly unrelated minecolonies crash i just got into. thought i'd leave it here

<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/ytwrf1vc">Minecolonies Crash 0.4.9 E5 2 - Pastebin.com</a></strong></div></blockquote>

**Comment by NielsPilgaard** [comment]
What were you doing when it happened?

**Comment by merlerm** [comment]
Trying to open up my builder's GUI, hasn't happened since

**Comment by merlerm** [comment]
Edit, it happened again i think? 
https://pastebin.com/xSqrT2c5

<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/xSqrT2c5">---- Minecraft Crash Report ----  // There are four lights!    Time: 5/9/20 12:2 - Pastebin.com</a></strong></div></blockquote>

**Comment by NielsPilgaard** [comment]
Yup that's the same issue :/ I'll ask around.
https://github.com/ldtteam/minecolonies/issues/4704

**Comment by NielsPilgaard** [comment]
I'm going to re-enable Colony protection, turning it off seems too unstable. Thanks for the feedback Merlo!
