### ISSUE TITLE
Vanilla Things glass door duplication bug

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica5#274]
**Modpack version**
E5 0.4.8

**Issue**
Vanilla Things glass door duplicate when broken. Tried with multiple tool (some enchanted with silk touch, some with fortune, and some with no enchants) and all produce this bug.

**Logs**
N/A

**Screenshots**
![image](https://user-images.githubusercontent.com/64355028/80963512-5df1c200-8e0f-11ea-8764-bfc6e1e0d352.png)
![image](https://user-images.githubusercontent.com/64355028/80963576-8083db00-8e0f-11ea-9839-00aa90da08ba.png)

**Comment by NielsPilgaard** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NielsPilgaard** [comment]
https://github.com/SaymN/VanillaThings/issues/23

**Comment by Ridanisaurus** [comment]
I think now that Vanilla Things has been removed, this bug can be closed/removed from the tracker.
