### ISSUE TITLE
Dissolution Chamber from Industrial Foregoing creates 2 items instead of 1

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica5#277]
**Modpack version**
E5 0.4.9

**Issue**
The Dissolution Chamber from IF produced double the items, using only 1 set of input items.
Example:
2X Redstone Dust, 2X Glass Pane, 4X Gold Nuggets = 2X Tier 6 Range Addon instead of 1. It does however require a second input of the required fluid.

**Logs**
N/A

**Comment by NielsPilgaard** [comment]
Huh, interesting, thanks for the report as always :)

**Comment by Ridanisaurus** [comment]
it looks like the same issue was encountered in other modpacks. https://github.com/AllTheMods/ATM-5/issues/46

**Comment by NielsPilgaard** [comment]
Aha! Also found it here: https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues/730
It seems to be fixed in-dev, so we're waiting for an update.
