### ISSUE TITLE
Error/Game Crash: Rendering screen - java.lang.ArithmeticException: / by zero

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica5#278]
**Modpack version**
E5 0.4.9

**Issue**
This error occurs when attempting to access the GUI/Right Clicking of the Biofuel Generator from Industrial Foregoing.

**Logs**
Attached.
[crash-2020-05-05_20.08.07-client.txt](https://github.com/NillerMedDild/Enigmatica5/files/4582838/crash-2020-05-05_20.08.07-client.txt)

**Comment by NielsPilgaard** [comment]
Thanks for letting me know, the issue was reported on the IF tracker here: https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues/748
