### ISSUE TITLE
FPS performance problem.

### ISSUE THREAD

**Issue by staviq** [NillerMedDild/Enigmatica5#280]
**Modpack version**
Enigmatica 5 0.4.9

**Issue**
So i tried E5 and i'm getting serious FPS performance issues.

TPS is fine, and forge reports it to be solid 20 at around 4ms/t

For comparision, i did 3 test setups, one in E5, one with AllTheMods5 modpack, and one with E5 but i removed all mods from "mods" folder. Every time i created a world with default settings (biomes o plenty) and the seed "test2", then without moving the mouse i positioned myself in the same place near the only cattail around, looking in the same direction iwas when i spawned, directly at the tree far south, then i wait at least a minute for the world and fps to stabilise.

In ATM5 i'm getting about 127 fps, with optifine and with shaders.
In E5 mods removed i'm getting around 133 fps, with optifine and with shaders.
In E5, all default settings i'm getting 90 ish NO optifine and NO shaders.

If i find a village and stick around there, the fps goes down to 60-ish, and if i'm walking around the village it can drop down to 30 fps.

I haven't even started playing the pack really. Not a single machine, not a single cable. Boat and wooden axe is as far as i got.

------

Now, i really wanted to give You the offending mod, but i just genuinely spent the last 11 hours trying to run E5 with only some mods, and i was a nightmare, and i encountered about 6 new, unrelated bugs in forge, and some mods. Even if i disable some mods, and re-enable dependencies that forge complains about, the game either crashes, crashes when creating world, crashes when loading world, enters bootloop, freezes, or crashes with completly unrelated problem that points to no specific mod, like net.minecraft.client.renderer.color.ItemColors crash, or net.minecraftforge.common.AdvancementLoadFix.loadVisibility crash, or Ticking Memory Connection crash.

So, the only thing that i pretty much managed to determine, is that none of the following mods are responsible, because the modpack is running fine and as expected with those mods:

`Neat`
`BiomesOPlenty`
`Botania`
`theoneprobe`
`PassableFoliage`
`jei`

I'm using java parameters from the modpack description and 12G ram for the game, RTX2070S, i59600KF

**Comment by NielsPilgaard** [comment]
Thanks a lot for putting this report together, it'll make troubleshooting the FPS a lot easier!

**Comment by Darkere** [comment]
Only mod that i've heard might cause fps problems is Journeymap. 

If you are this dedicated you might be able to run Spark on your client to specifically analyze the Problem.

**Comment by staviq** [comment]
I'm gonna try spark when i get home but i glanced at the mod description and i don't think it can profile rendering loop specifically.

If anybody knows about fps profiler that works with 1.15 i'd be glad to try it out and post the results.

**Comment by Darkere** [comment]
Spark analyses the entire client thread. That means it looks at every code that is being run. Run /sparkc sampler --timeout 50. Make sure to select a mapping in the top right to make the results readable. (or post here or in discord ;))

**Comment by staviq** [comment]
https://spark.lucko.me/#9slLbFOWV2

Aquaculture seems to stand out a bit in the render thread, but i tried without it and i saw no noticeable improvement.

Also, profile with aquaculture removed: https://spark.lucko.me/#hUGPhKXIoP

<blockquote><img src="https://sparkprofiler.github.io/assets/img/spark-160.png" width="48" align="right"><div>spark</div><div><strong><a href="https://sparkprofiler.github.io/">spark</a></strong></div><div>spark is a performance profiling plugin based on sk89q's WarmRoast profiler.</div></blockquote>
<blockquote><img src="https://sparkprofiler.github.io/assets/img/spark-160.png" width="48" align="right"><div>spark</div><div><strong><a href="https://sparkprofiler.github.io/">spark</a></strong></div><div>spark is a performance profiling plugin based on sk89q's WarmRoast profiler.</div></blockquote>

**Comment by Darkere** [comment]
The Biggest thing I'm seeing is journeymap at 2%.. Which is pretty much nothing. 

Can you make a comparison between an area where you get a lot of fps and one where you don't get as much?

**Comment by staviq** [comment]
Im trying again, loading some mods, this time groupped by first letter plus any dependencies, so far i got a stable set of about 35 mods ( by "stable set" i mean the fps is identical to no mods at all except biomesoplenty so the worldgen is the same ).

I'm currently stuck at this problem, bonsaitrees crashes because of some missing dependency that i don't know about:

`
java.lang.NullPointerException: Initializing game
	at net.minecraft.client.renderer.color.BlockColors.func_186722_a(BlockColors.java:97) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.davenonymous.bonsaitrees2.misc.PotColorizer.init(PotColorizer.java:33) ~[?:2.1.2.6] {re:classloading}
`


The plan is that i will start with a known stable set, and add mods group by grop and write down the results.

I just need your help with the crashes, just like above.

**Comment by Darkere** [comment]
The blockcolors crash happens when something else has caused the Event bus to shut down before it. Would need a latest.log to figure out what.

**Comment by staviq** [comment]
Crash report https://pastebin.com/cCb2UcnV
latestlog https://pastebin.com/7DZhqqxS 

<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/cCb2UcnV">---- Minecraft Crash Report ----  // This doesn't make any sense!    Time: 5/6/2 - Pastebin.com</a></strong></div></blockquote>
<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/7DZhqqxS">[19:26:56] [main/INFO]: ModLauncher running: args [--username, staviq, --version - Pastebin.com</a></strong></div></blockquote>

**Comment by Darkere** [comment]
`this is an expected crash because MixinBootstrap isn't (properly) installed`

Lots of mods need that one.

**Comment by staviq** [comment]
Oh yeah, when you said that i should look at latestlog instead of the crash report i found it immadiately :)

Anyway, i think i'm onto something now, because this set is stable: https://pastebin.com/TR9WLKA8
And this set is not: https://pastebin.com/sv9T46R3

With the  other set i'm getting fps almost as bad as with the whole modpack, but it's fluctuating a lot.

Definately a great difference in performance between those two sets.

<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/TR9WLKA8">        Directory: C:\Users\MajonezKielecki\Twitch\Minecraft\Instances\Enigmatic - Pastebin.com</a></strong></div></blockquote>
<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/sv9T46R3">        Directory: C:\Users\MajonezKielecki\Twitch\Minecraft\Instances\Enigmatic - Pastebin.com</a></strong></div></blockquote>

**Comment by NielsPilgaard** [comment]
I'm gonna try to find the culprit in the unsafe list :)

**Comment by Darkere** [comment]
Difference
![image](https://user-images.githubusercontent.com/4283717/81214070-947a3900-8fd7-11ea-8454-c2be2b465e3d.png)


I would immediately suspect Borderless to be the culprit in this case.

**Comment by staviq** [comment]
Spark profile with the "unstable" set https://spark.lucko.me/#ifo6ZsQaNv

Also for some clarification: with this "unstable" set, i'm getting fluctuating fps, between "good" and "bad" level, with some short where fps seems steady, but i can gest steady either in the "bad" or "good" state.

It looks sort of like one of mods steals a set amount of time from the frame thread, every frame, but does not do that continously. Meaning, adding or removing mods does not get the fps better or worse, but rather makes the "bad" fps happen more or less often.


Anyway, i'll try to do one by one now and report if i find somethin usefull.

<blockquote><img src="https://sparkprofiler.github.io/assets/img/spark-160.png" width="48" align="right"><div>spark</div><div><strong><a href="https://sparkprofiler.github.io/">spark</a></strong></div><div>spark is a performance profiling plugin based on sk89q's WarmRoast profiler.</div></blockquote>

**Comment by NielsPilgaard** [comment]
Disabling VSync nearly doubled by FPS, from 30 to 60, pretty decent start.

**Comment by staviq** [comment]
> I would immediately suspect Borderless to be the culprit in this case.

Oh, yeah, "Borderless" seems to make all the difference in the world for me.

Let me just run a couple more tests with the rest of the modpack to be sure, but this one is definitely at least one of the sources for the problem.

**Comment by NielsPilgaard** [comment]
I agree, removing Borderless does improve it quite a bit.

**Comment by NielsPilgaard** [comment]
Alright I'm going to remove Borderless, I get 60-90 FPS now which is pretty good on my PC. How are your tests going Staviq?

**Comment by staviq** [comment]
Ok, so i redownloaded the whole pack to have good reference, and did a couple of "test2" dances, with all defaults, and with borderless and/or vsync disabled.

Sweet Baby Jesus, my fps almost quadrupled.

**Comment by AndromeHyperion** [comment]
So i've tested this too, in single player removing borderless improves it quite a bit. going from 30 to 150+
But in multiplayer it improves not that much, went from 30 fps to 40 fps

after swapping my hotbar twice it goes up to 100 fps
