### ISSUE TITLE
Crafting Recipes missing

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica5#281]
**Modpack version**
0.4.9

**Issue**
I know this is probably a little out of scope here, but I thought I'd ask anyway. I went ahead and added PneumaticCraft to my Enigmatica 5 world figuring that your tweaks would, in general not effect it.

I have encountered a few issues that I've been able to solve (Silent's compressed iron interfering and adding compat recipes for Silent's oil) but I'm at a loss on this one and thought maybe you could offer some insight.

The Speed Upgrade simply has no recipe. It works fine in a test pack I threw together, so I figure it must be something in one of your CT scripts, but I haven't quite gotten used to the new syntax for that and I haven't seen anywhere obvious to look for an issue.

The item name is pneumaticcraft:speed_upgrade and it should normally use a bucket of lubricant, four sugar, and 4 lapis (or 4 of the new upgrade matrices) 

Where might I need to look to begin fixing this on my own?

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NielsPilgaard** [comment]
I'm gonna test PneumaticCraft in the pack soon, I'll let you know if I can figure it out :)
Edit: But I'm closing this issue and labeling it as invalid, as it's not a modpack issue yet :P
Edit2: Feel free to respond here.

**Comment by MuteTiefling** [comment]
Thanks for looking into it!
