### ISSUE TITLE
Range addon double output dissolution chamber

### ISSUE THREAD

**Issue by AndromeHyperion** [NillerMedDild/Enigmatica5#283]
**Modpack version**
0.4.9
**Issue**
If you create a range addon in the dissolution chamber and you put 2 or more buckets of latex in it, you get 2 of the same rande addon as output

It will create 2 range addons with only the ingredients of 1.
It's repeatable, it most likely is a bug with industrial foregoing.

**Comment by Darkere** [comment]
duplicate of #277
