### ISSUE TITLE
Enable Quark Chest Searching

### ISSUE THREAD

**Issue by NielsPilgaard** [NillerMedDild/Enigmatica5#286]
Sounds like I missed important details, as JEI doesn't have the overlay atm?

**Comment by Darkere** [comment]
JEI never had that search overlay. It's always been https://www.curseforge.com/minecraft/mc-mods/more-overlays or the NEI addon. 

<blockquote><div><strong><a href="https://www.curseforge.com/minecraft/mc-mods/more-overlays">Attention Required! | Cloudflare</a></strong></div></blockquote>

**Comment by NielsPilgaard** [comment]
Well that's embarrassing.
