### ISSUE TITLE
Wheat -> Wheat Seeds Recipe

### ISSUE THREAD

**Issue by NielsPilgaard** [NillerMedDild/Enigmatica5#288]
![billede](https://user-images.githubusercontent.com/21295394/81617380-9ed87080-93e5-11ea-90a9-e787738da13b.png)

**Comment by theboo** [comment]
uhhh, have i mentioned that crit's worlds are cursed? I'm not seeing the same issue in untouched 0.4.9

![2020-05-12_10 00 43](https://user-images.githubusercontent.com/3585761/81723367-927d0380-9437-11ea-97fb-07b500c29860.png)
![2020-05-12_09 49 58](https://user-images.githubusercontent.com/3585761/81723421-a7f22d80-9437-11ea-9e27-466f40b1161e.png)

**Comment by NielsPilgaard** [comment]
For the love of god :P his scripts were supposedly loaded when he saw the issue.

**Comment by NielsPilgaard** [comment]
At least something good came out of this :P
