### ISSUE TITLE
Journeymap Waypoint FPS Decrease

### ISSUE THREAD

**Issue by NowayIndustries** [NillerMedDild/Enigmatica5#291]
**Modpack version**
Version: 0.4.9
Minecraft Version: 1.15.2
(modded) forge-31.1.63

**Issue**
Upon switching hotbar with Quark's hotbar swapping feature (z hotkey) my FPS drops to ~14.
When restoring my original/actual hotbar my FPS returns to 60+
Sometimes I can get my FPS to go back to 60+ by swapping a couple of times to the different hotbar options.

**Logs**
Original/actual hotbar:
![image](https://user-images.githubusercontent.com/1672073/81728746-39d75600-948b-11ea-8955-4653701d36f4.png)
Replacing with any hotbar via Z key:
![image](https://user-images.githubusercontent.com/1672073/81728800-4a87cc00-948b-11ea-8b6a-a5622ddd996d.png)

**Comment by NielsPilgaard** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NielsPilgaard** [comment]
I'm not seeing any FPS drop, may I have a latest.log from you please? I suspect it may be caused by outdated java :)

**Comment by NowayIndustries** [comment]
[latest.log](https://github.com/NillerMedDild/Enigmatica5/files/4617813/latest.log)

A couple of other players on the server are seeing this FPS issue as well. Maybe its multiplayer only?

**Comment by NowayIndustries** [comment]
The first occurence of the lag is around [19:49:35] after someone mentioning the Z key in chat, relating to seeing multiple hotbars.

**Comment by NielsPilgaard** [comment]
Ah could be, I'll try on a server too, thanks.

**Comment by NielsPilgaard** [comment]
Well your java is outdated, I highly recommend that you get that fixed, as it causes a host of issues:

This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add `-version:1.8+` to the Additional Arguments

<blockquote><div><strong><a href="https://www.java.com/en/download/manual.jsp">Java Downloads for All Operating Systems</a></strong></div><div>Java manual download page. Get the latest version of the Java Runtime Environment (JRE) for Windows, Mac, Solaris, and Linux.</div></blockquote>

**Comment by NowayIndustries** [comment]
I'm downloading the update (8u251) now and I'll report back after that.
The twitch minecraft settings are misleadingly showing the java version as 13.0.0.0 (64 Bit), so that's not helping either.

**Comment by NielsPilgaard** [comment]
Yeah Twitch is a bit useless when it comes to Java version :P

**Comment by NielsPilgaard** [comment]
No FPS decrease on servers either, for me :)

**Comment by NowayIndustries** [comment]
So that was quite the journey, apparantly the twitch launcher doesn't want to use the newer version and kept on using the old version.
After importing the pack into multimc I'm still getting this behaviour, even with the latest java.
Swapping hotbar or opening the interface with Z will drop me to ~14 fps from 100+

So this is very weird, attached is some more screenshots and the latest.log

Got any more ideas on how to debug this one? Luckily I wasn't used to using the hotbar swapping thing, but one of the other players on the server had been plagued by low fps for a couple of days now, he apparantly switched hotbars by accident.

[latest.log](https://github.com/NillerMedDild/Enigmatica5/files/4618121/latest.log)
![image](https://user-images.githubusercontent.com/1672073/81739113-11efee80-949b-11ea-8881-dd2892d9da4d.png)
![image](https://user-images.githubusercontent.com/1672073/81739145-1b795680-949b-11ea-8c46-f17c741980dd.png)
![image](https://user-images.githubusercontent.com/1672073/81739165-2207ce00-949b-11ea-91b9-3981f409060d.png)

**Comment by NowayIndustries** [comment]
Might be hitting the limit a single core of my CPU can do? This screenshot is after a little while with the Z menu open:
![image](https://user-images.githubusercontent.com/1672073/81739926-76f81400-949c-11ea-8fcb-3d9846b30058.png)

This is a little while of no Z menu:
![image](https://user-images.githubusercontent.com/1672073/81740019-94c57900-949c-11ea-8e97-32599cc16fbb.png)

Even lowering the FPS target to 60 (from 120) only changes the CPU core load when the menu is not open:
![image](https://user-images.githubusercontent.com/1672073/81740184-d5bd8d80-949c-11ea-9cff-a74f2438dd4e.png)

**Comment by NielsPilgaard** [comment]
Huh, I'm stomped, I wonder why I can't reproduce it. Would you mind reposting this issue on [Quark's issue tracker](https://github.com/Vazkii/Quark/issues/new)?

**Comment by NowayIndustries** [comment]
Well good news, I have a plottwist!
Whilst I was installing spark to run the profiler, another server player found the actual culprit!

It's Journey maps waypoints... apparantly Z is also bound to toggle the waypoint displays. And it looks like he is right. If I press Z fast enough I can get the hotbar swapping GUI open but have the waypoints disabled and that results in 100+fps.

So I guess this issue can be closed (and possibly replaced with another), but for completeness sake here are two spark profiling runs (as per #280: ) 
with the waypoints being rendered:
https://spark.lucko.me/#rjHCHgE2nN
And one with the waypoints not being rendered (by Z):
https://spark.lucko.me/#3SRUh8Y6T5

Anyway thanks for the fast responses and help. I'll close this issue now and go to sleep.

<blockquote><img src="https://sparkprofiler.github.io/assets/img/spark-160.png" width="48" align="right"><div>spark</div><div><strong><a href="https://sparkprofiler.github.io/">spark</a></strong></div><div>spark is a performance profiling plugin based on sk89q's WarmRoast profiler.</div></blockquote>
<blockquote><img src="https://sparkprofiler.github.io/assets/img/spark-160.png" width="48" align="right"><div>spark</div><div><strong><a href="https://sparkprofiler.github.io/">spark</a></strong></div><div>spark is a performance profiling plugin based on sk89q's WarmRoast profiler.</div></blockquote>

**Comment by NielsPilgaard** [comment]
That is very helpful, thank you. I will change this issue to suit it's new purpose :P

**Comment by Giovanni-NL** [comment]
I can confirm. I had the exact same issue. For the longest time my fps would be stuck at about 20 fps max. Then we stumbled upon the z key to swap hotbars which restored the 120 fps I had before. But as already has been discovered, hotbars is not the problem.  The toggle of showing journeymap waypoints is also mapped to the z key.  With waypoints off I can get my fps to 120, with waypoints on it drops to about 20 fps.  So the bug definitely seems to be related to journeymap, not the hotbar.

**Comment by NielsPilgaard** [comment]
Could you post your journeymap log please, either of you? it's in the journeymap folder.

**Comment by Giovanni-NL** [comment]
[journeymap.log](https://github.com/NillerMedDild/Enigmatica5/files/4627017/journeymap.log)
The interesting bits are at the end.  I logged in at 10:36, waypoints were off. At 10:39 I turned the waypoints on.  My fps dropped to 20, and a NullPointerException appears in the log. Could be the culprit.  Good luck hunting down this bug. :)

**Comment by NielsPilgaard** [comment]
Perfect, thanks!

**Comment by NowayIndustries** [comment]
Here's my log (on 0.4.10 version of the pack, since thats what the server is running atm):

I'm not getting any errors looks like, but the behaviour is still there. So I figured my log would be of added value ;)
[journeymap.log](https://github.com/NillerMedDild/Enigmatica5/files/4630487/journeymap.log)
At 19:33:29 i'm logged in and a little while after that I start toggling the waypoints.
[latest.log](https://github.com/NillerMedDild/Enigmatica5/files/4630493/latest.log)

**Comment by NielsPilgaard** [comment]
I've decided to replace Jourmeymap with Xaero's minimap and worldmap, to remedy this issue.

**Comment by Giovanni-NL** [comment]
Hmm, ok. Time to backup those waypoints in [folder to Enigmatica 5]\journeymap\data\mp\Enigmatica~5\waypoints I guess.

**Comment by NielsPilgaard** [comment]
Myeah :/

**Comment by mysticdrew** [comment]
Those for sharing your profiling, it allowed me to pinpoint the issue. I may have a fix, i am testing it now. If any of you wish to verify and test one of my latest JM test builds please ping me in our discord.
