### ISSUE TITLE
Minecolonies Rendering Crash

### ISSUE THREAD

**Issue by merlerm** [NillerMedDild/Enigmatica5#295]
**Modpack version**
0.4.10

**Issue**
Seems like a one-off, but since i'm already off my PC and might not be playing much E5 i'll pin it here so i'll remember to test it again, crash seemingly happened out of nowhere.

If Minecolonies owed me a cent for every time it crashed me, i'd be a millionaire 

**Logs**
https://pastebin.com/WJmhMeUU

**Comment by NielsPilgaard** [comment]
Dammit, same type of issue.

**Comment by merlerm** [comment]
https://pastebin.com/1dY9WSmN

Here you are good sir, my daily minecolonies crash report. This one looks different though, doesn't seem to have to do with forge

<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/1dY9WSmN">Minecolonies Crash 0.4.11 E5 - Pastebin.com</a></strong></div></blockquote>

**Comment by NielsPilgaard** [comment]
Same type of issue, NoClassDefFoundError ><

**Comment by NielsPilgaard** [comment]
I will make another report though, maybe they'll have a look at this one.
Edit: Kinda changed my mind, I don't think they'll get that error fixed either, looks very very similar to the other one.
