### ISSUE TITLE
move FTBQ to its own branch until quests are made or fake player issue is resolved

### ISSUE THREAD

**Issue by theboo** [NillerMedDild/Enigmatica5#296]
Had a thought to remove FTBQ or have a branch of the pack dedicated to ftbq, at least until this issue with the clickers is resolved... apparently people cannot learn to not point them at each other lol

**Comment by NielsPilgaard** [comment]
They need to be adjacent or 1 block from each other for the crash to happen right?

**Comment by theboo** [comment]
they just need to be within range which is like 8 blocks i believe?

**Comment by theboo** [comment]
after further testing, anytime a clicker is set to right click pointed at another clicker 6 blocks away or less it crashes the next time the chunk is loaded

**Comment by NielsPilgaard** [comment]
Yikes. I'm going to remove Click Machine until it's fixed I think.

**Comment by NielsPilgaard** [comment]
Moved to #300
