### ISSUE TITLE
cannot pick simple farming berries with right click

### ISSUE THREAD

**Issue by theboo** [NillerMedDild/Enigmatica5#297]
**Modpack version**
0.4.10
**Issue**
Multiple reports in discord of people not able to right click to harvest simple farming berries.

right click harvesting seems to be turned off in simple farming config. It has a config to turn on right click harvesting, then gives you even more options on what things you want right click harvestable. Might look in to enabling some of that.

**Comment by NielsPilgaard** [comment]
Dammit :P thanks for letting me know, will re-enable some of it.
