### ISSUE TITLE
Add & Configure PackMenu 

### ISSUE THREAD

**Issue by NielsPilgaard** [NillerMedDild/Enigmatica5#3]
https://www.curseforge.com/minecraft/mc-mods/packmenu

**Comment by Dimentive** [comment]
You’re already working on Enigmatica 5 while still maintaining Enigmatica 2, Enigmatica 2: Light, Enigmatica 2: Expert, Enigmatica 4, and whatever else I’m forgetting? Jesus. You are a saint. 🙌

**Comment by Dimentive** [comment]
You’re _already_ working on Enigmatica 5 while still maintaining Enigmatica 2, Enigmatica 2: Light, Enigmatica 2: Expert, Enigmatica 4, and whatever else I’m forgetting? Jesus. You are a saint. 🙌

**Comment by NielsPilgaard** [comment]
Thanks :D
