### ISSUE TITLE
Pneumaticraft crash on startup

### ISSUE THREAD

**Issue by merlerm** [NillerMedDild/Enigmatica5#305]
**Modpack version**
0.4.11

**Issue**
Game crashed on startup, didn't finish loading. I thought it was due to a bad install but after launching the game again it loaded without crashing, though slower than usual

**Logs**
https://pastebin.com/veAmxTiF

**Comment by merlerm** [comment]
Edit: the install was still bad probably, trying to figure out exactly what happened. Updating from GD left ftbquests in and had two different versions of ftbchunks, but the game somehow still launched. Might have to do with that, trying to repair the install now

**Comment by NielsPilgaard** [comment]
Did a fresh install help? :)

**Comment by merlerm** [comment]
It did and it didn't. Fresh install on GD put the same extra mods, i could only get rid of them by hand. I couldn't replicate the crash with the "corrupted" or the correct instance anyways

**Comment by NielsPilgaard** [comment]
Alright, nice :)
