### ISSUE TITLE
Pneumatic Armor HUD takes up the full width of the screen

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica5#306]
**Modpack version**
0.4.11

**Issue**
The HUD for PneumaticCraft armor is huge. It's normally much smaller than this, and indeed in a standalone test pack with just PNC and a few other mods, it's fine. 

I've confirmed this in a fresh instance of E5 as well as my normal E5 instance has been modified a bit. 

![2020-05-13_20 04 05](https://user-images.githubusercontent.com/9543430/81878102-03fea400-9555-11ea-8491-505e64dc28ae.png)

For comparison, this is how it shows normally:
![2020-05-13_20 09 17](https://user-images.githubusercontent.com/9543430/81878311-aae34000-9555-11ea-8690-731ecf6dd607.png)

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NielsPilgaard** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NielsPilgaard** [comment]
I'm a bit stomped on this one, the configs are completely default.

**Comment by NielsPilgaard** [comment]
I removed ShetiPhianCore and MultiBeds, and the problem went poof.

**Comment by desht** [comment]
This should be fixed (at least in PNC) as of the 1.3.0 beta release (which despite beta status should be pretty stable).

Basic problem is clashing keys in the lang JSON files, in this case `_comment` keys which were almost certainly added when translations were auto-converted from the old 1.12.2 format.  I've fixed this for PNC 1.3.0, so this problem should go away.  Although the author of ShetiphianCore should do the same for his mods...

**Comment by NielsPilgaard** [comment]
Thanks! He also fixed it on his end :)
