### ISSUE TITLE
PneumaticCraft Speed upgrades have no recipe

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica5#307]
**Modpack version**
0.4.11

**Issue**
Re-opening this as PNC has been added to the pack officially. Something in the scripts is removing the recipe for Speed upgrades from PNC. The crafting recipe is fine in non E5 testing worlds. 

**Logs**
https://gist.github.com/MuteTiefling/ccd3e043e09d2925b5fd71a9a6208446

**Comment by NielsPilgaard** [comment]
Oh right, I forgot about, sorry!

**Comment by NielsPilgaard** [comment]
https://github.com/TeamPneumatic/pnc-repressurized/issues/485
