### ISSUE TITLE
Duping with Vanillahammers mod

### ISSUE THREAD

**Issue by JohnGohan** [NillerMedDild/Enigmatica5#308]
**Modpack version**
0.4.11

**Issue**
When using any of the vanillahammers hammer it'll only mine the middle one of the supposedly 3x3 blocks while still dropping the included blocks allowing you to place cobblestone for example continuously for infinite duplications.
![2020-05-14_15 32 47](https://user-images.githubusercontent.com/30379226/81940786-3f05e380-95f8-11ea-8894-d3b7fe9a60f0.png) # #

**Comment by NielsPilgaard** [comment]
Thank you for the report, I will investigate the issue.

**Comment by MelanX** [comment]
Fixed :)
