### ISSUE TITLE
Soils Unobtainable for Botany Pots

### ISSUE THREAD

**Issue by NielsPilgaard** [NillerMedDild/Enigmatica5#310]
> it seems there are multiple soils botany pots support yet u cannot get

farmland 
overgrowth seed + the enchanted soil

**Comment by Wntermute** [comment]
These should be obtainable with a shovel or other tool that has silk touch.

**Comment by NielsPilgaard** [comment]
Farmland has never been obtainable with Silk Touch, and Enchanted Soil isn't either.
