### ISSUE TITLE
Mining Gadget Laser not centered on block. 

### ISSUE THREAD

**Issue by Zymm2133** [NillerMedDild/Enigmatica5#312]
**Modpack version**
0.4.11

**Issue**
Mining Gadget Laser not centered on block. 
![mining beam](https://user-images.githubusercontent.com/65385723/82015573-aba6cf80-9644-11ea-84e5-fccdb0ed4880.png)
![mining beam 2](https://user-images.githubusercontent.com/65385723/82015654-e7419980-9644-11ea-992c-c033e0f5db37.png)

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by Zymm2133** [comment]
Tested on 2 different systems, one using a texture pack and one not.

**Comment by hvdklauw** [comment]
Yeah, same here.. also structurize building wand preview is like 1.5 blocks offset from where it's actually placing things.

I think this was already in 0.4.10, then I had some weird things too

**Comment by NielsPilgaard** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NielsPilgaard** [comment]
~~I removed ShetiPhianCore and MultiBeds, and the problem went poof.~~
I commented on the wrong issue, still investigating this one.

**Comment by Zymm2133** [comment]
Awesome.  Thank you for the info.

-Ben
________________________________

**Comment by Zymm2133** [comment]
That didn’t work on my system. Removed mods from server and client.

-Ben
________________________________

**Comment by NielsPilgaard** [comment]
Try reading my comment again :P

**Comment by Zymm2133** [comment]
Sorry I missed that last part.   :)

**Comment by NielsPilgaard** [comment]
The issue seems to have been caused by the mod Neat, it is now fixed.

**Comment by hvdklauw** [comment]
Neat :trollface:

**Comment by Darkere** [comment]
More reports of this. Even with the new Neat version :/

**Comment by NielsPilgaard** [comment]
Yay another one of those issues, it works just fine for me :P

**Comment by NielsPilgaard** [comment]
Still works just fine for me, do you have any more details @Darkere?

**Comment by xenoflot** [comment]
I was getting this with Enig5 and ATM5 packs, for Powah, Building Gadgets and Minecolonies previews. I updated to the latest alpha Enig5 (which presumably includes Neat 1.6-22) and my previews are now all where they're supposed to be. Neat's health bars are even above heads instead of tickling knees!

**Comment by hvdklauw** [comment]
Fixed in 0.4.13 after following the instructions to delete certain folders before updating
