### ISSUE TITLE
PNC Compressed Iron issues

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica5#316]
**Modpack version**
0.4.12

**Issue**
Normally Compressed Iron Blocks can be split up into nine compressed iron ingots. This provides a quicker way of making compressed iron via the pressure chamber as you can make a block of iron, compress it, then split it up. Effectively crafting nine times faster. 

With Silent's compressed iron being used preferentially, that recipe for blocks to ingots seems to have been removed. 

If Silent's is going to be the defacto ingot, it might also be nice to simply alter the Pressure Chamber and Explosion crafting recipes to make Silent's Compressed Iron directly. Currently an extra crafting step is required to convert PNC to Silent's which feels a bit clunky.

Lastly, the PNC Manual still uses PNC compressed iron, rather than Silent's. This is the only recipe remaining that still uses PNC compressed iron. 

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NielsPilgaard** [comment]
Thanks for letting me know, I'll get that sorted :)
