### ISSUE TITLE
PNC Pneumatic Armor's Step Assist feature doesn't seem to work with StepUp

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica5#317]
**Modpack version**
0.4.12

**Issue**

Prior to the addition of StepUp, the PNC armor's step assist ability was working fine. Now, StepUp seems to override other forms of Step Assist. I only have functional step assist if I toggle on the StepUp one. I realize they were both added at the same time in the official pack, but I had PNC added for some time before that. 

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NielsPilgaard** [comment]
Do the two step assists function differently, or are they the same?

**Comment by MuteTiefling** [comment]
They're identical as far as I can tell. The PNC one just requires the armor to be worn, charged, and upgraded. Whereas the other is free. 

I just wouldn't expect one to disable the other. I'd like to test with something like the botania sash that also gives step assist, but I haven't had the chance yet.

**Comment by NielsPilgaard** [comment]
Botania Sash still works.

I reported the issue here: https://github.com/NotTooManyItems/StepUp/issues/7

Thanks for the bug report :)

**Comment by NielsPilgaard** [comment]
We're not getting around this I'm afraid, it's intended behaviour :)
