### ISSUE TITLE
Storage Scanner: No Add Button Showing in JEI for Recipe Crafting

### ISSUE THREAD

**Issue by LRayZor** [NillerMedDild/Enigmatica5#318]
**Modpack version**
Version 0.4.12

**Issue**
When inside the Storage Scanner, if you click on JEI to bring up a recipe, the Add (Plus) button does not appear to allow you to paste it into the crafting window.

**Logs**
N/A

**Comment by NielsPilgaard** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NielsPilgaard** [comment]
Confirmed and reported here: https://github.com/McJtyMods/RFToolsStorage/issues/14
