### ISSUE TITLE
Silver ore processing is wrong, again...

### ISSUE THREAD

**Issue by Giovanni-NL** [NillerMedDild/Enigmatica5#319]
**Modpack version**
0.4.12

**Issue**
Once again, Silent's Mechanisms Silver Ore is being crushed into Occultism Silver Dust by the Mekanism Enriching Factory. This issue was gone after upgrading the server and client from 0.4.10 to 0.4.12. But for some reason, a couple of days later, the issue is back...  I have not yet been able to figure out why and when this change has occurred, but I'm quite sure it worked properly for a while, and now it does not. The client shows no error when logging in, and the server logs show no errors which (to me at least) would indicate a problem with ore processing.
Previous issue was: #315 

**Logs**
No relevant logs that I could find (client or server).

**Comment by Darkere** [comment]
Can you post the servers latest.log and crafttweaker.log?

**Comment by NielsPilgaard** [comment]
Please post the logs in the original thread :)
