### ISSUE TITLE
Server becomes unresponsive

### ISSUE THREAD

**Issue by Giovanni-NL** [NillerMedDild/Enigmatica5#321]
**Modpack version**
0.4.12

**Issue**
Every now and again, the server becomes unresponsive. Clients time out, and people are logged off automatically.  There is no common activity that seems to cause this, it happens seemingly at random. Yesterday is was when I was looking in a chest, today it was when I was chopping a tree with an axe.  

When you are at the server screen in the client, you can still see the people that were logged on as being active, but in reality they are all logged out.  When you try to log back in, it takes a while and then you get a time-out error. Logging in fails.

The server itself keeps running, as you can see it writing to the logs from time to time.  See the attached log.  I was forced off the server at about 11:52, and from that time on a lot of Server-Worker warnings are written to the log. 

Only solution at that point is to restart the server. 
N.B. Just using the /stop command does start the saving of all chunks, but the server does not actually stop after that. It just hangs. You have to force-quit it to actually make it stop.

**Logs**
(https://github.com/NillerMedDild/Enigmatica5/files/4673261/latest.log)

**Comment by Darkere** [comment]
One known case where this can happen is the TrueShot enchant. I think we disabled it recently. But the setting is in the world/serverconfig/ma-enchants.toml so if your world is older that may not be the case for your world.

**Comment by Giovanni-NL** [comment]
We have [true_shot] enable = true in that file. Should I set it to false?

**Comment by Darkere** [comment]
The issue with the trueshot enchant is that it's arrows continue into unloaded chunks. I'm not certain if disabling the enchant will fix arrows that are already flying. 

But it will certainly prevent people from making more. 

@NillerMedDild You might be interested in this one: https://www.curseforge.com/minecraft/mc-mods/serverconfig-updater

<blockquote><div><strong><a href="https://www.curseforge.com/minecraft/mc-mods/serverconfig-updater">Attention Required! | Cloudflare</a></strong></div></blockquote>

**Comment by NielsPilgaard** [comment]
Oh boy, I thought Forge did that automatically ><
I'll get that added, thanks.

**Comment by NielsPilgaard** [comment]
Serverconfig updater added and set to "update" Ma Enchants config, so this'll be fixed in 0.4.13 :)
