### ISSUE TITLE
Poor TPS caused by Apotheosis mobs (I think)

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica5#323]
**Modpack version**
0.4.12

**Issue**
TPS in my world will randomly drop down to 10-13 and until recently I wasn't sure what might be causing the issue. I then started flying around in spectator mode to see if there was anything funky and I found an absolute ton of Apotheosis spawned named 'boss' mobs. Using /kill to target skeletons, zombies, and spiders did seem to help with TPS, but not for long, as one might expect. It did get it up to 20 TPS but with a mean tick time in the 30s. 

Setting the game to peaceful seems to have immediately fixed the issue and I'm at a mean tick time of 13, and a solid 20 TPS.

Note, I do tend to AFK for long periods of time. Since the game takes so long to load, I typically just leave it on in the background.

**Logs**
There didn't seem to be anything shown in the logs. Oddly, not even 'server can't keep up' messages. I'll see if I can capture some more logs tomorrow

**Comment by NielsPilgaard** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NielsPilgaard** [comment]
Any update on logs? :)

**Comment by MuteTiefling** [comment]
Sorry, forgot all about the logs. I've spent my time filling in all of the caves under my base to prevent the massive number of mobs I was seeing down there. I had named mobs hanging around with particle effects all over the place and it was just too much. They never despawn.

**Comment by NielsPilgaard** [comment]
I've lowered their spawn chances by a ton, I hope that helps.
