### ISSUE TITLE
Minecolonies Pirate Raid ships are... weird? 

### ISSUE THREAD

**Issue by Giovanni-NL** [NillerMedDild/Enigmatica5#324]
**Modpack version**
0.4.12

**Issue**
Part of the MineColonies mod is a Pirate raid that happens from time to time.  The ship they come in has some issues... Looks like for every 8 blocks of height another 8 blocks of air is inserted. 

![image](https://user-images.githubusercontent.com/4085882/82842570-55eee480-9eda-11ea-8d09-86765068560a.png)

**Logs**
n/a

**Comment by NielsPilgaard** [comment]
Thank you for the report, I will investigate the issue.

**Comment by merlerm** [comment]
![2020-05-30_00 05 19](https://user-images.githubusercontent.com/62080872/83327355-5b9e4e80-a27b-11ea-9bef-471e5fcdae13.png)
I can confirm this still happens in 0.4.13, but i wouldn't be sure how to recreate it. This was the only ship I spawned so far, and it looked like that. I'll be sure to update if more comes up
