### ISSUE TITLE
Odd holes in the ocean

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica5#325]
**Modpack version**
0.4.12

**Issue**
I keep seeing these generate out in Ocean biomes. I'm not sure what's causing them. Maybe Quark mega caves?

![2020-05-25_16 48 56](https://user-images.githubusercontent.com/9543430/82842519-dcd69980-9ea7-11ea-9eb0-d3dc748acba3.png)

**Comment by NielsPilgaard** [comment]
Quark Crevices cause that, and they have been turned off in 0.4.13 :)
