### ISSUE TITLE
MineColonies structures attempt placement on half-slab level

### ISSUE THREAD

**Issue by chimpman73** [NillerMedDild/Enigmatica5#326]
**Modpack version**
5 v0.4.12

**Issue**
MineColonies structures attempt placement on half-slab level

It appears that when placing a MineColonies Supply Camp or Supply Ship, that the structure is 1/2 block above or below where it needs to go.  Because of that, those structures can not be placed (the error is that specific blocks need an "air block" above them).

I reverted to v0.4.11 and the same problem occurred.
Reverting to v0.4.9 removes the problem.

**Comment by Darkere** [comment]
installing 0.4.13 also solves the problem ;).
