### ISSUE TITLE
Minecolonies crafting recipes missing

### ISSUE THREAD

**Issue by chimpman73** [NillerMedDild/Enigmatica5#327]
**Modpack version**
v0.4.9

**Issue**
The crafting recipe for Plain Oak Paper Timber Frame is missing (I can't find a recipe for any of the Timber Frames).  This causes problems once you get up to a level 3 structure, especially in the asian building style (but possibly for others).

The only way I was able to get these blocks was by going into creative mode.

**Comment by NielsPilgaard** [comment]
Try updating the modpack, you're 4 versions behind :)

**Comment by chimpman73** [comment]
I'm updating to 4.13 now, but I couldn't even start a colony in 4.11 or 4.12 to get this far.  Once updated I'll look for those recipes.

**Comment by chimpman73** [comment]
This is not an issue in 4.13.  The recipes exist in that version and they can be crafted.

Thanks!

**Comment by NielsPilgaard** [comment]
Awesome, thanks for the report anyhow :)
