### ISSUE TITLE
Keeps Crashing

### ISSUE THREAD

**Issue by QPCrummer** [NillerMedDild/Enigmatica5#328]
**Modpack version**
Enigmatica 5

**Issue**
I have accepted the eula, but when I load it, it says I have to accept it again. Then it crashes.

**Logs**

Starting Enigmatica 5 Server...
DEBUG: Attempting to execute [ java -Xmx4G -Xms2G -d64 -server -XX:+AggressiveOpts -XX:+UseConcMarkSweepGC -XX:+UnlockExperimentalVMOptions -XX:+UseParNewGC -XX:+ExplicitGCInvokesConcurrent -XX:+UseFastAccessorMethods -XX:+OptimizeStringConcat -XX:+UseAdaptiveGCBoundary -jar "C:\Users\Kitca\Desktop\Egnamatica Folder\Enigmatica5Server-0.4.12\forge-1.15.2-31.2.0.jar" nogui ]
2020-05-27 16:05:18,122 main WARN Advanced terminal features are not available in this environment
[32m[16:05:18] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 31.2.0, --fml.mcpVersion, 20200515.085601, --fml.mcVersion, 1.15.2, --fml.forgeGroup, net.minecraftforge, nogui]
[m[32m[16:05:18] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 5.1.0+69+master.79f13f7 starting: java version 1.8.0_251 by Oracle Corporation
[m[32m[16:05:19] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[m[32m[16:05:19] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Users/Kitca/Desktop/Egnamatica%20Folder/Enigmatica5Server-0.4.12/mods/MixinBootstrap-1.0.3.jar Service=ModLauncher Env=SERVER
[m[32m[16:05:21] [main/INFO] [STDERR/]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 36:0 token recognition error at: 'S'
[m[32m[16:05:21] [main/INFO] [STDERR/]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 36:1 token recognition error at: 'pa'
[m[32m[16:05:21] [main/INFO] [STDERR/]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 36:3 token recognition error at: 'w'
[m[32m[16:05:21] [main/INFO] [STDERR/]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 36:4 token recognition error at: 'n'
[m[32m[16:05:21] [main/INFO] [STDERR/]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 36:5 token recognition error at: 'e'
[m[32m[16:05:21] [main/INFO] [STDERR/]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 36:6 token recognition error at: 'r'
[m[32m[16:05:21] [main/INFO] [STDERR/]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 36:8 token recognition error at: 'N'
[m[32m[16:05:21] [main/INFO] [STDERR/]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 36:9 token recognition error at: 'B'
[m[32m[16:05:21] [main/INFO] [STDERR/]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 36:10 token recognition error at: 'T'
[m[32m[16:05:23] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [be.nevoka.betterbedrockgenerator.MixinConnector]
[m[32m[16:05:23] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [snownee.passablefoliage.mixin.Connector]
[m[32m[16:05:23] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [me.jellysquid.mods.phosphor.mixin.PhosphorMixinConnector]
[m[32m[16:05:23] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [snownee.snow.mixin.Connector]
[m[32m[16:05:23] [main/INFO] [be.ne.be.MixinConnector/]: Invoking Mixin Connector
[m[32m[16:05:23] [main/INFO] [Passable Foliage/]: Invoking Mixin Connector
[m[32m[16:05:23] [main/INFO] [Kiwi/]: Invoking Mixin Connector
[m[32m[16:05:23] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlserver' with arguments [--gameDir, ., nogui]
[m[ApotheosisCore]: Patching ItemStack#onItemUse
[RandomPatches CompoundNBT Transformer]: Transforming class: net/minecraft/nbt/CompoundNBT
[RandomPatches CompoundNBT Transformer]: Patching method: equals (equals)
[33m[16:05:24] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/gui/widget/button/ImageButton (java.lang.ClassNotFoundException: null)
[m[33m[16:05:24] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.gui.widget.button.ImageButton was not found kubejs.mixins.json:ImageButtonMixin
[m[ApotheosisCore]: Patching LivingEntity#blockUsingShield
[ApotheosisCore]: Patching LivingEntity#applyPotionDamageCalculations
Initializing transformation  org.objectweb.asm.tree.ClassNode@43ab0659
Found method updateElytra  org.objectweb.asm.tree.MethodNode@71262020
Found node  org.objectweb.asm.tree.LineNumberNode@129b69b2
[1;31m[16:05:24] [main/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/MainWindow for invalid dist DEDICATED_SERVER
[m[33m[16:05:24] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/MainWindow (java.lang.RuntimeException: Attempted to load class net/minecraft/client/MainWindow for invalid dist DEDICATED_SERVER)
[m[33m[16:05:24] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.MainWindow was not found kubejs.mixins.json:MainWindowMixin
[m[RandomPatches Minecraft Transformer]: Patching method: func_230149_ax_ (func_230149_ax_)
[1;31m[16:05:24] [main/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
[m[33m[16:05:24] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/Minecraft (java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER)
[m[33m[16:05:24] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.Minecraft was not found kubejs.mixins.json:MinecraftMixin
[m[1;31m[16:05:24] [main/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/gui/ResourceLoadProgressGui for invalid dist DEDICATED_SERVER
[m[33m[16:05:24] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/gui/ResourceLoadProgressGui (java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/ResourceLoadProgressGui for invalid dist DEDICATED_SERVER)
[m[33m[16:05:24] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.gui.ResourceLoadProgressGui was not found kubejs.mixins.json:ResourceLoadProgressGuiMixin
[m[RandomPatches Entity Transformer]: Patching method: func_189511_e (func_189511_e)
[RandomPatches Entity Transformer]: Patching method: func_70020_e (func_70020_e)
[ApotheosisCore]: Patching Item#getItemEnchantability
[ApotheosisCore]: Patching LivingEntity#blockUsingShield
[ApotheosisCore]: Patching LivingEntity#applyPotionDamageCalculations
Initializing transformation  org.objectweb.asm.tree.ClassNode@1df9f7c6
Found method updateElytra  org.objectweb.asm.tree.MethodNode@4b5aa48b
Found node  org.objectweb.asm.tree.LineNumberNode@51c008fd
[32m[16:05:26] [main/INFO] [minecraft/MinecraftServer]: You need to agree to the EULA in order to run the server. Go to eula.txt for more info.
[m
WARN: Enigmatica 5 Server was stopped (possibly crashed)...
At 20200527:160512 Server has stopped.
Server has 1 consecutive stops, each within 600 seconds of eachother...

**Comment by NielsPilgaard** [comment]
Remove all spaces from the Eula :)
