### ISSUE TITLE
Glass panes vanishing in Refined Storage

### ISSUE THREAD

**Issue by xenoflot** [NillerMedDild/Enigmatica5#329]
**Modpack version**
0.4.13

**Issue**
When placed into a Refined Storage system, glass panes simply disappear.

Only regular, uncoloured glass panes appear to be affected. Stained glass panes and the modded panes, work fine. 

I set up a test instance with just JEI, refstor and refstor addons and it works fine. Added Engineers's Decor and PITG and still working fine. Not sure what else might be affecting it, but if you'd care to name a few other mods, I'm happy to do some more testing.

**Logs**
No crash

**Comment by xenoflot** [comment]
Added glasential to the test, still fine.

Completely unrelated - I thought I read somewhere there was a mod in the pack that increased the frequency of wandering traders, but I can't spot it on the dep list. Can you tell me which one? They're making me homicidal. So many llamas...

**Comment by NielsPilgaard** [comment]
Thanks for the report, I'll look into it.
That mod is Apotheosis, and I will be turning the frequency increase off :)

**Comment by NielsPilgaard** [comment]
Hmm I can't seem to reproduce this, would you mind testing whether it's still an issue in 0.4.14?
