### ISSUE TITLE
Cooking Cactus in a furnace gives Charcoal :-/

### ISSUE THREAD

**Issue by xenoflot** [NillerMedDild/Enigmatica5#330]
**Modpack version**
0.4.13

**Issue**
Cactus in a furnace used to give Quark's Cactus Paste which can then be crafted into green dye. However, that appears to have changed and is now giving Charcoal. Looking at 'Uses', the Smelting tab shows both charcoal and cactus paste, but both IF's Resourceful Furnace and vanilla Furnaces are giving charcoal.

It looks like cactus has been ore-dicted to wood for some reason. I would suggest undoing that. Wood isn't hard to get in minecraft!

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NielsPilgaard** [comment]
Thanks for letting me know, I'll get that fixed. I wonder which mod did that, and why.

**Comment by xenoflot** [comment]
Found it!

https://github.com/ldtteam/Structurize/pull/149

**Comment by NielsPilgaard** [comment]
Nice :D
