### ISSUE TITLE
Whoops mod functionality consumes 2 logs/stones instead of 1 when right-clicking

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica5#331]
**Modpack version**
E5 0.4.13

**Issue**
The functionality added by the mod 'Whoops' seems to be working incorrectly. It consumes 2 of the block in in the hotbar instead of a single block.

**Logs**
N/A

**Screenshots**
![image](https://user-images.githubusercontent.com/64355028/83306405-c8293700-a202-11ea-9459-21ed342176d6.png)
![image](https://user-images.githubusercontent.com/64355028/83306539-058dc480-a203-11ea-880a-f7ed300411c2.png)

**Comment by NielsPilgaard** [comment]
Thanks for the bug report (and welcome back) - I found it here as well https://github.com/noobanidus/Whoops/issues/2
