### ISSUE TITLE
Game Crash -  java.lang.NullPointerException: charTyped event handler

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica5#332]
**Modpack version**
E5 0.4.13

**Issue**
The game crashes when attempting to open the basic Shape Card GUI from within RFTools Builder.
GDLauncher has also provided the following error when the game crashes.

_AL lib: (EE) alc_cleanup: 1 device not closed_

**Logs**
Attached.

[crash-2020-05-30_04.50.53-client.txt](https://github.com/NillerMedDild/Enigmatica5/files/4705006/crash-2020-05-30_04.50.53-client.txt)

**Comment by NielsPilgaard** [comment]
Thanks for the report, it was reported by xenoflot here: https://github.com/McJtyMods/RFToolsBuilder/issues/22
