### ISSUE TITLE
Silktouch does not work on Glass Blocks/Panes from the Connected Glass mod

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica5#333]
**Modpack version**
E5 0.4.13

**Issue**
Using Silktouch enchanted items, or the Mining Gadget with Silktouch upgrade, does not retrieve the broken glass blocks/panes added by the Connected Glass mod.

**Logs**
N/A

**Comment by NielsPilgaard** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NielsPilgaard** [comment]
Reported here: https://github.com/SuperMartijn642/ConnectedGlass/issues/5
