### ISSUE TITLE
Some Botania Quartz is uncraftable. 

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica5#334]
**Modpack version**
0.4.13

**Issue**
The following quartz variants are unobtainable: 
Blaze Quartz
Sunny Quartz
Lavender Quartz
Redquartz

These should all have a 3x3 craft of 8 quartz plus 1 catalyst material (blaze powder, sunflower, lavender, and redstone dust) to get 8 of the new variant.

**Comment by NielsPilgaard** [comment]
Woops, I'll get that fixed ^^'
