### ISSUE TITLE
Nether Portal spread-prevention with 2 blocks of coal is not functional when the portal is a big sized protal

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica5#335]
**Modpack version**
E5 0.4.13

**Issue**
Placing 2 blocks of coal underneath the Nether portal doesn't prevent the nether spread if the portal is bigger than than the standard 4x5.

**Logs**
N/A

**Screenshot**
![image](https://user-images.githubusercontent.com/64355028/83337870-316e8000-a2bf-11ea-8357-d3b223d7bbde.png)

**Comment by NielsPilgaard** [comment]
Nether Portal Spread is being removed in 0.4.14 :)
