### ISSUE TITLE
Minecolonies Hospital not placing properly

### ISSUE THREAD

**Issue by merlerm** [NillerMedDild/Enigmatica5#337]
**Modpack version**
0.4.13

**Issue**
The minecolonies hospital structure seems to have trouble with correct positioning. From the last two screenshots, you can see how i was first trying to place it and how it actually places the construction tape, shifting it to the left a bit seemingly. After building it, i noticed it was rotated the wrong way. When trying to rotate it, as seen in the first two screenshots, the orientation of the block doesn't seem to change after the reposition. 
What i'm guessing is happening here is the building is failing to rotate properly, which would explain the first issue as well: it's not shifting to the left, it's just not rotating. 
As far as I can tell, this is the only structure with this issue.
![2020-06-01_00 17 31](https://user-images.githubusercontent.com/62080872/83364001-1c1c5300-a39e-11ea-9bc8-e4af87a205f7.png)

![2020-06-01_00 17 21](https://user-images.githubusercontent.com/62080872/83364000-1b83bc80-a39e-11ea-903d-0988b7987c41.png)

![2020-05-30_14 27 22](https://user-images.githubusercontent.com/62080872/83363998-1a528f80-a39e-11ea-9d45-95ed8ef018f1.png)

![2020-05-30_14 27 16](https://user-images.githubusercontent.com/62080872/83363997-1888cc00-a39e-11ea-87fd-811e0f07a756.png)

**Comment by NielsPilgaard** [comment]
Thanks for the report, I relayed it :)
