### ISSUE TITLE
Waystones2Waypoints - invalid as a value for both the Waystone Name and Waypoint

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica5#338]
**Modpack version**
E5 0.4.13

**Issue**
When discovering (or creating) a Waystone, the mod (Waystones2Waypoints) is supposed to add it as a Waypoint to Xaero's Worldmap. However, the value seems to always be set to 'invalid', and that is on both the Waypoints list, and the Waystone name. 
Please note that changing the Waystone name will infact update the displayed list of discovered locations, but not in the actual name area.
Furthermore, the Waypoint added is in an incorrect coordinates. 

**Logs**
N/A

**Screenshots**
This is a created Waystone I placed in my colony. Even if I named it to 'Rid's Colony' as can be seen in the listed locations, it still displays as 'invalid' in the name.
![image](https://user-images.githubusercontent.com/64355028/83385415-7ee70c00-a3e9-11ea-9bef-600802a89509.png)

This waypoint is created automatically when discovering the Waystone, and as can be seen, it is showing as 'invalid'
![image](https://user-images.githubusercontent.com/64355028/83385336-53642180-a3e9-11ea-9ac0-e6d0b9be5cfe.png)

The Waypoint is placed far away from the Waystone
![image](https://user-images.githubusercontent.com/64355028/83385700-fb79ea80-a3e9-11ea-91c3-514fb0ca4d06.png)

**Comment by NielsPilgaard** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NielsPilgaard** [comment]
Works just fine for me, but I did update Xaero's a time or two :)

**Comment by Ridanisaurus** [comment]
I can confirm that it is now working on the copy of the world you provided on when running it as a Single Player. Will test it again when 0.4.14 comes.

**Comment by Shindur** [comment]
Still happening on 0.5.1 on a freshly made server.

Edit: Also seems to be making new waypoints each time the waystone is right clicked on, at least the one I found in this village is doing it...

**Comment by NielsPilgaard** [comment]
I can't reproduce any of those issues :/ would you mind supplying both server and client log @Shindur ?

**Comment by Shindur** [comment]
Sure, here you go. This is on a newly created server world and in survival right clicking the waystone. I think the multiple waypoints/invalid marks were due to being in creative, but I have to test that still as in survival it only occurred once on the waystone.
[ClientLatest.log](https://github.com/NillerMedDild/Enigmatica5/files/4800378/ClientLatest.log)
[ServerLatest.log](https://github.com/NillerMedDild/Enigmatica5/files/4800379/ServerLatest.log)

**Comment by NielsPilgaard** [comment]
Dammit, nothing helpful in there ><

**Comment by Shindur** [comment]
One thing I have noticed, is every waystone I've placed down so far and right clicked to test has put the waypoint at 0x 0z and 1y - at world spawn and at bedrock.

**Comment by NielsPilgaard** [comment]
The developer is aware of the issue, but sadly doesn't have the time or energy atm to investigate/fix it, he has recommended that we simply remove the mod for the time being, so I will :)
