### ISSUE TITLE
Stripping log with an axe in a crafting grid is duplicating the logs

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica5#339]
**Modpack version**
E5 0.4.13

**Issue**
Using the functionality to strip logs in the crafting table with an axe is duplicating the logs. Furthermore, you can only do it 1 log at a time. Holding shift, and clicking on the output does not work.

**Logs**
N/A

**Screenshots**
![image](https://user-images.githubusercontent.com/64355028/83437790-a917e880-a440-11ea-8c8d-e89ecc46aaf3.png) 
![image](https://user-images.githubusercontent.com/64355028/83437922-e0869500-a440-11ea-8d46-3e550fc19f31.png)

**Comment by NielsPilgaard** [comment]
Yikes, thanks for the report.

**Comment by NielsPilgaard** [comment]
Reported to Darkere on Discord, fixed in PR: https://github.com/refinedmods/refinedstorage/pull/2564
