### ISSUE TITLE
Storage Scanner inventory highlight functionality is not working

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica5#340]
**Modpack version**
E5 0.4.13

**Issue**
When double clicking on an Inventory, the Storage Scanner is supposed to highlight that inventory. However, this functionality doesn't seem to be working.

**Logs**
N/A

**Screenshot**
![image](https://user-images.githubusercontent.com/64355028/83443759-8f7b9e80-a44a-11ea-8bfc-fe3210aa4fa8.png)
![image](https://user-images.githubusercontent.com/64355028/83443926-da95b180-a44a-11ea-81e8-ff9e3f2c6a96.png)

**Comment by NielsPilgaard** [comment]
Relayed here: https://github.com/McJtyMods/RFToolsStorage/issues/16
