### ISSUE TITLE
Dying multiplies player's max hearts

### ISSUE THREAD

**Issue by ElliClaw** [NillerMedDild/Enigmatica5#342]
**Modpack version**
0.4.12

**Issue**
Dying increases max hearts after earning additional hearts from Spice of Life: Carrot Edition. After every single death, my maximum health goes up.

**Comment by NielsPilgaard** [comment]
Could you please check for if this also occurs on 0.4.13?

**Comment by ElliClaw** [comment]
Yep, still occurs on 0.4.13 with a new world.

**Comment by NielsPilgaard** [comment]
Thanks, I'll have a look.

**Comment by Trostmm** [comment]
Also occurring on 0.4.15, didn't have to die, just went to the end and back through the pool.

**Comment by NielsPilgaard** [comment]
It has been reported here: https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/issues/95
