### ISSUE TITLE
Minecolonies Florist can generate Botania flowers, including functional flowers

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica5#347]
**Modpack version**
E5 0.4.13

**Issue**
The Minecolonies Florist/Flower Shop can generate Botania flowers at level 2, this includes functional flowers which completely breaks the Botania progression system. I've checked on their Discord, and they confirmed that the shop is designed to just generate flowers, regardless of mod compatibility, and forcing some flowers not to appear should be done intentionally, so I guess it is modpack to modpack basis.

**Logs**
N/A

**Screenshots**
![image](https://user-images.githubusercontent.com/64355028/84072018-cca5da80-a9ce-11ea-9570-489de6b7ac94.png)

**Comment by Ridanisaurus** [comment]
Someone from Minecolonies Discrod suggest the following change to the config:

listofplantables = ["minecraft:sunflower", "minecraft:lilac", "minecraft:rose_bush", "minecraft:peony", "minecraft:tall_grass", "minecraft:large_fern", "minecraft:fern", "minecraft:dandelion", "minecraft:poppy", "minecraft:blue_orchid", "minecraft:allium", "minecraft:azure_bluet", "minecraft:red_tulip", "minecraft:orange_tulip", "minecraft:white_tulip", "minecraft:pink_tulip", "minecraft:oxeye_daisy", "minecraft:cornflower", "minecraft:lily_of_the_valley"]

**Comment by NielsPilgaard** [comment]
I did just that, thank you for the report and fix :)

**Comment by theboo** [comment]
might be cool to add the botania mystical flowers to the list as well, idk
