### ISSUE TITLE
Suggestion: DruidCraft

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica5#349]
https://www.curseforge.com/minecraft/mc-mods/druidcraft

Would be nice to see this in this pack. Seems like it would go along nicely with Nature's Aura and Botania

**Comment by NielsPilgaard** [comment]
I don't really understand Druidcraft to be honest, it seems to have a bunch of random stuff in it, not really anything related to druidry.

**Comment by NielsPilgaard** [comment]
It's gonna be a no still. It has some really pretty stuff, but it's pretty random. If it was actually about Druidry, I'd be more inclined to add it.
