### ISSUE TITLE
Torchmaster Feral Flare and Frozen Pearl tooltips seems to be broken

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica5#351]
**Modpack version**
E5 0.4.14

**Issue**
The tooltip of Torchmaster's Feral Flare and Frozen Pearl seems to be broken. Other items are showing as expected.

**Logs**
N/A

**Screenshots**
![image](https://user-images.githubusercontent.com/64355028/84193961-9171dd00-aa9c-11ea-9335-6266550dc03f.png)
![image](https://user-images.githubusercontent.com/64355028/84193991-9d5d9f00-aa9c-11ea-88ca-78cf73b4d65d.png)

**Comment by NielsPilgaard** [comment]
Known issue :/ https://github.com/Xalcon/TorchMaster/issues/115
