### ISSUE TITLE
RFTools Builder - Game hangs if attempting to configure space card in a builder

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica5#352]
**Modpack version**
0.4.13

**Issue**
If I place a ~~space~~ shape card in a builder, then press the ? button to alter the offsets, the game simply hangs. It doesn't crash out and, unfortunately, is generating no logs. It'll sit there in a hung up state for quite a while too without recovering. I eventually have to X out of the game

**Logs**
No crash log is being generated... Here's the main log, however. Didn't see anything there though. 
[2020-06-12-1.log.gz](https://github.com/NillerMedDild/Enigmatica5/files/4770481/2020-06-12-1.log.gz)

**Comment by NielsPilgaard** [comment]
Hmm yikes... It could be your java version :P Try the fix below:

You appear to be using outdated Java. This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add `-version:1.8+` to the Additional Arguments

<blockquote><div><strong><a href="https://www.java.com/en/download/manual.jsp">Java Downloads for All Operating Systems</a></strong></div><div>Java manual download page. Get the latest version of the Java Runtime Environment (JRE) for Windows, Mac, Solaris, and Linux.</div></blockquote>

**Comment by MuteTiefling** [comment]
Hrm, yeah Java is updated, but I guess since I'm using the Native Launcher it wasn't using the version installed on my machine. I actually had no idea how to even specify which version to use, so thanks for the tip. 

I just tried again, however, and the game is stuck. It is _slightly_ better in that it appears as though there's simply a missing GUI. I left the F3 screen open and I see stuff still moving, memory going up and down as normal. I just can't actually interact with the window anymore. 

It even still lets me take screenshots

![2020-06-12_20 12 59](https://user-images.githubusercontent.com/9543430/84555109-2b2dca00-ace9-11ea-872d-bf905d68cf53.png)

**Comment by NielsPilgaard** [comment]
Huh, interesting :D May I have the new latest log please?

**Comment by MuteTiefling** [comment]
[2020-06-12-5.log.gz](https://github.com/NillerMedDild/Enigmatica5/files/4775863/2020-06-12-5.log.gz)
[2020-06-12-4.log.gz](https://github.com/NillerMedDild/Enigmatica5/files/4775864/2020-06-12-4.log.gz)
[2020-06-12-3.log.gz](https://github.com/NillerMedDild/Enigmatica5/files/4775865/2020-06-12-3.log.gz)
[2020-06-12-2.log.gz](https://github.com/NillerMedDild/Enigmatica5/files/4775866/2020-06-12-2.log.gz)
[2020-06-12-1.log.gz](https://github.com/NillerMedDild/Enigmatica5/files/4775867/2020-06-12-1.log.gz)
[2020-06-13-3.log.gz](https://github.com/NillerMedDild/Enigmatica5/files/4775868/2020-06-13-3.log.gz)
[2020-06-13-2.log.gz](https://github.com/NillerMedDild/Enigmatica5/files/4775869/2020-06-13-2.log.gz)
[2020-06-13-1.log.gz](https://github.com/NillerMedDild/Enigmatica5/files/4775870/2020-06-13-1.log.gz)

Here are the logs I have for when I was messing around with this. Nothing much to see, unfortunately.

**Comment by NielsPilgaard** [comment]
There are crashes in some of those logs, would you mind recreating the issue and supplying the log from that? Not really sure what I'm looking at with all those :(

**Comment by MuteTiefling** [comment]
[latest.log](https://github.com/NillerMedDild/Enigmatica5/files/4789203/latest.log)

In this one, I started up, plopped down the builder, and hit the ? button. After that I just had to X out to quit since I couldn't open any other menus afterwards.

**Comment by NielsPilgaard** [comment]
Thanks - It appears that `[17:28:12] [Thread-33/INFO]: Block file not found: rftoolsutility:timer` is printed in the log every time it happens.
