### ISSUE TITLE
Crashes when previewing Botania multi blocks from Patchouli

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica5#353]
**Modpack version**
0.4.13

**Issue**
Getting a hard crash suddenly when attempting to preview Botania's Mana Enchanter from the Patchouli book. I can successfully preview structures in Nature's Aura's guide book, oddly enough. But it would seem anything in the Botania book is crashing me out. Just got a third crash attempting to preview the Gaia ritual. To the best of my knowledge, I haven't actually got any previews sitting around in the world... 

**Logs**
[crash-2020-06-13_23.42.52-client.txt](https://github.com/NillerMedDild/Enigmatica5/files/4775871/crash-2020-06-13_23.42.52-client.txt)

[crash-2020-06-13_23.34.34-client.txt](https://github.com/NillerMedDild/Enigmatica5/files/4775872/crash-2020-06-13_23.34.34-client.txt)

[crash-2020-06-14_00.45.34-client.txt](https://github.com/NillerMedDild/Enigmatica5/files/4775876/crash-2020-06-14_00.45.34-client.txt)

**Comment by NielsPilgaard** [comment]
Reported and fixed here: https://github.com/Vazkii/Patchouli/issues/224
This issue should be resolved on 0.4.15 :)
