### ISSUE TITLE
Spruce Drying Rack Recipe Conflict

### ISSUE THREAD

**Issue by LunixNovalis** [NillerMedDild/Enigmatica5#354]
**Modpack version**
0.4.13

**Issue**
Spruce Drying Rack recipe conflicts with Spruce Flooring.

I found a 2 month old issue that was marked completed and fixed in next update, but its not fixed for the spruce version.

**Comment by NielsPilgaard** [comment]
I have a feeling you wouldn't see that issue in a newly installed instance, but who knows. I can assure you the problem will go away in version 0.5.0 :)

**Comment by NielsPilgaard** [comment]
Updating to 0.4.15 would also resolve this issue I believe, fyi.
