### ISSUE TITLE
Only double sided tools are craftable in tetra

### ISSUE THREAD

**Issue by theboo** [NillerMedDild/Enigmatica5#358]
**Modpack version**
0.5.0

**Issue**
currently you can only make double sided tools with tetra by modifying a hammer/wooden mallet. putting a sword or any other vanilla tool will not let you modify its parts. Therefore tetra swords and shovels(single head items) are impossible to craft

https://gyazo.com/410952b45639be806f5854e2932470f3

**Comment by NielsPilgaard** [comment]
Errrr... okay.. I wonder how it worked for me. Server issue perhaps.

**Comment by NielsPilgaard** [comment]
Heh, I can't get anything to work :P

**Comment by theboo** [comment]
lol yeah, i tested this one in SP before reporting xD

**Comment by NielsPilgaard** [comment]
Alright I think I've found the issue: Only the Tools registered as valid Tetra tools from my datapack are loaded, not the base ones

**Comment by NielsPilgaard** [comment]
I asked Mickelus about it, and apparently replacements do not stack, I'm putting an s at the end of the file names to fix this issue :P
