### ISSUE TITLE
Dirt ores can be crushed into full dusts

### ISSUE THREAD

**Issue by Discomanco** [NillerMedDild/Enigmatica5#360]
**Modpack version**
0.5.0

**Issue**
The Dirt Ore Deposits can be Create Crushing Wheel'd into full Dusts, which then can be smelted into ingots

**Comment by NielsPilgaard** [comment]
That is intended, crushing/enriching yields 1 dust :)

**Comment by NielsPilgaard** [comment]
Hmm, I forgot the IE crusher though.

**Comment by Discomanco** [comment]
Fair enough - granted I didn't look at the Crushing Wheel recipe since Create 0.1 :P

**Comment by NielsPilgaard** [comment]
Just realized I didn't forget it, woops.
