### ISSUE TITLE
[0.5.0] No Ability Bottle when spawning in server

### ISSUE THREAD

**Issue by Frikkle** [NillerMedDild/Enigmatica5#361]
**Modpack version**
0.5.0

**Issue**
Spawning in the (public) server for the first time did not give me any Ability Bottle. Not sure why and how. Others seem to have it? Disco, Boo and Merlo had one.

**Logs**
N/a

**Comment by NielsPilgaard** [comment]
Huh, interesting. Maybe it rolled a disabled ability and just didn't spawn?

**Comment by Shindur** [comment]
I noticed for myself and my friend, when we spawned in my server running 0.5.1 the EXP and bottle were on the ground, not automatically in the player's inventory.

This could pose a problem if the person is slow loading in (think potato computer) and the items/exp disappear before they load in. Or they have trolly/jerky friends who steal their EXP and bottle :P

**Comment by Frikkle** [comment]
I spawned in the E5 public service at spawn (underground?) and there was nothing there. So I think Niller's suggestion might have been happening. I am definitely not running on a potato :3

**Comment by NielsPilgaard** [comment]
If anyone manages to reproduce this please let me know :D
