### ISSUE TITLE
Mining Gadgets crashing server

### ISSUE THREAD

**Issue by theboo** [NillerMedDild/Enigmatica5#363]
**Modpack version**
0.5.0

**Issue**
Server has crashed 3 times due to someone using a mining gadget. I am assuming some sort of mod conflict but no idea. Did not have these issues in previous versions of e5 that i am aware of. Both disco and darkere have seen the crash report.

**Comment by Darkere** [comment]
Crashlog: https://gist.github.com/Darkere/8afa228057b4da64e87f228f34e196d7

no indication to what's going wrong.

<blockquote><img src="https://github.githubassets.com/images/modules/gists/gist-og-image.png" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> Gist</div><div><strong><a href="https://gist.github.com/Darkere/8afa228057b4da64e87f228f34e196d7">gist:8afa228057b4da64e87f228f34e196d7</a></strong></div><div>GitHub Gist: instantly share code, notes, and snippets.</div></blockquote>

**Comment by NielsPilgaard** [comment]
The only change I can think of that could affect rendering is the addition of Immersive Engineering :/
Does it happen immediately when using a Mining Gadget?

**Comment by theboo** [comment]
no, randomly.. they are able to use it for awhile, sometimes 30 seconds sometimes a few minutes

**Comment by theboo** [comment]
i dont have a gadget to test but i was thinking maybe IE ores? those are new and new to 1.15

**Comment by NielsPilgaard** [comment]
Worth a shot, I'll try.

**Comment by NielsPilgaard** [comment]
That's a nope for singleplayer, couldn't get it to crash yet.

**Comment by NielsPilgaard** [comment]
We haven't been able to reproduce this for quite some time, closing it for now.
