### ISSUE TITLE
Vanilla campfire ticking way too much on servers

### ISSUE THREAD

**Issue by merlerm** [NillerMedDild/Enigmatica5#364]
**Modpack version**
0.5.0

**Issue**
Vanilla campfire seem to have troubles with ticking when directly looked at, only on servers. Here's a video showing the bug in action.
https://www.youtube.com/watch?v=pdZMdMAM0rc&feature=youtu.be
As you can see, when I look directly at the campfire, both the smoke particles and the embers start coming out, as if the campfire is being tick accelerated. This doesn't happen in singleplayer worlds. On server, it happens with and without a hay bale underneath the campfire

**Comment by NielsPilgaard** [comment]
What the hell, I'll try and figure out what's going on, thanks.

**Comment by merlerm** [comment]
Update, it seems fixed in 0.5.1
The plot thickens

**Comment by NielsPilgaard** [comment]
Well yay :P

**Comment by NielsPilgaard** [comment]
I think we need a `Status: Fixed by last Release I guess?` label :P
