### ISSUE TITLE
Create Integration

### ISSUE THREAD

**Issue by theboo** [NillerMedDild/Enigmatica5#366]
https://www.curseforge.com/minecraft/mc-mods/create-integration

comes with a machine that converts rotation to FE, fully customize-able ofc, as well as a Create-themed enderchest style crate. I have work so not able to test it myself. (Mod found and suggested by Rid)

**Comment by Ridanisaurus** [comment]
I tested it, and it works pretty well. It's fairly light as far as blocks and items added, and it uses Create items for its recipes. I can provide some screenshots, if needed.

**Comment by NielsPilgaard** [comment]
It sounds a bit on the OP side, but I'm not directly against it :P

**Comment by theboo** [comment]
I am totally fine with it being nerfed fairly hard tbh... Mostly would be cool to be able to run a small RS system off it... I am all for disabling the FE to rotation (the mod can convert both ways) part tho...

**Comment by merlerm** [comment]
From the looks of it, it has handy config options to customize the amount of RF/rotation needed. I feel like that's the key to introduce it and balance it, while not making it too broken

**Comment by NielsPilgaard** [comment]
I will check this out when 0.5.x has had a stable release :)

**Comment by MuteTiefling** [comment]
Just my 2 cents here, but there's already at least 2 clever ways to do RF/rotational power in the pack that are very low RF cost. adding another seems a bit much, but this also allows converting rotational power to RF. That seems like a recipe for an infinite feedback loop. Maybe something to keep an eye out for.

**Comment by theboo** [comment]
what are these two RF>rotation methods you speak of? also rotation to RF is lossy by default. If you read my comment earlier, i said i was completely okay with RF>rotation being disabled from this mod anyway. I was just hoping to be able to power a small RS system using create, not anything crazy. The other things this mod adds are a moveable chunk loader(loads the one chunk it is currently in) and the ender crate which is ender chest like item transfer but works on moving contraptions.

**Comment by MuteTiefling** [comment]
@theboo Immersive Engineering's External heater can power a furnace for about 8rf/t. If you give it a redstone signal it will power the furnace even if there's nothing to smelt. That's enough to get Create's flywheel/furnace engine running.

Similarly, PneumaticCraft can run a furnace with it's own heat. Put a vortex tube against a furnace and it'll start smelting anything in it. This method requires smelting items, but it's a breeze to loop a couple pieces of iron through a Mekanism Crusher and smelt the resulting dust. Automating that just takes a little bit of piping. That whole system takes about 25 rf/t if you tune everything correctly, limiting the air flow to the vortex tube and keeping the flux compressor cooled. The nice part of this is that you can also use other fuels (diesel, kerosene, lpg, or even burnables) at a much more efficient rate to power your rotational setups.

**Comment by NielsPilgaard** [comment]
It's gonna be a nope for now, but I'll keep an eye on it as it develops. In it's current state, I don't think it would add much, and it would add a little bloat.
