### ISSUE TITLE
Mekanism Infuser makes Steel Dust, not Grit

### ISSUE THREAD

**Issue by merlerm** [NillerMedDild/Enigmatica5#367]
**Modpack version**
0.5.1

**Issue**
More of an annoyance really, but I'm not sure if this one got under the radar. When making steel through Mekanism, the infuser makes Mek steel dust, which can then be crafted into IE steel grit. Dust has no recipes, so it has to be converted to grit. It'd be nice if the machine made grit directly, bypassing steel dust entirely, since it's pointless

**Comment by NielsPilgaard** [comment]
That went under my radar, this kind of issue is exactly why 0.5.x versions are in alpha :D Thanks Merlo!

**Comment by hvdklauw** [comment]
ah, just ran into this.. seems to be a lot of silent mechanism recipes while it's not in the pack.

**Comment by NielsPilgaard** [comment]
Please read the changelog when updating @hvdklauw :)
