### ISSUE TITLE
Add Engineer's Tools

### ISSUE THREAD

**Issue by hvdklauw** [NillerMedDild/Enigmatica5#370]
https://www.curseforge.com/minecraft/mc-mods/engineers-tools

I especially like the _Ariadne Coal_ because I always get lost :D

**Comment by NielsPilgaard** [comment]
I'll have a look, thanks for the suggestion.

**Comment by NielsPilgaard** [comment]
That redia axe is very very OP :P
I'm sorry but no, I don't really like the items, except for Ariadne Coal.
