### ISSUE TITLE
Immersive Engineering Metal Press not syncing properly on servers

### ISSUE THREAD

**Issue by merlerm** [NillerMedDild/Enigmatica5#372]
**Modpack version**
0.5.1

**Issue**
The IE metal press is acting strange on servers, here's a video of the exact behaviour: https://www.youtube.com/watch?v=GNYdJRDYXHk&feature=youtu.be

It is not due to the weird XNet interaction i had there, testing it with a crate straight on the extractor did the same thing.
When investigating on the IE discord and providing them with the test crash pasted down here, I was told it is likely a compatibility issue, and to try removing batches of mods to see what is causing it. As it is a server issue, I currently can't test this myself.

**Logs**
https://pastebin.com/Yf7kuQyZ

**Comment by NielsPilgaard** [comment]
I'll try to find out what's up, thanks :)

**Comment by NielsPilgaard** [comment]
I can't reproduce this issue on a fresh E5 test server. Do you happen to know what the server TPS was during the time of the recording?

**Comment by NielsPilgaard** [comment]
We discussed the issue further on Discord, and Merlo is trying to zone in on what's going on, other things are buggy too.

**Comment by merlerm** [comment]
It was caused by an interaction with performant. Removing it from the server solved the issue. Darkere might know more

https://imgur.com/a/smUN8yR

<blockquote><img src="https://i.imgur.com/K2BUzbO.jpg?fb" width="48" align="right"><div><img src="//s.imgur.com/images/favicon-16x16.png" height="14"> Imgur</div><div><strong><a href="https://imgur.com/a/smUN8yR">Imgur</a></strong></div><div>Post with 0 views.</div></blockquote>

**Comment by NielsPilgaard** [comment]
I.. what? The server has Performant?

**Comment by Darkere** [comment]
I added it back when we were experiencing heavy load on the 0.5.0 release. 

It was a nice and small improvement to entity goal selector once... Now it has a bunch of stuff no one needs. removed it again as traffic has died down.

**Comment by NielsPilgaard** [comment]
Alright, cool.
