### ISSUE TITLE
[Suggestion] Add recipe to turn clear glass back into normal glass

### ISSUE THREAD

**Issue by merlerm** [NillerMedDild/Enigmatica5#373]
**Modpack version**
0.5.1

**Issue**
Clear glass from the connected glass mod can't be turned back into regular glass, and it's rather annoying for basic crafting recipes. A solution would be either adding a recipe to turn it back (maybe 4 to 4 like the rest of the mod recipes) or adding the forge:glass (with the respective colors i guess) tag on all of the blocks (if i understand tags correctly, that should at least make it useful for some of the recipes). This would be a QoL improvement, since as of now if you overcraft clear glass you're just left with it standing there useless.

**Comment by NielsPilgaard** [comment]
Absolutely, thanks for the suggestion.

**Comment by NielsPilgaard** [comment]
This was fixed in the mod :D
