### ISSUE TITLE
Suggestion: YUNG's Better Mineshafts

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica5#374]
**Modpack version**
E5 0.5.1

**Enhancement**
Was just watching Vallen's video on YUNG's Better Caves, and Better Mineshafts. 
The YUNG's Better Mineshafts looks pretty cool, and it could help add a little bit of exploration to the game. 
https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-forge
Mischief of Mice Video: https://www.youtube.com/watch?v=w9mRgkOv2jM

**Comment by NielsPilgaard** [comment]
I'll have a look, thanks for the suggestion.
