### ISSUE TITLE
Suggestion: Integrated Dynamincs

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica5#375]
**Modpack version**
E5 0.5.1

**Enhancement**
It seems that Integrated Dynamics has been ported to 1.15.
2 people have already suggested this on Discord (Glubo, and T3RM1N4T0R).

https://www.curseforge.com/minecraft/mc-mods/integrated-dynamics

**Comment by NielsPilgaard** [comment]
I'll get it added, thank you :)

**Comment by NielsPilgaard** [comment]
https://github.com/CyclopsMC/IntegratedDynamics/issues/890
