### ISSUE TITLE
Pretty Pipes

### ISSUE THREAD

**Issue by merlerm** [NillerMedDild/Enigmatica5#376]
**Modpack version**
0.5.1

**Issue**
Pretty Pipes seems like a plain better implementation of the same concept, with much more functionality. Refined Pipes by themselves don't add much to the pack, and I've seen them cause lag issues in the past (not sure if that's been fixed though). I love Pretty Pipes' throwback concept to Logistic Pipes, and i feel like it would be a cool addition for simple item logistics, and could be used for low tech setups. 
https://www.curseforge.com/minecraft/mc-mods/pretty-pipes

**Comment by NielsPilgaard** [comment]
Thanks for the suggestion, I'll have a look :)

**Comment by MuteTiefling** [comment]
I too would like to see something different. Refined Pipes has been rather disappointing so far... Even in my limited use, I noticed lag when the fluid ones got backed up. The item ones just drop everything on the ground, which is another problem entirely.

**Comment by NielsPilgaard** [comment]
Pretty Pipes seems nice, I will add it, but Refined Pipes is able to move liquid and energy, which Pretty Pipes cannot, so it's not a replacement.
