### ISSUE TITLE
Suggestion: Some form of fluid trash

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica5#380]
I can't seem to find anything that provides this functionality in the pack, but it's something that I feel is really lacking. Especially with the recent addition of Immersive Engineering. Having a way to dump excess creosote would be very helpful.

**Comment by NielsPilgaard** [comment]
Doesn't Cyclic have a trash can that works with everything? :)

**Comment by NielsPilgaard** [comment]
Nope, I got that wrong :P

**Comment by MuteTiefling** [comment]
It used to. But it seems like a lot of Cyclic hasn't been ported over yet.

I honestly have no clue what else does, however, that's been ported to 1.15. NuclearCraft was my go-to in 1.12, or Cyclic if it wasn't available. 

I used to be able to void liquids into a kitchen sink too, but that only seems to accept 16 buckets before I have to break and place it again (that may be a bug, not sure)

**Comment by NielsPilgaard** [comment]
The sink no longer voids fluids from pipes, I think buckets should work still.

**Comment by NielsPilgaard** [comment]
https://github.com/blay09/CookingForBlockheads/issues/278

**Comment by MuteTiefling** [comment]
Hrm, so I guess at the worst I could use a modular router to fill buckets and click a sink. Not ideal since it can't handles quantities less than a bucket, but for something like creosote I'm not concerned with voiding it all anyway, just voiding excess. So that'll work fine.

**Comment by NielsPilgaard** [comment]
Something should become available eventually anyway, I'mma close this for the time being :)
