### ISSUE TITLE
Recipe Conflict: Beams/Sticks

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica5#381]
**Modpack version**
0.5.1

**Issue**
Two stripped spruce logs should craft into two Spruce Beams. However, you get sticks instead. Stripped Oak to Beams works fine, but most of the other wood types seem to result in sticks. This persists across restarts. 

**Logs**

[crafttweaker.log](https://github.com/NillerMedDild/Enigmatica5/files/4839857/crafttweaker.log)
[latest.log](https://github.com/NillerMedDild/Enigmatica5/files/4839858/latest.log)

**Comment by NielsPilgaard** [comment]
Thank you for the report, I will investigate the issue.
