### ISSUE TITLE
Suggestion: Expanded liquid fuels for PneumaticCraft

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica5#382]
Would be nice to see some extra fuels added as valid for PneumaticCraft.

Ethylene, Ethanol, Bioethanol, and Biodiesel would all potentially be good. 

Also, some of the currently available ones make little sense (lava, liquid lithium, molten plastic, liquid steam). I believe these would have been auto registered by heat.

**Comment by NielsPilgaard** [comment]
Good idea :)

**Comment by Ridanisaurus** [comment]
In Build 48+ of PneumaticCraft, the mod author introduce further compat with Mekanism, allowing Liquid Hydrogen and Ethylene to be used as a fuel already, also allowing Mekanism heating machines to also be used with PNC.

**Comment by NielsPilgaard** [comment]
> In Build 48+ of PneumaticCraft, the mod author introduce further compat with Mekanism, allowing Liquid Hydrogen and Ethylene to be used as a fuel already, also allowing Mekanism heating machines to also be used with PNC.

Considering that, I'll say that's fine for now, don't really have time to spend on this :(
