### ISSUE TITLE
Trouble with Copper processing with Create / generation with Nature's Aura

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica5#385]
**Modpack version**
0.5.1

**Issue**
Nature's Aura's Powder of the Bountiful Core (ore generator) produces Mekanism Copper which can't be directly processed

I was testing Create's ore processing overnight (roughly 8 hours) and feeding it ore's made by Nature's Aura. In total I got the following after everything was processed and compacted to block form:

- Aluminum Blocks : 362
- Uranium Blocks : 119
- Lapis Blocks : 459
- Lead Blocks : 462
- Gold Blocks : 161
- Nickel Blocks : 27
- Diamond Blocks : 10
- Emerald Blocks:  8
- Redstone Blocks : 262
- Iron Blocks : 927
- Coal Blocks : 2126
- Tin Blocks : 563
- Osmium Blocks : 468
- Zinc Blocks : 311
- Silver Blocks : 310

I noticed the lack of copper and thought that it was a bug that none was being produced, but upon further inspection, it's just getting Mek copper which would have to be converted to Immersive Copper in a crafting table before Create can process it. So I was destroying the ore all night instead of processing it. 

Processing of this copper also results in Create's nuggets, instead of Immersive's nuggets of copper. So another crafting table conversion is required before being able to do anything with it.

The distribution of a few of those seems uncommonly low too. Diamond, emerald, nickel and gold could all probably stand a bit of a boost. 

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by MuteTiefling** [comment]
Altering the Nature's Aura config to the following seems to fix the Copper issue

`oreExceptions = ["mekanism:copper_ore", "tmechworks:copper_ore"]`

Trying to figure out how to re-distribute ores, however, and that's just a mess.

**Comment by MuteTiefling** [comment]
Actually, it requires blocking all of the other possible coppers... 

`oreExceptions = ["mekanism:copper_ore", "tmechworks:copper_ore", "occultism:copper_ore", "create:copper_ore"]`

and adjusting the rates appears to be as simple as re-adding the tag with an override quantity. 9000 would be absurd, but this is just the test I was making to see if it worked. 

`additionalOres = ["#forge:ores/copper:9000:overworld"]`

Still not sure it actually _is_ working, though since 9000 should be nearly twice Coal and I'm getting about half as much copper as coal. 

I've also noticed now that I've stopped getting immersive aluminum and am now getting tinker's mechworks aluminum. So probably a pass like this for all ores will be necessary.

**Comment by NielsPilgaard** [comment]
Thanks for the report. I feel like is a mod bug, since I actively remove the tags from the ores we don't want.

**Comment by MuteTiefling** [comment]
I think this gets rid of all the unwanted blocks:

`oreExceptions = ["mekanism:copper_ore", "tmechworks:copper_ore", "occultism:copper_ore", "create:copper_ore", "occultism:silver_ore", "tmechworks:aluminum_ore"]`

I've been testing with altering distribution though and either I'm just dumb and don't understand how to do it, or the config doesn't work. Maybe you'll have more luck than me though.

**Comment by MuteTiefling** [comment]
Spoke with ellpeck on discord. The additionalOres config is not currently working with tags as intended: https://github.com/Ellpeck/NaturesAura/issues/127

**Comment by NielsPilgaard** [comment]
Did you bring up the issue about Nature's Aura generating blocks that have had their tags removed? :)

**Comment by NielsPilgaard** [comment]
Oh and thanks a lot for providing the fix and reacing out to the mod author :D

**Comment by MuteTiefling** [comment]
> Did you bring up the issue about Nature's Aura generating blocks that have had their tags removed? :)

I didn't since I'm not really informed on how all that works. I kinda get the impression that what you're doing to remove the tags may only impact crafting though. For example, all of the copper ores still have a block tag of  forge:ores/copper

![copper](https://user-images.githubusercontent.com/9543430/85958345-e2ba1180-b962-11ea-8af8-4f2fd0e80b3a.PNG)

**Comment by NielsPilgaard** [comment]
Ah right, he's probably checking the block tag not item tag ^^'

**Comment by MuteTiefling** [comment]
I'd be curious to see if that fixes things for Botania too

**Comment by theboo** [comment]
doesnt matter how it is generated... washing crushed copper ore with create makes copper nuggets which you cannot do anything with(cant convert nuggets in crafting table)... in fact there is are a few things that are broken as far as washing crushed ore in to nuggets goes.. Ill make a separate issue after compiling a list
