### ISSUE TITLE
IE Jerry Can / PNC tank crafting issues

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica5#387]
**Modpack version**
0.5.1

**Issue**
Both of these items are meant to be able to be used to batch craft things that require buckets of fluid (IE treated wood, IE concrete, PNC speed upgrades, to name a few), but neither of them work in the crafting grid. I can confirm both of these work in a small test pack I've put together with no crafttweaker modifications. 

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NielsPilgaard** [comment]
Thanks for the report! Sad that this doesn't work. 
If you get an abundance of time, would you mind adding KubeJS to that small test pack and see if the recipes stop working with bulk liquid?

**Comment by MuteTiefling** [comment]
Sure. No need to configure it in any way?

**Comment by MuteTiefling** [comment]
Ah, yep. No need to configure it. It stops working as soon as I add the mod to my world.

**Comment by NielsPilgaard** [comment]
Thought so, thanks for checking and reporting :D

**Comment by MuteTiefling** [comment]
No trouble. Glad to help :D
