### ISSUE TITLE
Immersive Arc Furnace misusing materials for brass

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica5#388]
**Modpack version**
0.5.1

**Issue**
To make brass, 3 copper and 1 zinc are required to begin crafting. But it only actually uses one copper and one zinc. 

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NielsPilgaard** [comment]
Thanks, I'll get that fixed :D

**Comment by NielsPilgaard** [comment]
Reported it here: https://github.com/BluSunrize/ImmersiveEngineering/issues/4038

**Comment by NielsPilgaard** [comment]
Fixed in dev of IE
