### ISSUE TITLE
Create bulk washing recipes not making IE nugs for some ores

### ISSUE THREAD

**Issue by theboo** [NillerMedDild/Enigmatica5#389]
Washing crushed copper ore with create bulk washing makes Create copper nuggets. You can do literally nothing with them as they don't even have a conversion recipe.

Washing crushed aluminum ore makes tinker's mechworks aluminum nuggets. This does have a conversion recipe but it is still a pain to do so.

Washing crushed silver ore makes occultism silver nuggets. Same deal as aluminum

**Comment by theboo** [comment]
on further inspection, the silver and aluminum issues only appear on servers(i have this issue on both the official server and my test server), in single player IE silver and aluminum nugs are made like they should. 

In single player, washing copper ore still makes create nugs but there is a recipe to convert, on both servers i tried there is no conversion recipe

**Comment by theboo** [comment]
i tried giving copper nugs the same treatment you did with plates/sheets, and added this json to the enigmatica datapack in my instance... but it doesnt seem to work, idk what im doing wrong lol, i also tried disabling the create nugget recipe which didnt help. 
```
{
    "type": "create:splashing",
    "ingredients": [
    	{
    		"item": "create:crushed_copper_ore"
    	}
    ], 
	"results": [
		{
			"item": "immersiveengineering:nugget_copper",
			"count": 10
		}
		{	"item": "immersiveengineering:nugget_copper",
			"chance": 0.5,
			"count": 5
		}	
	]
}

**Comment by theboo** [comment]
i was missing a "," between results lmao

**Comment by theboo** [comment]
i was able to fix copper nuggets... i dont know what to do about the server issues with silver and aluminum nugs though

**Comment by theboo** [comment]
copper nuggets is fixed in single player... my json doesnt seem to be working on servers? I also added your IE plate/sheets fixes to my server and they dont seem to work either... maybe there is something borked with openloader and servers right now?

**Comment by NielsPilgaard** [comment]
Works fine for me :)
