### ISSUE TITLE
Torch Slab Mod not actually added to current Beta

### ISSUE THREAD

**Issue by Draco856** [NillerMedDild/Enigmatica5#39]
**Modpack version**
0.3.3

**Issue**
Torch Slabs Mod not actually added as stated in Changelog. Tested by downloading to a new profile, 97 mods downloaded, Torch Slabs Mod wasn't part of the list, and upon unlocking the profile and looking for it via search, it wasn't listed as Installed.

**Comment by NielsPilgaard** [comment]
Err woops :P thanks for letting me know!
