### ISSUE TITLE
Prismarine dupe loop

### ISSUE THREAD

**Issue by jt1399** [NillerMedDild/Enigmatica5#391]
**Modpack version**
0.5.1

**Issue**
1. crush prismarine crystal in a create mod crushing set up give 2-4 prismarine shards
2. enrich the prismarine shards in a mekanism mod enricher to get more prismarine crystals

**Comment by NielsPilgaard** [comment]
Thanks for the report, we're looking into it :)

**Comment by NielsPilgaard** [comment]
I usually don't close issues before the update containing the fix has been built @Halfdeaf :)

**Comment by Halfdeaf** [comment]
Oops, I knew that. Got too excited to actually squash a bug :)
