### ISSUE TITLE
Suggestion: Ambient Sounds 3

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica5#396]
**Modpack version**
E5 0.5.x

**Enhancement**
This could be a nice addition to add that extra little to the outside world.
Mod: Ambient Sounds 3
Link: https://www.curseforge.com/minecraft/mc-mods/ambientsounds

**Comment by NielsPilgaard** [comment]
I'm a bit hesitant to add that, but I'll check it out!

**Comment by Halfdeaf** [comment]
I added it in with my testing of Terraforged and I'm loving it. Big thumbs up from me

**Comment by NielsPilgaard** [comment]
Will give it a shot, seems nice through my limited testing.
