### ISSUE TITLE
Suggestion: Miner's Helmet

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica5#397]
**Modpack version**
E5 0.5.x

**Enhancement**
A lot of people like to use OptiFine for its dynamic lights functionality, but as you know, OptiFine is still quite buggy at the moment. This could be something worth looking into as an alternative.
Mod: Miner's Helmet
Link: https://www.curseforge.com/minecraft/mc-mods/miners-helmet

**Comment by NielsPilgaard** [comment]
I'm a bit afraid of how they managed to create the dynamic lighting effect, but I'll have a look :)
