### ISSUE TITLE
Suggestion: Just Enough Calculation

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica5#398]
I'd like to see the mod [Just Enough Calculation](https://www.curseforge.com/minecraft/mc-mods/just-enough-calculation) added to the pack if it's not too much trouble. 

It's very handy to have a crafting calculator to determine the quantities needed for any craft. I rarely use things like RS or AE2 for auto crafting anymore as I'm just kind of bored of them, but when setting up a complicated craft with PNC drones or Create, or any of the other fun alternatives, it can be nice to know how many of each item I'll need at each step. Just Enough Calculation fits that need nicely.

**Comment by NielsPilgaard** [comment]
I will think about it good sir :)

**Comment by NielsPilgaard** [comment]
I think this is too specific to benefit the majority of users, sorry but no :)

**Comment by MuteTiefling** [comment]
Fair enough! Thanks anyway
