### ISSUE TITLE
Add Project Vibrant Journeys

### ISSUE THREAD

**Issue by hvdklauw** [NillerMedDild/Enigmatica5#404]
Please add https://www.curseforge.com/minecraft/mc-mods/project-vibrant-journeys to the pack.

It adds a few biomes which will be included in both the terraforges en BoP world types, but in general it adds little animals and things on the ground everywhere, making the world seem more alive without being intrusive.

**Comment by NielsPilgaard** [comment]
Thanks for the suggestion. I have considered it before, but I was/am afraid that it would just add clutter and useless entities, but it does look good. I'll have a look in-game.

**Comment by Halfdeaf** [comment]
Going to add my endorsement on this one :)

**Comment by Ridanisaurus** [comment]
Likewise

**Comment by merlerm** [comment]
Add my support! I'd even consider swapping BoP for it to remove clutter, but that would clearly break worlds

**Comment by NielsPilgaard** [comment]
Shit, is it that good? :P

**Comment by Ridanisaurus** [comment]
It adds less stuff than BoP, but what is added is done perfectly. It gives such life to the biomes. Check their Wiki, it has a pretty extensive showcase of what it does.
Link: https://www.orderedchaos.dev/mods/projectvibrantjourneys/

<blockquote></blockquote>

**Comment by MuteTiefling** [comment]
Playing devil's advocate here... It does look really lovely, but it doesn't look like anything that would warrant replacing BoP in an existing pack. I could see someone picking it over BoP for a new pack, but in the context of E5, you'd be tearing out one mod to replace it with practically the same thing.

**Comment by Ridanisaurus** [comment]
Well, the pack is still under development, and of course, replacing BoP with PVJ should only be done on the next major update which would require a world reset, similar case to 0.5.x.

**Comment by hvdklauw** [comment]
I'm not requesting to replace bop at all, it adds things to all world types (and does not add a world type itself)

It just sprinkles the world with life (fly's, snails, slugs, small spiders) and some random items.

Sure it adds biomes and woods but I've seen them been generated in both TerraForged and BoP worlds.

The only thing is that the tree's don't seem to be automatically added to the bonsai tree pots, so some other things might need to be tweaked too.

But it just makes the whole world seem way more random and alive in all biomes without replacing it all.

**Comment by Halfdeaf** [comment]
Been testing. Works well but needs tweaking both to add clutter to BoP biomes and tweaking biome weights

**Comment by NielsPilgaard** [comment]
You volunteer to do said tweaking, right? :D iirc I saw that on Discord

**Comment by Halfdeaf** [comment]
Absolutely already started planning for it

**Comment by NielsPilgaard** [comment]
Will be adding this as a part of https://github.com/NillerMedDild/Enigmatica5/projects/2


<blockquote><img src="https://avatars2.githubusercontent.com/u/21295394?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/NillerMedDild/Enigmatica5">NillerMedDild/Enigmatica5</a></strong></div><div>The official repository and issue-tracker for Enigmatica 5 - NillerMedDild/Enigmatica5</div></blockquote>
