### ISSUE TITLE
new stick recipe to fix beam conflict conflicts with macaw's tile logs recipe

### ISSUE THREAD

**Issue by theboo** [NillerMedDild/Enigmatica5#406]
**Modpack version**
0.5.2

commit 22e2eb3cfb6edac995a472b2db4ea99af52c9e4e to fix logs>sticks/beams recipe conflicts now conflicts with macaw's tile log recipes xD the macaw's recipes override

https://gyazo.com/2516b373d19f3219dcb288c6f66074be

**Comment by NielsPilgaard** [comment]
That's odd, it didn't conflict during my testing. Thanks for letting me know.
Edit: I didn't check stripped logs ^^'
