### ISSUE TITLE
Commit reducing demons dream seeds seems to have removed all modded seeds from grass drops

### ISSUE THREAD

**Issue by theboo** [NillerMedDild/Enigmatica5#407]
just making an issue for this for tracking

**Comment by merlerm** [comment]
This seems to still be a problem for the occultism seeds. Some discord users reported them not dropping at all for grass and some quick testing by me seems to confirm this.

**Comment by NielsPilgaard** [comment]
Interesting, the Occultism datapack is correct and I haven't altered it. I'll have a look.
