### ISSUE TITLE
productive bees

### ISSUE THREAD

**Issue by theboo** [NillerMedDild/Enigmatica5#408]
cant believe i'm saying this as forestry bees was always up there with ic2 in my least favorite mods list, but after watching Vallen's recent bit-by-bit and playing with it a little, it actually seems like a fun useful mod in a pack with no real non destructive oregen(besides botania). All recipes and bee production seem to be changeable with datapacks, and has support for just about everything.

https://www.curseforge.com/minecraft/mc-mods/productivebees/files/2994361

**Comment by Halfdeaf** [comment]
Looks pretty good. I haven't delved into the gameplay but it seems to have good configurability and the hives spawn in modded biomes

**Comment by NillerMedDild** [comment]
Also investigate https://www.curseforge.com/minecraft/mc-mods/resourceful-bees
