### ISSUE TITLE
Applied Energistics

### ISSUE THREAD

**Issue by theboo** [NillerMedDild/Enigmatica5#409]
Alpha... but it's a thing now! 

https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2/files/2998317

**Comment by NielsPilgaard** [comment]
Waiting till beta, and maybe longer than that :)

**Comment by TGMax233Michael** [comment]
The beta version of **Applied Energistic 2** has been released on **curseforge**.
URL: https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2/files/3015191
Please Add it,I miss this mod for a long time.

**Comment by NielsPilgaard** [comment]
We have decided not to add AE2 after all.
