### ISSUE TITLE
Reliquiary

### ISSUE THREAD

**Issue by merlerm** [NillerMedDild/Enigmatica5#410]
https://www.curseforge.com/minecraft/mc-mods/reliquary-v1-3

I'll leave this here in case you want to check it out, it's been a classic mod in many 1.12 modpacks and i think it'd fit nicely. I've done some testing and couldn't find any glaring issue straight away

**Comment by NielsPilgaard** [comment]
I don't really like it tbh, I find the mob drops annoying :P but worth another look.

**Comment by NielsPilgaard** [comment]
Yeah no, I still don't like it :P
