### ISSUE TITLE
Biome distribution

### ISSUE THREAD

**Issue by Halfdeaf** [NillerMedDild/Enigmatica5#411]
If we add Project Vibrant Journeys there is some overlap with Biomes o` Plenty. Some biomes will need to be removed

* biomesoplenty:redwood_forest
* biomesoplenty:redwood_forest_edge

**Biome Registry:**
https://gist.github.com/Halfdeaf/cf1c91a225bd4d94d4c6554edbde9426

**Comment by merlerm** [comment]
Here's all the duplicate/similar biomes besides redwood between BoP and PVJ (as far as I can see). Might be worth investigating and looking if they're different enough to warrant keeping both.

- biomesoplenty:boreal_forest/projectvibrantjourneys:boreal_forest
- biomesoplenty:prairie/projectvibrantjourneys:prairie
- biomesoplenty:seasonal_forest/projectvibrantjourneys:aspen_grove
- biomesoplenty:chaparral/biomesoplenty:overgrown_cliffs/projectvibrantjourneys:overgrown_spires

**Comment by Halfdeaf** [comment]
There might also be some we'd want to remove in Terraforged terrain but keep for a BoP terrain. Given that TF completely negates the intended height map some will look different between the two.

**Comment by NielsPilgaard** [comment]
What's the status on this? I should've asked before changing labels :P

**Comment by Halfdeaf** [comment]
It's indeed ready for testing
