### ISSUE TITLE
Terraforged tag manipulation

### ISSUE THREAD

**Issue by Halfdeaf** [NillerMedDild/Enigmatica5#412]
Remove the tag **forge:wg_stone** from blocks we don't want to be generated in the strata layers 

https://github.com/NillerMedDild/Enigmatica5/projects/2#card-41535245

Block with the block tag

* create:dolomite
* create:gabbro
* create:limestone
* create:natural_scoria
* create:weathered_limestone
* minecraft:andesite
* minecraft:diorite
* minecraft:granite
* minecraft:stone
* quark:jasper
* quark:limestone
* quark:marble
* quark:slate

[Block registry with tags](https://docs.google.com/spreadsheets/d/12YPF8-EgyFbfmoLmUQb2wzVegekwyY4dtgRrwYc9IyI/edit#gid=767728834)

**Comment by NielsPilgaard** [comment]
On one side I really like the strata layers, but on the other hand it's annoying not to have ores in the top Y levels of the world :/ in the current default, the strata layer generation is disabled.

What are your thoughts?

**Comment by Halfdeaf** [comment]
I agree, I'm looking for a way to make it possible. Oreveins should be able to generate in those layer if we add them to the datapacks. I'm also hoping there's a way to increase the frequency of stone and maybe control how the type distribute. However this is dead in the water at the moment because removing the tag does nothing at the moment.

**Comment by NielsPilgaard** [comment]
Oh, that sucks. 
Getting ores to generate in the strata layer should be simple enough, but I'd rather not as it would be ugly af :P

**Comment by Halfdeaf** [comment]
Indeed, the crazy way would be to add our own custom ores XD talk about a can of worms

**Comment by NielsPilgaard** [comment]
Even if we did that, it would produce the issue of 9 different coppers not stacking in the inventory though.

**Comment by Halfdeaf** [comment]
True

**Comment by Halfdeaf** [comment]
Actually no that's not true. If we were to do something like that we could always make sure the block's loot table would just contain the stone variant item

**Comment by NielsPilgaard** [comment]
Ah yes! Or a non-block drop even.

**Comment by Halfdeaf** [comment]
Closing for now. Will re-open if we find a way to customize the strata
