### ISSUE TITLE
Investigate Resourceful Bees

### ISSUE THREAD

**Issue by NielsPilgaard** [NillerMedDild/Enigmatica5#415]
https://www.curseforge.com/minecraft/mc-mods/resourceful-bees

**Comment by Halfdeaf** [comment]
Had a bit of a look. It has some nice features to customize and Rid and I were able to mock up a quick Easter Egg bee.
It has 14 pre made bees that need some tweaking but shouldn't be too hard. I made a bee in less time than it took me to load the client after crash

http://prntscr.com/thq4t5
Missing a language file but still quick work

<blockquote><img src="https://image.prntscr.com/image/khsW5LXrSuaOErkG2D5oNA.png" width="48" align="right"><div>Lightshot</div><div><strong><a href="https://prnt.sc/thq4t5">Screenshot</a></strong></div><div>Captured with Lightshot</div></blockquote>

**Comment by NielsPilgaard** [comment]
That bee is pure horror, I love it.

**Comment by theboo** [comment]
BooBee!!!!

**Comment by NielsPilgaard** [comment]
Will re-evaluate this for 1.16 once/if it updates :)
