### ISSUE TITLE
Is it on purpose that industrial hemp can only be grown manually (on farmland) or in a cloche? And not in a botany pot?

### ISSUE THREAD

**Issue by Flabort** [NillerMedDild/Enigmatica5#417]
**Modpack version**
0.5.2

**Issue**
Industrial hemp is used a lot in immersive engineering, but in order to obtain it, it must be grown. To automate it, you currently need an advanced setup to break the tops off and collect it, or to construct a garden cloche - a much more complex recipe than the botany pot, and still more complex to set up, requiring power and water and a separate pipe to remove items automatically.

I'd like to know if this was a design choice, or a limitation, or an oversight. I'd understand any of these three cases, and if it's the first I won't argue the issue any further - I can kind of see why such a choice would be made, even if I don't personally agree with it.

**Logs**
non-applicable

**Comment by NielsPilgaard** [comment]
We had to add it ourselves, it's in 0.5.3 :)

**Comment by Flabort** [comment]
Thanks, appreciate the quick answer.
