### ISSUE TITLE
Annoying dupe glitch in RS

### ISSUE THREAD

**Issue by theboo** [NillerMedDild/Enigmatica5#418]
https://github.com/refinedmods/refinedstorage/issues/2608#issue-655976330 

might wanna put out a 0.5.5 for this one xD anytime someone shift clicks a recipe into the RS crafting grid it will pull all of those available resources even above stack limit and not remove them from the system. Couple reports of client side crashes from this as well. Looks like darkere has it fixed.

**Comment by Darkere** [comment]
It's fixed for RS. Waiting for Raoul to fix it for RS addons.

**Comment by raoulvdberge** [comment]
Fixed in latest RS Addons too.

**Comment by Darkere** [comment]
Addons update was missed in 0.5.5

**Comment by NielsPilgaard** [comment]
I wouldn't call it missed, Addons hadn't been updated when I hotfixed.

**Comment by Darkere** [comment]
Oh... My bad. I thought there was another update since.
