### ISSUE TITLE
replace lost corail recipes with KJS/stonecutter

### ISSUE THREAD

**Issue by theboo** [NillerMedDild/Enigmatica5#423]
might be cool to see if we can replace some of the lost corail woodcutter recipes we had with the stonecutter(like minecraft glass to  other mod variants) using kubeJS

**Comment by Ridanisaurus** [comment]
And as for the wood cutting recipes, it seems that this mod could get that work done using the same stonecutter. https://www.curseforge.com/minecraft/mc-mods/actually-useful-stonecutter

<blockquote><div><strong><a href="https://www.curseforge.com/minecraft/mc-mods/actually-useful-stonecutter">Attention Required! | Cloudflare</a></strong></div></blockquote>

**Comment by merlerm** [comment]
Isn't that basically what a mekanism sawmill does already though?

**Comment by Discomanco** [comment]
Meks Sawmill is only logs -> planks and planks -> sticks yeah? And various wood products to planks & sticks

**Comment by NielsPilgaard** [comment]
#425 
Sounds good to me!

**Comment by NielsPilgaard** [comment]
> might be cool to see if we can replace some of the lost corail woodcutter recipes we had with the stonecutter(like minecraft glass to other mod variants) using kubeJS

Minecraft glass to other mod variants weren't added by me, do you happen to remember them?

**Comment by NielsPilgaard** [comment]
I marked this as fixed because I re-added the recipes for the Woodcutter I made btw, not because it's "fully" fixed

**Comment by theboo** [comment]
i still have an instance with corail woodcutter... ill grab some screenshots in a bit

**Comment by theboo** [comment]
well i may be an idiot... i think the stuff i was talking about is already in the stone cutter lol... dont mind me xD

**Comment by theboo** [comment]
https://www.curseforge.com/minecraft/mc-mods/woodcutter-forge iitemstack just made this lol
