### ISSUE TITLE
Minecolonies 

### ISSUE THREAD

**Issue by creed333** [NillerMedDild/Enigmatica5#424]
**Modpack version**
Input modpack version here MineColonies 0.13.14 Alpha of Enigmatica5 - 0.5.2

**Issue**
Input short description of the issue here - Unable to access sim inventory when I want to take items from them. It worked initially, stopped working. Conflict with builder asking for chest or oak pressure plate and it seems to want the vanilla chest, not the modded 'oak' (or other chest). Works fine if I cheat the vanilla chest in.  

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NielsPilgaard** [comment]
Please update the modpack and see if the issue persists :)
