### ISSUE TITLE
Integrated Dynamics: Meneglin Biome generates with no decoration

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica5#427]
**Modpack version**
0.5.3

**Issue**
In fact, every feature appears to be missing. There are no caves, no trees, no tall grass or flowers. My end stronghold was supposed to generate here and that's missing too. It's just a big blank area with grass and stone. 

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NielsPilgaard** [comment]
Thanks for the report, yikes. Could I have a screenshot or 3 please?

**Comment by MuteTiefling** [comment]
Here's an aerial view.

![2020-07-18_09 23 31](https://user-images.githubusercontent.com/9543430/87853502-7898ea80-c8d8-11ea-9dfb-d06cdbc68f86.png)

And one underground at those same coordinates. 

![2020-07-18_09 23 59](https://user-images.githubusercontent.com/9543430/87853510-95352280-c8d8-11ea-9bcf-b22b42db6b2a.png)

All of those caves are beyond the boundary of the biome.

**Comment by NielsPilgaard** [comment]
Wow, that's really something :P Thanks!

**Comment by NielsPilgaard** [comment]
Reported, thanks!

**Comment by NielsPilgaard** [comment]
Sorta fixed: Meneglin will spawn in 0.6.0

**Comment by NielsPilgaard** [comment]
Sorta fixed: Meneglin will spawn in 0.6.0
