### ISSUE TITLE
Simple Farming Seeds

### ISSUE THREAD

**Issue by thedirtycap** [NillerMedDild/Enigmatica5#428]
**1.15.2**
Input modpack version here

I can only get regular seeds and hempfiber seeds from breaking tall grass. I have tried changing the config for both simple farming and the mod for hemp seeds and nothing happened. I changed hemp seeds to 0 to not spawn and they still spawned when I hit the grass. I also changed the part of the simple farming config to true in the section that said to change to true if it had conflicting grass drops. I just want to have all the different seeds and vegetables for Simple Farming to get more hearts and have fun!

**Comment by Darkere** [comment]
Modpack version?

**Comment by thedirtycap** [comment]
0.5.5!

**Comment by NielsPilgaard** [comment]
Why did you close the issue?

**Comment by Flabort** [comment]
If you're having issues getting all the seeds still, even if you have found them dropping now, I suggest checking out the Market block. You won't lack for seed types once you have it, it's just one emerald per seed.
