### ISSUE TITLE
Matter Receiver private breaks Transmitters.

### ISSUE THREAD

**Issue by AmyMialee** [NillerMedDild/Enigmatica5#429]
**Modpack version**
0.5.5

**Issue**
When an RFTools receiver is set to private in one dimension, transmitters cannot find any other receivers if they are in another dimension.

**Logs**
It's on the server, didn't test in sp.

**Comment by NielsPilgaard** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NielsPilgaard** [comment]
Will be fixed soon, found it reported here: https://github.com/McJtyMods/RFToolsUtility/issues/13
