### ISSUE TITLE
Obsidian duping with Mekanism

### ISSUE THREAD

**Issue by KrAzYGEEK32** [NillerMedDild/Enigmatica5#430]
**Modpack version**
0.5.5

**Issue**
Steps to replicate: obsidian in an enrichment chamber gives 4 obsidian dust
Each obsidian dust can be smelted back to an obsidian block, thus effectively making 4 from 1. 

I believe this issue arises due to some obsidian shard tag conflict with another mod. I've noticed this issue since 0.5.x and pointed it out on the discord then, but people replied that it was known so I didn't bother with a git issue.im doing it now because it's still not fixed. 

**Logs**
N/A

**Comment by NielsPilgaard** [comment]
I feel like I fixed this once already :P thanks for letting me know!
