### ISSUE TITLE
Minecolonies builder stops working at custom KubeJS deposits

### ISSUE THREAD

**Issue by Flabort** [NillerMedDild/Enigmatica5#431]
**Modpack version**
0.5.5

**Issue**
I wanted to have a builder make a medieval oak tavern, which is sunk into the ground two or three layers, but they stopped working after digging down one layer - refused to place blocks, dig any more blocks, anything. They just stood there. I reassigned their task to do something else and had another builder take the task, in case it was that builder bugging out. Nope, the new builder just stood there doing nothing at the build site too. 

Eventually, I realized there was a singled block dug of the next layer down, next to a patch of Uranium deposit, which the game said was from KubeJS, and the discord says were custom blocks made by Niller. As soon as I removed the uranium deposit myself, the builder went from doing nothing, to digging out the next layer at lightning speed; in practically no time at all, it was built completely.

As a test, I made a quick dummy scan of a small space and had a builder try and recreate it in a space where I had placed a uranium deposit block. They refused to work until it was removed, but had no error messages or anything to say about it, they just stood there.

**Comment by NielsPilgaard** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Halfdeaf** [comment]
I don't seem to be able to replicate. The builder does take an incredibly long time to dig out the deposits with a wood shovel though. One thing I did notice is that he seems stuck sometimes and needs an update. No matter if there are ore deposit blocks on the dig site or not. Usually seems like breaking any block gets him going again

**Comment by NielsPilgaard** [comment]
I'll close this for now, but we can always reopen if we manage to reproduce it :)
