### ISSUE TITLE
Random crash while opening an Integrated Dynamics Display Panel

### ISSUE THREAD

**Issue by AmyMialee** [NillerMedDild/Enigmatica5#435]
**Modpack Version**
0.5.5

**Issue**
Random crash while opening an Integrated Dynamics Display Panel.
Doesn't happen every time but it does somewhat often.

**Logs**
Happened on the server.
[latest.log](https://github.com/NillerMedDild/Enigmatica5/files/4957353/latest.log)
[crash-2020-07-22_02.39.35-client.txt](https://github.com/NillerMedDild/Enigmatica5/files/4957354/crash-2020-07-22_02.39.35-client.txt)

**Comment by NielsPilgaard** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NielsPilgaard** [comment]
The issue has been fixed, we're just waiting for a new release now :)

**Comment by AmyMialee** [comment]
Thank God. There might be another issue too but I can't actually test until I can do it without crashing.
