### ISSUE TITLE
Refined Storage Wireless Crafting Grid Duplicates Items

### ISSUE THREAD

**Issue by oodlez** [NillerMedDild/Enigmatica5#437]
**Modpack version**
0.5.5

**Issue**
When crafting with the wireless crafting grid as part of refined storage, the items will end up in your inventory but will not be taken out of your storage. For example, I have 12 red dye and 12 wool. When I shift click to craft a stack of red wool, I receive 64 and my storage system still has 12 dye and wool.

**Logs**

**Comment by NielsPilgaard** [comment]
Thank you for the report. We're aware of the issue, and it will be fixed in the next update :)
