### ISSUE TITLE
Signs

### ISSUE THREAD

**Issue by zachsai** [NillerMedDild/Enigmatica5#438]
**Modpack version**
Input modpack version here
Updated: 7/14/2020

Played: 8 hours ago

Version: 0.5.5

Minecraft Version: 1.15.2

(modded) forge-31.2.30

**Issue**
Vanilla Signs cannot be stacked against each-other, even when crouching. cannot block a 3x3 lava pool for death trap because the middle sign cannot be placed against another sign

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NielsPilgaard** [comment]
Thanks for the report, could you please try sneak + ctrl + place key? :)

**Comment by NielsPilgaard** [comment]
No need to answer that, I just tested it - Reported the issue here: https://github.com/GirafiStudios/PassthroughSigns/issues/11

**Comment by NielsPilgaard** [comment]
And it has been fixed! It'll be in Enigmatica 5 0.6.0 :)
