### ISSUE TITLE
Suggestion - Occultism saplings ought to be available in the Market

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica5#439]
I've been flying around for a very long while now and the world gen seems to have completely destroyed any of the Otherworld trees. I've found exactly one of the underground groves and it had been smashed by other world generation, leaving only a bit of the otherstone behind. 

I think it'd be nice if the saplings could be made available in the market at the cost one Spirit Attuned Gem each.

**Comment by NielsPilgaard** [comment]
That sounds reasonable, thanks for the suggestion :)
