### ISSUE TITLE
gas duping using gas nodes from laser relays

### ISSUE THREAD

**Issue by KrAzYGEEK32** [NillerMedDild/Enigmatica5#442]
**Modpack version**
0.2.0

**Issue**
steps to reproduce: connect tow gas tanks, one filled with a gas, and other empty, link them with gas nodes from laser relays.
the gas seems to be inserting at the output, but not draining the input

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NielsPilgaard** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NielsPilgaard** [comment]
The main menu button incorrectly links here, I moved your issue :)
