### ISSUE TITLE
Suggestion - Blacklist Programmable Controller from Neat

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica5#445]
**Modpack version**
0.5.5

**Issue**
PNC's Programmable Controller uses an invisible entity to perform it's tasks. Neat is currently displaying a health bar for this entity.

I'd suggest it be added to the Neat blacklist

`Blacklist = ["minecraft:shulker", "minecraft:armor_stand", "minecraft:cod", "minecraft:salmon", "minecraft:pufferfish", "minecraft:tropical_fish", "pneumaticcraft:programmable_controller"]`

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NielsPilgaard** [comment]
Good idea, thanks :)
