### ISSUE TITLE
Suggestion - Update Tetra

### ISSUE THREAD

**Issue by Dournbrood** [NillerMedDild/Enigmatica5#452]
The mod just received a QoL update that fixes the generation of ancient ruin structures (apparently they weren't generating in mountainous regions) and also allows the player to add a scanner module to the holosphere that scans for the structures in a 36-block radius, but only in the direction the player is looking.

The scanner module itself is locked behind obtaining 2 Eye of Ender. Finding these structures without it can be horrifically painful especially when you get power hammers generating with no forges.

**Comment by NielsPilgaard** [comment]
We'll update, don't worry.
