### ISSUE TITLE
Bug: Simply Backpacks deleting items

### ISSUE THREAD

**Issue by Dournbrood** [NillerMedDild/Enigmatica5#453]
**Modpack version**
0.5.5

**Issue**
Made a diamond-tier Simply Backpack and subsequently crammed every last one of my max-hone multiple-enchant Tetra tools into it. Closed bag, opened it again. Everything was gone!

This is just speculation, but it seems like the sheer volume of NBT data attached to Tetra tools exceeded some maximum depth or size allocated by Simply Backpacks.
Kind of strange for a _backpack_ mod to have an item deletion bug lol

Edit: Tested with other storage mods to be sure. Shulker boxes and Refined Storage both don't delete tools, so it seems to be an issue with Simply Backpacks itself

**Comment by NielsPilgaard** [comment]
Yikes! I'll have a look asap, thanks for the report.

**Comment by NielsPilgaard** [comment]
Simply Backpacks will be removed in 0.6.0, rendering this obsolete :)
