### ISSUE TITLE
Minecolonies Delivery man not fullfilling Pickup requests.

### ISSUE THREAD

**Issue by NotAPostMan** [NillerMedDild/Enigmatica5#455]
**Modpack version**
0.5.5

**Issue**
The Mineclonies Delivery men will not fulfil pickup Requests for any other colonist. e.g. they will deliver blocks to the builder, but will not collect any unnecessary items from their inventories, or collect anything from the full farmer's hut inventory. when monitoring the request log, it claims all the pickups have the resolver as the player.

If anyone could lend a hand it would be greatly appreciated. I attempted this in a singleplayer world as well as the server I am playing on and I had the same problem with both.

**Comment by NielsPilgaard** [comment]
Thanks for the report! Could you try updating both MineColonies and Structurize and see if that fixes the issue? :)

**Comment by NotAPostMan** [comment]
@NillerMedDild Thanks for the response. I updated the structurize mod in the twitch launcher as it was the only one of the two I could find in the mod list (it did update the minecolonies.jar file in the folder as well) and it seemed to fix the issue with deliverymen, however oak leaves and grass blocks seem to of turned grey after doing this. I am unsure as to which mod add the varying colours of leaves so I am unsure as of which other mod to update. When hovering over these blocks in JEI it says the only available colours they have are grey and silver.

**Comment by NotAPostMan** [comment]
@NillerMedDild Just a quick update, it seems that after restarting the game a couple of times, the problem seems to of fixed itself. Can't explain why, but thank you very much for your help.

**Comment by NielsPilgaard** [comment]
My pleasure, not that I did anything :P
