### ISSUE TITLE
PassableFoliage pathing issues

### ISSUE THREAD

**Issue by Dournbrood** [NillerMedDild/Enigmatica5#456]
**Modpack version**
0.5.5

**Issue**
Title. Minecolonies villagers (though I'm sure this issue is applicable elsewhere) treat the leaf blocks as air, per the PassableFoliage config but also seem to treat it as solid if they're standing inside it when pathing begins. This renders the lumberjack completely useless when faced with trees that generate leaves at or below head-level (spruce for instance) as it will path to the trunk of the tree and get stuck indefinitely. 

Tested with two lumberjacks so far, both got stuck. They seem totally incapable of pathing as they both never returned to bed and then died of starvation.

~~**Possible fix**
Setting `modifyPathFinding` to `false` at line 15 in `passablefoliage-common.toml` fixed the issue for me. Lumberjacks and other entities no longer path through leaves or get stuck in them.~~

Even with `playerOnly` as `true` and `modifyPathFinding` as false in the PassableFoliage configs, it still seems possible for things to be pushed inside leaf blocks by other entities or even by growing saplings. Colonists, hostile and passive mobs alike all get stuck and cannot path.

**Comment by NielsPilgaard** [comment]
Thanks for the report, I'll relay it :)

**Comment by NielsPilgaard** [comment]
Confirmed the bug and reported here: https://github.com/Snownee/PassableFoliage/issues/11
