### ISSUE TITLE
Bug: Tetra bow with zero second draw speed causes world to stop rendering

### ISSUE THREAD

**Issue by jag1g13** [NillerMedDild/Enigmatica5#460]
**Modpack version**
0.5.5

**Issue**
Drawing (happens as soon as bow is drawn) a Tetra bow with a zero second draw speed (recurve bow + bolt tuning) stops the world from rendering, showing just the skybox colour and the UI. This first occured on my server and I've replicated in single player. The bug does not occur with the same bow tuned to have the quickest possible non-zero draw speed.

Disconnecting and reconnecting **does not** fix the rendering (world remains unrendered). Reloading with F3 + T also **does not** fix the rendering. Fully exiting the game **does** fix the rendering.

EDIT: The broken rendering is also persistent across worlds. i.e. if I draw the bow in one world, disconnecting and connecting to another has broken rendering in the new world.

Screenshots are of the bow used, showing how to get zero second draw speed, and the world failing to render after using the bow. Note at the top of the screen that I'm looking at a grass block.

![bow](https://user-images.githubusercontent.com/13136352/89550962-3c371b00-d802-11ea-8fe8-b824313fb2d8.png)
![render-broken](https://user-images.githubusercontent.com/13136352/89550970-3f320b80-d802-11ea-9622-5bdffb42ef07.png)

**Logs**
https://pastebin.com/Bw90xESn
The test occured between 16:05 and 16:10, but nothing unexpected appears in the logs during that time.

I'm happy to report this to Tetra directly if you think that's more appropriate.

**Comment by NielsPilgaard** [comment]
Fixed in Tetra, will update :)
https://www.curseforge.com/minecraft/mc-mods/tetra/files/3018259

<blockquote><div><strong><a href="https://www.curseforge.com/minecraft/mc-mods/tetra/files/3018259">Attention Required! | Cloudflare</a></strong></div></blockquote>
