### ISSUE TITLE
Integrated Tunnels

### ISSUE THREAD

**Issue by mthp1999** [NillerMedDild/Enigmatica5#464]
**Modpack version**
0.5.5

**Issue**

Integrated tunnels, integrated dynamics add on that was just updated to 1.15.2
https://www.curseforge.com/minecraft/mc-mods/integrated-tunnels

**Comment by NielsPilgaard** [comment]
One mod per request please, I made a new one for you here: https://github.com/NillerMedDild/Enigmatica5/issues/465
