### ISSUE TITLE
BlockCarpentry

### ISSUE THREAD

**Issue by NielsPilgaard** [NillerMedDild/Enigmatica5#476]
https://www.curseforge.com/minecraft/mc-mods/blockcarpentry

**Comment by NielsPilgaard** [comment]
Not ready, highly unstable on servers.

**Comment by PianoManu** [comment]
Hey, I'm the creator of the mod. May I ask, what exactly is unstable? It's a pretty new mod and I want to improve it :)
Regards, Manu

**Comment by NielsPilgaard** [comment]
Hi there! Server crashing, this one to be specific: https://github.com/PianoManu/BlockCarpentry/issues/1

**Comment by PianoManu** [comment]
Oh this one. Yeah, I know this problem and I'm already trying to fix it. Unfortunately, I had my exam phase in between and was unable to get it done sooner. Thank you very much!

**Comment by NielsPilgaard** [comment]
I know, no worries :) I hope your exams went well!

**Comment by PianoManu** [comment]
Thanks, it went okay! :)
I think I fixed that. At least I've tested all three versions (1.15.1/1.15.2 **0.7.0**, 1.16.1 **0.2.0**, 1.16.2 **0.2.1**) with "Biomes'o'Plenty" and "Oh The Biomes You'll Go" and it works fine. I also installed Enigmatica5 and tested it together with my mod. I did not encounter any crashes, but I read "CCL Caught an exception rendering a block. See the log for info" four or five times (I've tested more than 50 different blocks from different mods). This error only occured with blocks from CookingForBlockHeads, DarkUtilities, BuildingGadgets, RFToolsPower, so I hope it's not that bad... I'm sorry for the inconvenience, I'm a pretty new and inexperienced modder. If you want, I would be happy if you give my mod a second chance :D
I will test the 1.16.1 version asap.
Regards, Manu

**Comment by NielsPilgaard** [comment]
Sounds good, I'm checking it out in E5 now :)

No worries! It's a learning process :D 
I will also be re-testing the 1.16.1, I'll let you know if I find anything.

**Comment by NielsPilgaard** [comment]
I placed a Diamond Block in a Frame, the server crashed instantly :P
https://gist.github.com/NillerMedDild/ef07476ea865cc121117da3cc9066f19

<blockquote><img src="https://github.githubassets.com/images/modules/gists/gist-og-image.png" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> Gist</div><div><strong><a href="https://gist.github.com/NillerMedDild/ef07476ea865cc121117da3cc9066f19">gist:ef07476ea865cc121117da3cc9066f19</a></strong></div><div>GitHub Gist: instantly share code, notes, and snippets.</div></blockquote>

**Comment by PianoManu** [comment]
Oh man, I'm so dumb... I somehow accidentally tried to render the block on the server side. I don't know why, but it's working perfectly in singleplayer - that's why I never encountered any problems. I was unable to reproduce the error, so I removed the rendering part, that seemed to cause the error, at least that's how I understood it from the crash report. This was unnecessary anyway, as I only used it for debugging. Thanks for being patient with me :D
I've uploaded the fixed version to curseforge, but it's still under review. I'll test it extensively tomorrow. Sorry about the circumstances.
Regards, Manu

**Comment by NielsPilgaard** [comment]
Sure thing, thanks for the quick fix! I recommend that you test on a server in the future though :P

**Comment by NielsPilgaard** [comment]
The server no longer crashes when you place a block in a Frame, now it crashes when you break it again. 
Crash: https://gist.github.com/NillerMedDild/4e3408e2178f94c6b7f48b00642ead37

**Comment by PianoManu** [comment]
Yup, I did as you said and made me a server. I noticed that bug two days ago. Unfortunately, I got sick on thursday, so I had no time for the mod, but I'm feeling better today and found a way to fix this bug. I'm also testing all the other features on my server environment. I'm sorry for all these problems. I'll write again when I've tested everything on the server and in the single player. Thanks for your patience

**Comment by PianoManu** [comment]
I've tested all other blocks and features on my server (found and fixed another bug, that would have led to server crashes). I did not get any more crashes, so I hope it works now correctly. I just uploaded version 0.7.2 (1.15.1/1.15.2) and I'll now wait if anyone reports a bug in the comments. I will try to fix the bugs in the other two versions later today. Best regards

**Comment by NielsPilgaard** [comment]
No worries, thanks for the fixes, will try again soon :D
