### ISSUE TITLE
Minecolonies Baker not working

### ISSUE THREAD

**Issue by darkraven1313** [NillerMedDild/Enigmatica5#477]
**Modpack version**
0.5.5

**Issue**
Mine colonies baker does not produce bread. 

Built the Bakery and assigned a worker. Turned on the bread recipe. Gave the worker 2 stacks of wheat. WOrker started crafting and went through all the wheat. No bread produced. 

**Logs**
NA

**Comment by NielsPilgaard** [comment]
I'm pretty sure I know the cause of this issue, I'll fix it, ty :)

**Comment by NielsPilgaard** [comment]
Apparently the wheat is consumed, and then the bread is slowly made, could that be happening?
