### ISSUE TITLE
Skeleton Horses Causing Crashes

### ISSUE THREAD

**Issue by Keyrative** [NillerMedDild/Enigmatica5#482]
**Modpack version**
Enigmatica 5 0.5.5

**Issue**
Skeleton Horses Crashes the game/server

**Logs**
https://pastebin.com/731rVd3F

Skeleton horses cause a crash when approached, whether in creative or not. Recovery is to kill player where incident happened or server gets stuck in crash loop.

**Comment by NielsPilgaard** [comment]
Setting `max-tick-time` to 0 in server.properties would most likely fix this issue, are you able to check? :)
