### ISSUE TITLE
Astral Sorcery Structures

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica5#484]
**Modpack version**
E5 0.6.0

**Issue**
I noticed that the basic fountain/shrine is spawning way too often, and Jamsn from the server raised this concern as well. The config says the below which just doesn't seem right at all. This is from the PLAINS biome `[world.generation.struct_small]`
 ```#Set this to set the overall chance for this feature to generate. The higher, the rarer.
			#Range: 1 ~ 200000
			generationChance = 140
			#Set the amount this feature tries to generate per chunk
			#Range: 1 ~ 128
			generationAmount = 1```

**Comment by NielsPilgaard** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NielsPilgaard** [comment]
Confirmed, almost doubled it's value.
