### ISSUE TITLE
[1.15.2, E5] Snow under Trees, but no Snow in the Biome

### ISSUE THREAD

**Issue by TheSnowyChickens** [NillerMedDild/Enigmatica5#485]
**Modpack version**
E5 0.6.0
+
Optifine pre30 + OptiForge 0.1.28, powered by Forge 31.2.37

**Issue**
Snow under Trees, but there is no Snow on the ground in this Biome.

**Screenshots**
![2020-09-13_02 27 32](https://user-images.githubusercontent.com/29357962/93007390-f0963080-f568-11ea-90c7-73aea27ffbd0.png)
![2020-09-13_02 27 42](https://user-images.githubusercontent.com/29357962/93007392-f429b780-f568-11ea-889f-51abba649acc.png)
![2020-09-13_02 27 51](https://user-images.githubusercontent.com/29357962/93007394-f8ee6b80-f568-11ea-9447-da578961a885.png)

**Logs**
(I think it is not needed, but just for fun :) )
https://pastebin.pl/view/7900cf20

As discussed in the Discord, the Git issue for the Snow. :)

**Comment by NielsPilgaard** [comment]
I guess the mod Snow Under Trees isn't compatible with TerraForged :)
