### ISSUE TITLE
Suggestion: Flux Network

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica5#486]
**Modpack version**
E5 0.6.0

**Enhancement/Suggestion**
ManiacRobert mentioned in the chat that Flux Network was not added to the pack, apparently it was ported to 1.15.2 already. Not sure if it was not considered for E5, or you just didn't know it was out yet.

**Comment by Ridanisaurus** [comment]
Was just informed by Boo that this was already suggested, and turned down. Sorry for the spam.

**Comment by NielsPilgaard** [comment]
No worries :)
