### ISSUE TITLE
Cobblestone-only recipes are causing issues if only Stone is available underground (Allow Stone in the place of cobblestone in some recipes)

### ISSUE THREAD

**Issue by merlerm** [NillerMedDild/Enigmatica5#487]
**Modpack version**
0.6.0

**Issue**
Most of the new scoria worldgen stones have the forge:stone tag and not the forge:cobblestone tag. This results in crafting inconsistencies, such as trying to craft a shovel with granite giving an excavator, essentially making cobblestone-only crafts locked in areas where normal stone isn't present. The worlgen stones should probably have forge:cobblestone, and the polished variants should have forge:stone.
As far as I can tell, this is an issue with the vanilla stones (granite, andesite, diorite), the create stones and the quark stones.

**Comment by NielsPilgaard** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NielsPilgaard** [comment]
I'd rather leave the tags as-is, to prevent confusion, and then make sure forge:stone can be used in most forge:cobblestone recipes. The Excavator will be changed to use compressed cobblestone.
Have you found any other recipes that need fixing? :)

**Comment by KrAzYGEEK32** [comment]
hey niller, i think making pistons use stone would also be a good idea :P
