### ISSUE TITLE
Pulverizer recipes for Zinc and Aluminum

### ISSUE THREAD

**Issue by KrAzYGEEK32** [NillerMedDild/Enigmatica5#488]
**Modpack version**
 0.6.0
**Issue**
suggestion for adding ore doubling recipes for zinc and aluminum in the Thermal Expansion pulverizer

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NielsPilgaard** [comment]
That'd be nice! I've asked over on the JAOPCA tracker if it's something he wouldn't mind implementing: https://github.com/TheLMiffy1111/JAOPCA/issues/166
If he'd rather not, I'll do it :)
