### ISSUE TITLE
Ritual of the forest not working 

### ISSUE THREAD

**Issue by Darkere** [NillerMedDild/Enigmatica5#489]
**Modpack version**
0.6.0

**Issue**
Growing the tree for natures aura's ritual of the forest doesn't start the ritual.

**Comment by KrAzYGEEK32** [comment]
https://github.com/Ellpeck/NaturesAura/issues/139

seems like its terraforged altering tree growth

**Comment by NielsPilgaard** [comment]
Found this report from TF: https://github.com/TerraForged/TerraForged/issues/157
We can fix it with configs, but would prefer not to go that route as it would turn off fancy sapling growth.

**Comment by Ridanisaurus** [comment]
This issue has been raised again by one of the players on Frank's community server.
If no solution has been found by 0.6.1, maybe adding a custom recipe where it requires all the items of the ritual and gives the output? Something along these lines, just so people can actually progress through the mod.
![image](https://user-images.githubusercontent.com/64355028/94782364-67d21e00-03cb-11eb-91f5-ee732cfc3d8c.png)

If you agree, I would be more than happy to create all these recipes and push them to dev branch.

**Comment by NielsPilgaard** [comment]
Yes please, being locked by TF and IE is annoying :P

**Comment by NielsPilgaard** [comment]
Rid added shapeless recipes for the Tokens as a temporary work-around, considering this.. sorta fixed

**Comment by NielsPilgaard** [comment]
TerraForged released a version with their fix, will verify soon.
