### ISSUE TITLE
Broken Farmland Recipe

### ISSUE THREAD

**Issue by hvdklauw** [NillerMedDild/Enigmatica5#493]
**Modpack version**
0.6

**Issue**
The recipe is with dirt and `Empty Tag: enigmatica:hoes` with as texture the barrier 

Same for the repair of a wooden paxel `Empty Tag: minecraft:planks`
Enrichment recipe for Prismarine Crystals `Empty Tag: forge:dusts/prismarine`

**Comment by NielsPilgaard** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NielsPilgaard** [comment]
I fixed the hoe issue, not so sure about how to fix the others. Especially paxel repair.

**Comment by hvdklauw** [comment]
Sure, it could be an issue with the mod itself, just thought I'd mention them in case it was related.
