### ISSUE TITLE
[Mod Suggestion] Ice and Fire

### ISSUE THREAD

**Issue by KrAzYGEEK32** [NillerMedDild/Enigmatica5#498]
would love to see it added :) i personally love the mod so much

**Comment by NielsPilgaard** [comment]
Hmm.. I don't know. It's a cool mod, but not really suited for a kitchen sink pack.

**Comment by KrAzYGEEK32** [comment]
i feel like itll add to the above ground exploration a bit, currently i run around only for astral temples. tbh i just wanna check it out and didnt see a suggestion for it so i mentioned.

**Comment by NielsPilgaard** [comment]
I've decided not to add it this time around :)
