### ISSUE TITLE
Unable to apply enchants on crystal swords with an anvil

### ISSUE THREAD

**Issue by KrAzYGEEK32** [NillerMedDild/Enigmatica5#499]
**Modpack version**
0.6.0

**Issue**
unable to apply enchants on Astral sorcery crystal swords using an anvil, ive mentioned this on their discord and the response was basically "this is most likely due to another mod", i personally dont know what might be causing it so im reporting here

note: the sword worked fine in an enchantment table. 

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NielsPilgaard** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NielsPilgaard** [comment]
It works just fine for me, which enchant did you try with?

**Comment by KrAzYGEEK32** [comment]
![2020-09-20_03 41 42](https://user-images.githubusercontent.com/59537798/93690205-5f3c3680-faf3-11ea-8a09-fb72b4572787.png)
![2020-09-20_03 41 44](https://user-images.githubusercontent.com/59537798/93690207-62cfbd80-faf3-11ea-9783-d87a98b4653e.png)
![2020-09-20_03 41 46](https://user-images.githubusercontent.com/59537798/93690209-65321780-faf3-11ea-8c7e-8da25394d08e.png)

**Comment by KrAzYGEEK32** [comment]
seems to work on other crystal tools, but not a crystal sword, ive tested on plain crystal swords as well (pulled straight from JEI) but they dont seem to work

**Comment by KrAzYGEEK32** [comment]
ok my bad, ive been thinking from the tool perspective till now, but it seems like its the enchanted book's fault, upon further testing it seems like i can apply enchants to the sword through an anvil but for some reason some enchanted bools dont work, ill do a little more testing and try to figure it out

**Comment by KrAzYGEEK32** [comment]
![2020-09-20_04 03 19](https://user-images.githubusercontent.com/59537798/93690459-3f5a4200-faf6-11ea-819a-871a60e1c0fa.png)
this combo definitely does not work, atleast i figured out that XD

**Comment by KrAzYGEEK32** [comment]
atleast i can sleep well now that i figured out the issue, i can finally get looting on my sword \o/, that fortune 4 is messing up the enchant for some reason
