### ISSUE TITLE
Game crashes when you press ESC

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica5#503]
**Modpack version**
E5 0.6.1

**Issue**
The game crashes during world data save when you press ESC

**Logs**
[crash-2020-09-20_00.16.07-server.txt](https://github.com/NillerMedDild/Enigmatica5/files/5250784/crash-2020-09-20_00.16.07-server.txt)

**Comment by NielsPilgaard** [comment]
Having a hard time reproducing, will continue tomorrow.

**Comment by Ridanisaurus** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/4309

**Comment by KrAzYGEEK32** [comment]
i downloaded 0.6.1 before it was pulled back and noticed this crash only occured for newly created worlds,just wanted to mention.
