### ISSUE TITLE
Thermal Machines Integration

### ISSUE THREAD

**Issue by merlerm** [NillerMedDild/Enigmatica5#504]
**Modpack version**
0.6.0

**Issue**
Some Thermal machines could use more integration recipes, here's a couple examples I came up with, will update with more

-Thermal Centrifugal Separator should be able to process productive bee's combs
-Zinc and Aluminum chunks currently can't be processed with the pulverizer

**Comment by NielsPilgaard** [comment]
The latter will be fixed in 0.6.1, Thermal is working on adding more compat natively, I think we should wait for that :)
