### ISSUE TITLE
Duplicate bug with Integrated-Dynamics

### ISSUE THREAD

**Issue by ManiacRobertWasTaken** [NillerMedDild/Enigmatica5#507]
**Modpack version**
E5 0.6.0

**Issue**
When i break Generator from Integrated-Dynamics, coal or any fuel will be duplicated.

https://vimeo.com/461478298

**Comment by NielsPilgaard** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NielsPilgaard** [comment]
I relayed the issue here: https://github.com/CyclopsMC/IntegratedDynamics/issues/924
Thanks again :)
