### ISSUE TITLE
unable to insert materials into a Coke Oven/Blast furnace from IE

### ISSUE THREAD

**Issue by KrAzYGEEK32** [NillerMedDild/Enigmatica5#509]
**Modpack version**
0.6.1 (doesnt crash old worlds :P) 

**Issue**
i'm unable to insert wood, coal or coal blocks into a coke oven
![2020-09-29_16 50 44](https://user-images.githubusercontent.com/59537798/94553176-bd94b200-0275-11eb-9218-c6f4a1e065f7.png)

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by KrAzYGEEK32** [comment]
same with blast furnace :/

**Comment by NielsPilgaard** [comment]
Hmm.. Possibly fixed by https://github.com/BluSunrize/ImmersiveEngineering/issues/4098 when we update
