### ISSUE TITLE
Quark Stone Brick Variants Unobtainable 

### ISSUE THREAD

**Issue by merlerm** [NillerMedDild/Enigmatica5#510]
**Modpack version**
0.6.0

**Issue**
The brick variations of the quark stones (only those native to quark) are uncraftable right now. They could be added to the stonecutter.

**Comment by NielsPilgaard** [comment]
sorta duplicate of #508, thanks though, will get that fixed.

**Comment by merlerm** [comment]
my bad, i didn't check at all for open issues
