### ISSUE TITLE
Create Sheets Compat

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica5#513]
**Modpack version**
E5 0.6.0

**Issue**
Redstone Link from Create accepts only the Create Brass Plate which is no longer obtainable.

**Screenshot**
![image](https://user-images.githubusercontent.com/64355028/94957739-91379a80-04ee-11eb-911f-bf6392988d5d.png)

**Comment by Ridanisaurus** [comment]
Another recipe broken, Create Integrated Circuit only accepting Create Lapis Sheet instead of EE Lapis Plate.
Ignore the textures of course.
![image](https://user-images.githubusercontent.com/64355028/95000249-649f8380-05bf-11eb-8929-b644cd698e41.png)

**Comment by NielsPilgaard** [comment]
that one was fixed in #500

**Comment by Ridanisaurus** [comment]
Ah, sorry for the duplicate.

**Comment by NielsPilgaard** [comment]
No worries, things are weird with 0.6.1 being pushed but not available :P
