### ISSUE TITLE
Sawdust to Paper Recipes

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica5#520]
**Modpack version**
E5 0.6.2

**Issue**
There are 2 recipes for Sawdust to Paper where the input to output ratio seems a little off.

**Screenshot**
![image](https://user-images.githubusercontent.com/64355028/95300932-31d7e280-0880-11eb-9add-4b0c5d39e91b.png)

**Comment by Ridanisaurus** [comment]
This seems to still be on-going. Both recipes are present in E5 0.6.3.

**Comment by NielsPilgaard** [comment]
Oh, woops ^^'

**Comment by NielsPilgaard** [comment]
Only one is present on my instance of E5 0.6.3 :s
![billede](https://user-images.githubusercontent.com/21295394/96169986-458be480-0f23-11eb-8a18-1af846d65733.png)
