### ISSUE TITLE
Thermal Magnet crashes the client

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica5#522]
**Modpack version**
E5 0.6.2

**Issue**
Thermal Magnet causes the client to disconnect from the server when it attempts to magnet items dropped in the world by another entity such as a machine/player.

**Logs**
The log was too big for pastebin :D
[server-crash-log.txt](https://github.com/NillerMedDild/Enigmatica5/files/5349316/server-crash-log.txt)
[client-crash-log.log](https://github.com/NillerMedDild/Enigmatica5/files/5349317/client-crash-log.log)

**Comment by Darkere** [comment]
I reported this to KingLemming on discord.
