### ISSUE TITLE
Server Disconnect when placing Supply Camp/Ship

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica5#524]
**Modpack version**
E5 0.6.2

**Issue**
When a play attempts to confirm the placement of a Supply Camp/Ship from Minecolonies, they disconnect from the server with the following error `Ridanis lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Payload may not be larger than 32767 bytes`
The same issue is encountered by multiple people on the server, and can be replicated.

**Logs**
Client A: https://gist.github.com/Ridanisaurus/b768b1581975b6e16dbebd894838b97e
Client B: https://gist.github.com/Ridanisaurus/0404994443aa31ef571107bbb88df4ca
Server: https://gist.github.com/Ridanisaurus/bafd1fc6ad4dc67659186beea5d8141b

**Comment by Darkere** [comment]
Fixed in dev https://github.com/ldtteam/minecolonies/issues/5889
