### ISSUE TITLE
ConnectedTexturesMod

### ISSUE THREAD

**Issue by ManiacRobertWasTaken** [NillerMedDild/Enigmatica5#525]
I added into e5 pack and it's working well with mekanism structures.

https://www.curseforge.com/minecraft/mc-mods/ctm

**Comment by NielsPilgaard** [comment]
I'll have a look, thanks for the suggestion! I thought I had added it tbh :P

**Comment by NielsPilgaard** [comment]
I'm not seeing any difference with the Dynamic Tank. Which structure(s) change? :)

**Comment by ManiacRobertWasTaken** [comment]
Thermal evaporation, tank, induction, every multi-block structure from mekanism at least

With
![with](https://user-images.githubusercontent.com/39351347/95688345-49152800-0c12-11eb-9b34-ea692ce7b1ee.png)

Without

![image](https://user-images.githubusercontent.com/39351347/95688351-516d6300-0c12-11eb-9743-445795d5a131.png)

**Comment by NielsPilgaard** [comment]
That's... quite a difference. Thanks for the side-by-side :D
