### ISSUE TITLE
Bambo can not be made into Bambo Bundle, only Bambo Block

### ISSUE THREAD

**Issue by kman3107** [NillerMedDild/Enigmatica5#528]
**Modpack version**
Enigmatica 5 - 0.6.3

**Issue**
Bambo can not be made into Bambo Bundle, only Bambo Block. Bambo Block can not be used to make things like Bambo Fence,
stairs, slabs etc.

If you want people to use the Treated Wood Crafting Table you should probably make some sort of hint for that.
But I'm assuming this is not ment to be.
![BamboConflict](https://user-images.githubusercontent.com/10728652/96142604-93442500-0f02-11eb-9be3-e9445e72db4d.png)

**Comment by NielsPilgaard** [comment]
I'll get that fixed, thank you :)
