### ISSUE TITLE
Crash while attempting to plant Farmer's Delight rice with drones

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica5#530]
**Modpack version**
0.6.3

**Issue**
I had a drone attempting to plant a rice field. To save a little effort, I made my area selection larger than the fields so I could use it to also collect the drops later (since they tend to fall all over the place). Normally with vanilla or even modded crops this is not an issue. The drone will gracefully fail to place a crop if it's not properly tilled land and move on to the next block space.

In this case, it appears that the crash happens as soon as the drone attempts to place the rice in an invalid space (air). 

**Logs**
[crash-2020-10-18_09.51.01-server.txt](https://github.com/NillerMedDild/Enigmatica5/files/5397601/crash-2020-10-18_09.51.01-server.txt)

**Comment by NielsPilgaard** [comment]
Dammit Mute stop crashing the drones :P
Relayed!
