### ISSUE TITLE
Rich Soil Farmland is unobtainable for use in botany pots

### ISSUE THREAD

**Issue by radiomike** [NillerMedDild/Enigmatica5#531]
**Modpack version**
0.6.4

**Issue**
Doesn't seem to be any way of obtaining rich soil farmland from farmer's delight for use in botany pots.

**Comment by NielsPilgaard** [comment]
Thank you for the report, I will investigate the issue.

**Comment by MuteTiefling** [comment]
You need to make Organic Compost and then place that in the world. Over time, it converts to Rich Soil. Working fine in 0.6.4 in my experience

**Comment by radiomike** [comment]
The rich soil part is fine. It's that you can't obtain the 'farmland' version to use in botany pots, which is a top tier soil.

**Comment by NielsPilgaard** [comment]
I'll add a simple recipe, something like Rich Soil + Water bottle -> Rich Soil Farmland
