### ISSUE TITLE
Applied Energistics 2

### ISSUE THREAD

**Issue by unexceptable** [NillerMedDild/Enigmatica5#536]
Hey, I saw you closed https://github.com/NillerMedDild/Enigmatica5/issues/409

I'm curious if you don't plan to include that in this modpack at all, or might be willing to reconsider given it is now a stable release.

I did see you added it to Enigmatica6, so thought I might ask to be sure. ;)

**Comment by NielsPilgaard** [comment]
We will not be adding AE2, and it's not going to remain in E6 :)
