### ISSUE TITLE
Mekanism enrichment chamber not processing all ores (Gems still missing)

### ISSUE THREAD

**Issue by SinKane-MC** [NillerMedDild/Enigmatica5#54]
**Modpack version**
0.3.3

**Issue**
Enrichment chamber will not process Silent's Mechanisms ore: Bauxite, Zinc, Nickle, Silver, Uranium, Bismuth, Platinum or Lead or Blue Power Tungsten

I would assume that these ores should also be able to be doubled using the Mekanism processes?

Cheers!

**Comment by NielsPilgaard** [comment]
I'll get that fixed, thanks for letting me know :)

**Comment by SinKane-MC** [comment]
No Problem! Also seems the Enrichment Chamber and the Smelter  won't process Mekanism copper or tin ore, need to put it in a crafting grid to switch it to silent's before it'll smelt

**Comment by SinKane-MC** [comment]
Just found that neither the Enrichment Chamber, Smelter or Crusher will process Teslatite, Ruby, Amethyst, Sapphire, Malachite or Dimension Shard ores either

**Comment by NielsPilgaard** [comment]
I'll get those added as well, thanks :)
Edit: it's intended that Mekanism ores can't be processed, they shouldn't be obtainable. I'll check that too.

**Comment by SinKane-MC** [comment]
Thank you sir!

**Comment by NielsPilgaard** [comment]
Fixed modded ores not smelting, but not the gems - I have yet to decide how to handle processing of gems :) I'll make a new issue about those, so I don't forget.
