### ISSUE TITLE
Enigmatica 5 uses a version of Emendatus Enigmatica that is no longer listed, making installation impossible.

### ISSUE THREAD

**Issue by Nezumi-chan** [NillerMedDild/Enigmatica5#543]
### Modpack Version

0.6.5

### Describe your issue.

I was reinstalling modpacks imported from old versions of MultiMC to use the new index file and update features of PrismLauncher, when I discovered I could not reinstall this pack, because it expects EmendatusEnigmatica-1.15.2-1.0.10.jar, which is no longer downloadable -- only 1.0.0 is available for that version of Minecraft. This makes installing it impossible, unless I rename the jar and hope for the best.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment]
Thanks for the report :)
@Ridanisaurus any chance you can re-list that file?

**Comment by Ridanisaurus** [comment]
Should be available now.

**Comment by NielsPilgaard** [comment]
Thanks ❤️
