### ISSUE TITLE
1.18.2

### ISSUE THREAD

**Issue by Ostwind128** [NillerMedDild/Enigmatica5#544]
### URL

https://www.curseforge.com/minecraft/mc-mods/terraforged

### Why would you like the mod added?

Will there be a way to customise the world gen in 1.18.2, similar to how it was in 1.16.5? Also perhaps add a preset on how rivers end. It the 1.16.5 version they would tend to just get smaller and end, which I think looks far better than them always ending in a lake, like in the 1.18.2 vision.

**Comment by Darkere** [comment]
This is the Enigmatica 5 Tracker. E5 was for Minecraft 1.15 and is no longer updated. The Repo for E8 can be found here: https://github.com/EnigmaticaModpacks/Enigmatica8. Though that also is no longer receiving updates. 

<blockquote><img src="https://repository-images.githubusercontent.com/427968379/bd03050b-0135-4d6c-a6e6-8f2199fc93a8" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/EnigmaticaModpacks/Enigmatica8">GitHub - EnigmaticaModpacks/Enigmatica8: The official repository and issue-tracker for Enigmatica 8</a></strong></div><div>The official repository and issue-tracker for Enigmatica 8 - EnigmaticaModpacks/Enigmatica8</div></blockquote>
