### ISSUE TITLE
CobbleForDays mod makes world unloadable (Removed CobbleForDays)

### ISSUE THREAD

**Issue by Zarkov2** [NillerMedDild/Enigmatica5#57]
**Modpack version**
0.3.3

**Issue**
When attempting to load a single player world, it got stuck showing an empty void (which usually can be seen briefly when loading worlds). Only the hot bar, HUD and player character were being rendered. I repeatedly tried restarting Minecraft which didn't work. I remembered placing a tier 3 (iron) cobble gen from CobbleForDays under a standard (single) chest just before quitting previously, and so I removed that mod. The world was then loaded successfully.

**Logs**
latest.log and crafttweaker.log are both >2.5 MB, attaching zip.
[logs.zip](https://github.com/NillerMedDild/Enigmatica5/files/4226907/logs.zip)

**Comment by NielsPilgaard** [comment]
Thanks for the report, I'll see if I can reproduce it :)

**Comment by NielsPilgaard** [comment]
I was able to reproduce it, and it seems to be a known issue: https://github.com/LexManos/CobbleForDays/issues/7

Removing the mod, at least for now. Thanks!
