### ISSUE TITLE
Evaluate Vanilla Things

### ISSUE THREAD

**Issue by SaymN** [NillerMedDild/Enigmatica5#62]
[Vanilla Things](https://www.curseforge.com/minecraft/mc-mods/vanilla-things)

**Comment by NielsPilgaard** [comment]
I'll have a look.

**Comment by NielsPilgaard** [comment]
I like Vanilla Things and will include it, but if something like Carpenter's Blocks or Blockcraftery is released for 1.15.2, I will most likely remove Vanilla Things to save some RAM - Just so you know :)
