### ISSUE TITLE
Add Lightest Lamps

### ISSUE THREAD

**Issue by DcZipPL** [NillerMedDild/Enigmatica5#70]
[Lightest Lamps](https://www.curseforge.com/minecraft/mc-mods/lightest-lamps)

**Comment by NielsPilgaard** [comment]
I'll consider it :)

**Comment by NielsPilgaard** [comment]
Very interesting mod, but E5 already has a ton of lighting options.

I like the Gas Centrifuge, but personally think it would be more fitting for a tech/machine mod.

Additionally, breaking and placing the Lamps impact my FPS significantly, it's consistently cut in half for a few seconds after breaking/placing, that's a bit worrying. The Omega Lamp it particularly laggy. I'm not sure there's any way to prevent that when placing so much light at one time, it's just a note :)
