### ISSUE TITLE
Crash on World Load NBT PlayerPositionAndDimension

### ISSUE THREAD

**Issue by janagyjr** [NillerMedDild/Enigmatica5#82]
**Modpack version**
0.3.7

**Issue**
Crashes on trying to load in from an existing world made with an earlier version of the pack.

**Logs**
https://gist.github.com/janagyjr/094f1c8b2da9b6efde8f163bcacdb6f4

**Comment by NielsPilgaard** [comment]
Ouch, sorry about that. You should be able to load the world ID you remove the Ultra Amplified Dimension mod.
I'll work on a fix this evening :)

**Comment by NielsPilgaard** [comment]
Did you try removing Ultra Amplified Dimension?

**Comment by janagyjr** [comment]
I'm trying it now, sorry. Not feeling well today.

**Comment by NielsPilgaard** [comment]
No problem at all, there's no rush :)

**Comment by janagyjr** [comment]
I disabled UAD, was able to log in to the world (I made a copy, jic it didn't work anyway). Still a bazillion errors spamming chat though.

**Comment by NielsPilgaard** [comment]
May I have the copy of the world you made please? The UAD developer made a new update that may have fixed it, and I'd like to verify :)

If you're up for it you can also test yourself, by adding the new mod jar that the developer linked in the issue I linked up above.

**Comment by janagyjr** [comment]
I will provide a link to a download with both worlds and a note.

https://drive.google.com/file/d/1eF11LiBT-fX10NKp-CceL48mSDagqsB_/view?usp=sharing

**Comment by NielsPilgaard** [comment]
Sadly not fixed.

**Comment by NielsPilgaard** [comment]
I'm not seeing any errors in the world with UAD, do you remember what any of them were?

**Comment by NielsPilgaard** [comment]
I messed up and forgot to use the new jar he gave me, he did indeed fix the issue :P
