### ISSUE TITLE
Mod Suggestion: Industrial Foregoing

### ISSUE THREAD

**Issue by ResminZ** [NillerMedDild/Enigmatica5#9]
Industrial Foregoing just got ported to 1.15.1. Could you investigate it and possibly add in new update?

**Comment by ResminZ** [comment]
And also there is 1.15 version of Hwyla, which can make gameplay much easier.

**Comment by NielsPilgaard** [comment]
I'll get those added :) HWYLA will probably be replaced by TOP at some point though
